### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by CanvaChen** [OpenBMB/MiniCPM-V#100]
device_map='auto'

> File "MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 416, in chat
    res, vision_hidden_states = self.generate(
  File "MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 326, in generate
    ) = self.get_vllm_embedding(model_inputs)
  File "MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 148, in get_vllm_embedding
    cur_vllm_emb.scatter_(0, image_indices.view(-1, 1).repeat(1, cur_vllm_emb.shape[-1]),
  File "torch/utils/_device.py", line 78, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument src in method wrapper_CUDA_scatter__src)

**Comment by TheJason1997** [comment]
came across the same issue

**Comment by Cuiunbo** [comment]
This issue does not provide a reproducible context and requires more information to help resolve it. If you still need assistance, please provide your code environment and running code to help us reproduce the issue

**Comment by limian-xixi** [comment]
> This issue does not provide a reproducible context and requires more information to help resolve it. If you still need assistance, please provide your code environment and running code to help us reproduce the issue

你好，可以看下这个issues里面的问题吗？
