### ISSUE TITLE
多轮对话效果不佳

### ISSUE THREAD

**Issue by CanvaChen** [OpenBMB/MiniCPM-V#101]
![image](https://github.com/OpenBMB/MiniCPM-V/assets/18375123/c566c141-ae5c-4d74-a829-f72655775791)

**Comment by xxllp** [comment]
现在支持一次输入多个图片进行问答吗

**Comment by Cuiunbo** [comment]
> 现在支持一次输入多个图片进行问答吗

目前支持多图进行问答， 我们后续会将其使用方式加入文档中
