### ISSUE TITLE
when can we get the code of train from scratch?

### ISSUE THREAD

**Issue by sankexin** [OpenBMB/MiniCPM-V#105]
it`s a good project , But how to train from scratch?,  could you give the train code and dataset?  it is very important, thank you .

**Comment by iceflame89** [comment]
Thanks for your attention.

Since the training code and data are deeply tied to our internal infrastructure, we do not intend to open source this part. Please refer to our fine-tune code and follow our subsequent technical reports to learn the training detail and what data we used.
