### ISSUE TITLE
Deploy MiniCPM-V 2.5 with vllm

### ISSUE THREAD

**Issue by zimoqingfeng** [OpenBMB/MiniCPM-V#107]
Very impressive work for the community! 

I am wondering how to deploy the MiniCPM-V 2.5 with vllm, and I have found that the repo https://github.com/OpenBMB/vllm/commit/94fcfc6582a347de3b26b377169bc78d06184c98 only support MiniCPM-V 2.0.

Looking forward to your reply.

**Comment by iceflame89** [comment]
Thanks for your attention，we will support to deploy the MiniCPM-V 2.5 with vllm soon.

**Comment by Cuiunbo** [comment]
add to the Future Program, temporarily closed issue
