### ISSUE TITLE
mlc-MiniCPM：回答异常

### ISSUE THREAD

**Issue by zjts** [OpenBMB/MiniCPM-V#109]
您好，我下载了mlc-MiniCPM提供的MiniCPM-V 2.0的安卓demo，下载完模型后进行问答，有时会下如图所示的异常输出，请问这个主要是什么原因造成的呢？
使用的手机型号为iqoo neo8 pro,配置为天玑9200+16g内存
![6c6c5aff-eee7-43d8-8686-d050a4b434ea](https://github.com/OpenBMB/MiniCPM-V/assets/44887396/2f55bcbd-6f1c-448a-a7f3-2256eb98e900)

**Comment by Cuiunbo** [comment]
MiniCPM-V2.0的语言模型较小，有时会陷入重复，这属于模型正常行为，我们正在尝试优化。你也可尝试重试来解决这个问题。
另外我们最新版2.5模型重复较少～
