### ISSUE TITLE
minicpmv_example.py  文件不存在

### ISSUE THREAD

**Issue by ipv6ok** [OpenBMB/MiniCPM-V#110]
想使用vllm部署多卡推理，发现教程中提示的minicpmv_example.py 文件 并不存在vllm库中。

**Comment by ipv6ok** [comment]
找到了。正在测试。建议官方提供多卡推理教程。谢谢！

**Comment by Cuiunbo** [comment]
近日将放出多卡推理教程

**Comment by zhuyr97** [comment]
> 找到了。正在测试。建议官方提供多卡推理教程。谢谢！

在哪找到的呢

**Comment by dengruoqing** [comment]
现在还是没有呀？
