### ISSUE TITLE
M1,16G带不动如何卸载？

### ISSUE THREAD

**Issue by ottngzy** [OpenBMB/MiniCPM-V#115]
M1,16G带不动如何卸载？

**Comment by iceflame89** [comment]
你好，Mac 上运行需16GB以上内存

**Comment by ottngzy** [comment]
运行后看到说内存不够。所以我想把已经配置好的模型卸载，请问如何操作？

谢谢。

发件人: Hongji Zhu ***@***.***>
日期: 星期三, 2024年5月22日 13:28
收件人: OpenBMB/MiniCPM-V ***@***.***>
抄送: ottngzy ***@***.***>, Author ***@***.***>
主题: Re: [OpenBMB/MiniCPM-V] M1,16G带不动如何卸载？ (Issue #115)

你好，Mac 上运行需16GB以上内存

―

**Comment by iceflame89** [comment]
你是说删除模型权重？ 缓存的模型权重在～/.cache/huggingface/hub/目录下，可手动删除
