### ISSUE TITLE
请问能不能训练特定场景，然后转成ONNX

### ISSUE THREAD

**Issue by shenyunhuan** [OpenBMB/MiniCPM-V#118]
如题，想在边缘设备上使用，算力不高1.5 TOPS

**Comment by iceflame89** [comment]
感谢关注，1.5 TOPS算力可以试试MiniCPM-V 2.0，2.8B参数，更小的算力需求
转onnx需要根据具体硬件所支持的op进行一些定制适配，欢迎尝试～

**Comment by Cuiunbo** [comment]
@shenyunhuan If you can adapt it to ONNX, welcome! 
欢迎合作！

**Comment by hhhhrc** [comment]
转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.

**Comment by wenxingxingxing** [comment]
> 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.

请问你是怎么转换onnx？

**Comment by hhhhrc** [comment]
> > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> 
> 请问你是怎么转换onnx？

感谢回复，我转换onnx的方式是

`        model_visual = AutoModelForCausalLM.from_pretrained(
            pretrained_model_path,
            device_map="cuda",
            torch_dtype=torch.float16,
            trust_remote_code=True,
            # fp16=True
        ).vpm.eval()
                torch.onnx.export(model_visual,
                          torch.randn(
                              [1, 3, 364, 546]).to(device).half(),
                          onnx_file_path,
                          opset_version=18,
                          input_names=['input'],
                          output_names=['output'],
                          dynamic_axes={
                              'input': {
                                  2: 'height',
                                  3: 'width',
                              },
                              'output': {
                                  1: 'output_dim'
                              }
                          }
                          )
        `
        我的torch版本是2.3.0，请问有可用的解决方案吗？

**Comment by wenxingxingxing** [comment]
> > > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> > 
> > 
> > 请问你是怎么转换onnx？
> 
> 感谢回复，我转换onnx的方式是 model_visual = AutoModelForCausalLM.from_pretrained( pretrained_model_path, device_map="cuda", torch_dtype=torch.float16, trust_remote_code=True, # fp16=True ).vpm.eval()
> 
> torch.onnx.export(model_visual, torch.randn( [1, 3, 364, 546]).to(device).half(), onnx_file_path, opset_version=18, input_names=['input'], output_names=['output'], dynamic_axes={ 'input': { 2: 'height', 3: 'width', }, 'output': { 1: 'output_dim' } } ) 我的torch版本是2.3.0，请问有可用的解决方案吗？

我的也是这个算子不支持。不过我的是onnx opset version 18 is not supported

**Comment by Popsicle0-0** [comment]
> > > > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> > > 
> > > 
> > > 请问你是怎么转换onnx？
> > 
> > 
> > 感谢回复，我转换onnx的方式是 model_visual = AutoModelForCausalLM.from_pretrained( pretrained_model_path, device_map="cuda", torch_dtype=torch.float16, trust_remote_code=True, # fp16=True ).vpm.eval()
> > torch.onnx.export(model_visual, torch.randn( [1, 3, 364, 546]).to(device).half(), onnx_file_path, opset_version=18, input_names=['input'], output_names=['output'], dynamic_axes={ 'input': { 2: 'height', 3: 'width', }, 'output': { 1: 'output_dim' } } ) 我的torch版本是2.3.0，请问有可用的解决方案吗？
> 
> 我的也是这个算子不支持。不过我的是onnx opset version 18 is not supported

参考这个 这个算子是还没支持的https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html#unsupported-operators，不知道能不能找到这个运算符换种写法

**Comment by huibinluo** [comment]
> > > > > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> > > > 
> > > > 
> > > > 请问你是怎么转换onnx？
> > > 
> > > 
> > > 感谢回复，我转换onnx的方式是 model_visual = AutoModelForCausalLM.from_pretrained( pretrained_model_path, device_map="cuda", torch_dtype=torch.float16, trust_remote_code=True, # fp16=True ).vpm.eval()
> > > torch.onnx.export(model_visual, torch.randn( [1, 3, 364, 546]).to(device).half(), onnx_file_path, opset_version=18, input_names=['input'], output_names=['output'], dynamic_axes={ 'input': { 2: 'height', 3: 'width', }, 'output': { 1: 'output_dim' } } ) 我的torch版本是2.3.0，请问有可用的解决方案吗？
> > 
> > 
> > 我的也是这个算子不支持。不过我的是onnx opset version 18 is not supported
> 
> 参考这个 https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html#unsupported-operators 这个算子是还没支持的 不知道能不能找到这个运算符换种写法

你好，这个转换onnx的过程解决了么

**Comment by Popsicle0-0** [comment]
> > > > > > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> > > > > 
> > > > > 
> > > > > 请问你是怎么转换onnx？
> > > > 
> > > > 
> > > > 感谢回复，我转换onnx的方式是 model_visual = AutoModelForCausalLM.from_pretrained( pretrained_model_path, device_map="cuda", torch_dtype=torch.float16, trust_remote_code=True, # fp16=True ).vpm.eval()
> > > > torch.onnx.export(model_visual, torch.randn( [1, 3, 364, 546]).to(device).half(), onnx_file_path, opset_version=18, input_names=['input'], output_names=['output'], dynamic_axes={ 'input': { 2: 'height', 3: 'width', }, 'output': { 1: 'output_dim' } } ) 我的torch版本是2.3.0，请问有可用的解决方案吗？
> > > 
> > > 
> > > 我的也是这个算子不支持。不过我的是onnx opset version 18 is not supported
> > 
> > 
> > 参考这个 https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html#unsupported-operators 这个算子是还没支持的 不知道能不能找到这个运算符换种写法
> 
> 你好，这个转换onnx的过程解决了么

还没有

**Comment by wenxingxingxing** [comment]
> > > > > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> > > > 
> > > > 
> > > > 请问你是怎么转换onnx？
> > > 
> > > 
> > > 感谢回复，我转换onnx的方式是 model_visual = AutoModelForCausalLM.from_pretrained( pretrained_model_path, device_map="cuda", torch_dtype=torch.float16, trust_remote_code=True, # fp16=True ).vpm.eval()
> > > torch.onnx.export(model_visual, torch.randn( [1, 3, 364, 546]).to(device).half(), onnx_file_path, opset_version=18, input_names=['input'], output_names=['output'], dynamic_axes={ 'input': { 2: 'height', 3: 'width', }, 'output': { 1: 'output_dim' } } ) 我的torch版本是2.3.0，请问有可用的解决方案吗？
> > 
> > 
> > 我的也是这个算子不支持。不过我的是onnx opset version 18 is not supported
> 
> 参考这个 https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html#unsupported-operators 这个算子是还没支持的 不知道能不能找到这个运算符换种写法

这个是一个三次方的算子，能不能进行算子替换来实现onnx转换

**Comment by wenxingxingxing** [comment]
> > > > > > > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> > > > > > 
> > > > > > 
> > > > > > 请问你是怎么转换onnx？
> > > > > 
> > > > > 
> > > > > 感谢回复，我转换onnx的方式是 model_visual = AutoModelForCausalLM.from_pretrained( pretrained_model_path, device_map="cuda", torch_dtype=torch.float16, trust_remote_code=True, # fp16=True ).vpm.eval()
> > > > > torch.onnx.export(model_visual, torch.randn( [1, 3, 364, 546]).to(device).half(), onnx_file_path, opset_version=18, input_names=['input'], output_names=['output'], dynamic_axes={ 'input': { 2: 'height', 3: 'width', }, 'output': { 1: 'output_dim' } } ) 我的torch版本是2.3.0，请问有可用的解决方案吗？
> > > > 
> > > > 
> > > > 我的也是这个算子不支持。不过我的是onnx opset version 18 is not supported
> > > 
> > > 
> > > 参考这个 https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html#unsupported-operators 这个算子是还没支持的 不知道能不能找到这个运算符换种写法
> > 
> > 
> > 你好，这个转换onnx的过程解决了么
> 
> 还没有

我这边的解决方式是在torch.nn.functional.py中找到这个算子的转换函数，利用upsample函数替换

**Comment by Popsicle0-0** [comment]
> > > > > > > > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> > > > > > > 
> > > > > > > 
> > > > > > > 请问你是怎么转换onnx？
> > > > > > 
> > > > > > 
> > > > > > 感谢回复，我转换onnx的方式是 model_visual = AutoModelForCausalLM.from_pretrained( pretrained_model_path, device_map="cuda", torch_dtype=torch.float16, trust_remote_code=True, # fp16=True ).vpm.eval()
> > > > > > torch.onnx.export(model_visual, torch.randn( [1, 3, 364, 546]).to(device).half(), onnx_file_path, opset_version=18, input_names=['input'], output_names=['output'], dynamic_axes={ 'input': { 2: 'height', 3: 'width', }, 'output': { 1: 'output_dim' } } ) 我的torch版本是2.3.0，请问有可用的解决方案吗？
> > > > > 
> > > > > 
> > > > > 我的也是这个算子不支持。不过我的是onnx opset version 18 is not supported
> > > > 
> > > > 
> > > > 参考这个 https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html#unsupported-operators 这个算子是还没支持的 不知道能不能找到这个运算符换种写法
> > > 
> > > 
> > > 你好，这个转换onnx的过程解决了么
> > 
> > 
> > 还没有
> 
> 已经转出来了，我这边的解决方式是在torch.nn.functional.py中找到这个算子的转换函数，利用upsample函数替换

感谢回复
我把torch.nn.functional.py中抗锯齿这个注释掉了，转出来了
`    if input.dim() == 4 and mode == "bicubic":
        assert align_corners is not None
        # if antialias:
        #     return torch._C._nn._upsample_bicubic2d_aa(input, output_size, align_corners, scale_factors)
        return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)`

大佬你是只转了视觉层吗，有没有试过转tensorrt

**Comment by wenxingxingxing** [comment]
> > > > > > > > > 转换vpm到onnx的过程中，出现算子不支持的情况，请问有方式解决吗 torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bicubic2d_aa' to ONNX opset version 17 is not supported.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 请问你是怎么转换onnx？
> > > > > > > 
> > > > > > > 
> > > > > > > 感谢回复，我转换onnx的方式是 model_visual = AutoModelForCausalLM.from_pretrained( pretrained_model_path, device_map="cuda", torch_dtype=torch.float16, trust_remote_code=True, # fp16=True ).vpm.eval()
> > > > > > > torch.onnx.export(model_visual, torch.randn( [1, 3, 364, 546]).to(device).half(), onnx_file_path, opset_version=18, input_names=['input'], output_names=['output'], dynamic_axes={ 'input': { 2: 'height', 3: 'width', }, 'output': { 1: 'output_dim' } } ) 我的torch版本是2.3.0，请问有可用的解决方案吗？
> > > > > > 
> > > > > > 
> > > > > > 我的也是这个算子不支持。不过我的是onnx opset version 18 is not supported
> > > > > 
> > > > > 
> > > > > 参考这个 https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html#unsupported-operators 这个算子是还没支持的 不知道能不能找到这个运算符换种写法
> > > > 
> > > > 
> > > > 你好，这个转换onnx的过程解决了么
> > > 
> > > 
> > > 还没有
> > 
> > 
> > 已经转出来了，我这边的解决方式是在torch.nn.functional.py中找到这个算子的转换函数，利用upsample函数替换
> 
> 感谢回复 我把torch.nn.functional.py中抗锯齿这个注释掉了，转出来了 ` if input.dim() == 4 and mode == "bicubic": assert align_corners is not None # if antialias: # return torch._C._nn._upsample_bicubic2d_aa(input, output_size, align_corners, scale_factors) return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)`
> 
> 大佬你是只转了视觉层吗，有没有试过转tensorrt

我是用torch.nn.upsample替换掉转出来的，目前还没有转tensorrt的需求

**Comment by tiger-boy** [comment]
@Popsicle0-0 大佬，你好，请问你转minicpm转tensorrt成功了吗，我LLM(qwen2)转onnx，然后再转tensorrt转成功了，但是结果差别很大，onnx结果是对的，但是tensorrt结果是错的，各种报错都解决掉了，没有提示错误。
这是onnx输出的结果，是正确的：
`logits [[[ 3.7372942  5.974597   7.254508  ... -4.197067  -5.5219636 -4.1806183]
  [ 2.297062   3.427858   4.6179614 ... -3.9310434 -3.7837098 -3.5643003]
  [ 2.60129    7.165606  12.978946  ... -3.683305  -3.8735662 -4.486837 ]
  ...
  [15.757364  23.128721  15.915645  ...  5.2553625  8.817051  10.390112 ]
  [25.599512  24.137163  29.001715  ... 18.404926  16.576166  16.997326 ]
  [13.539958  24.923449  16.892876  ...  8.566763   9.428918  10.582098 ]]]
input_ids tensor([[87140]])
logits [[[ 7.3675704 15.722521  11.139324  ...  3.620854   5.7070045  6.174467 ]]]
input_ids tensor([[87140, 15946]])
logits [[[ 8.263374  15.2043915  8.158638  ...  3.5326996  6.137852   5.7413454]]]
input_ids tensor([[87140, 15946,  3837]])
logits [[[ 7.8696613 18.49066   10.368851  ...  4.547389   5.4900913  7.2045383]]]
input_ids tensor([[ 87140,  15946,   3837, 101961]])
logits [[[2.8191872 9.505165  6.5611563 ... 1.1850363 2.354134  4.671297 ]]]
input_ids tensor([[ 87140,  15946,   3837, 101961,  95256]])
logits [[[6.0040436  7.3352814  4.755529   ... 2.9951687  0.18238968 2.270723  ]]]
input_ids tensor([[ 87140,  15946,   3837, 101961,  95256,  99164]])`
这是tensorr输出的部分结果：
`logits tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])
input_ids tensor([[46266]])

logits tensor([[[2.6008e-42, 0.0000e+00, 2.6022e-42,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])
input_ids tensor([[46266,   728]])

logits tensor([[[2.6008e-42, 0.0000e+00, 2.6022e-42,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])
input_ids tensor([[46266,   728,   666]])

logits tensor([[[2.6008e-42, 0.0000e+00, 2.6022e-42,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])
input_ids tensor([[46266,   728,   666,   630]])

logits tensor([[[2.6008e-42, 0.0000e+00, 2.6022e-42,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])
input_ids tensor([[46266,   728,   666,   630,   688]])

logits tensor([[[2.6008e-42, 0.0000e+00, 2.6022e-42,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])
input_ids tensor([[46266,   728,   666,   630,   688,   604]])`
