### ISSUE TITLE
是否有，仿OpenAI API风格的demo运行文件

### ISSUE THREAD

**Issue by xiaoToby** [OpenBMB/MiniCPM-V#119]
类似这种：https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/openai_api_zh

@iceflame89

**Comment by xiaoToby** [comment]
Implements API for minicpm on OpenAI's format.

**Comment by Cuiunbo** [comment]
Added to future plans, feel free to ask us any further questions!

**Comment by Single430** [comment]
@xiaoToby 我这边尝试基于https://github.com/QwenLM/Qwen-VL/blob/master/openai_api.py 做了一些修改，目前是可以post调用的 [minicpm_openai_api.py](https://github.com/Single430/issuesFile/tree/master?tab=readme-ov-file#%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5)
