### ISSUE TITLE
package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by cvmilesight** [OpenBMB/MiniCPM-V#120]
ERROR: Cannot install -r requirements.txt (line 18) and -r requirements.txt (line 32) because these package versions have conflicting dependencies.

The conflict is caused by:
    spacy 3.7.2 depends on typer<0.10.0 and >=0.3.0
    gradio 4.31.4 depends on typer<1.0 and >=0.12; sys_platform != "emscripten"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by clearsitedesigns** [comment]
I fixed this myself by modify the requirements.txt - to let pip determine dependencies


packaging==23.2
addict==2.4.0
editdistance==0.6.2
einops==0.7.0
fairscale==0.4.0
jsonlines==4.0.0
markdown2==2.4.10
matplotlib==3.7.4
more_itertools==10.1.0
nltk==3.8.1
numpy==1.24.4
opencv_python_headless==4.5.5.64
openpyxl==3.1.2
Pillow==10.1.0
sacrebleu==2.3.2
seaborn==0.13.0
shortuuid==1.0.11
spacy
typer
timm==0.9.10
torch==2.1.2
torchvision==0.16.2
tqdm==4.66.1
protobuf==4.25.0
transformers==4.40.0
typing_extensions==4.8.0
uvicorn==0.24.0.post1
#xformers==0.0.22.post7
#flash_attn==2.3.4
sentencepiece==0.1.99
accelerate==0.30.1
socksio==1.0.0
gradio
gradio_client==0.16.4

**Comment by iceflame89** [comment]
Thanks for you feedback，fixed now.
