### ISSUE TITLE
Model gets language confused - running gradio 2.5 demo.

### ISSUE THREAD

**Issue by clearsitedesigns** [OpenBMB/MiniCPM-V#124]
I've been running a few tests on an M1 pro - with a simple  "whats in the image."

I've noticed the model gets language confused:

продавец I can see a cartoon image of a cat. The cat has a mix of orange and white fur, with green eyes. It appears to be sitting and looking directly at the viewer.

**Comment by Cuiunbo** [comment]
I think this should be very much related to the generation parameters used for inference
I recommend using Beamsearch, and you can always talk to us again if this problem still occurs!
