### ISSUE TITLE
finetune

### ISSUE THREAD

**Issue by hn18001** [OpenBMB/MiniCPM-V#135]
Can 4* 40G A100 finetune the model?

**Comment by qyc-98** [comment]
Hi,

Yes, you can use 4 * 40G A100 to finetune the model. I recommend using DeepSpeed ZeRO-2 or ZeRO-3 to manage the memory more efficiently. Additionally, you can reduce the number of parameters being trained by setting `tune_vision`, `tune_llm`, etc.

If you still encounter OOM (Out of Memory) issues, we will soon release a LoRA version of the finetuning code, which should help with memory constraints.

Thanks!

**Comment by Cuiunbo** [comment]
Temporarily closed, if you have more questions, please continue to ask us!

**Comment by piarosebelledelapaz** [comment]
Hello, I would like to ask what would you recommend for finetuning (LoRA) MiniCPM-o with vision module set to true? 
Is 2*A100 enough?
