### ISSUE TITLE
似乎扫描件效果不佳

### ISSUE THREAD

**Issue by 0sengseng0** [OpenBMB/MiniCPM-V#136]
主要在数字表格类型的扫描件上，数据识别的准确度相比专门的OCR还是有差距的；文字类型的话，虽然有差距，但不是很大。感觉相对OCR的优势是，可以问答。针对扫描件，是否会做优化呢？

**Comment by Cuiunbo** [comment]
感谢反馈， 我们会在下一版模型中加入更多优化实现对扫描件的理解能力～
如有更多问题，欢迎继续讨论
