### ISSUE TITLE
请问这个int4量化是怎么做的了，有相关的参考文件吗。

### ISSUE THREAD

**Issue by Alxemade** [OpenBMB/MiniCPM-V#139]
### 摘要 | Summary

无

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by tc-mb** [comment]
> ### 起始日期 | Start Date
> _No response_
> 
> ### 实现PR | Implementation PR
> _No response_
> 
> ### 相关Issues | Reference Issues
> _No response_
> 
> ### 摘要 | Summary
> 无
> 
> ### 基本示例 | Basic Example
> 无
> 
> ### 缺陷 | Drawbacks
> 无
> 
> ### 未解决问题 | Unresolved questions
> _No response_

I'll give a int4/int8 introduction later this week.

**Comment by tc-mb** [comment]
> 请问下，有发 MiniCPM-Llama3-V-2_5 量化文档了不，比如GPTQ/Awq 4bit量化，没看到有文档 @tc-mb

人力不济，还没时间写。
