### ISSUE TITLE
加上LLM_TYPE后报错ValueError

### ISSUE THREAD

**Issue by Zmeo** [OpenBMB/MiniCPM-V#142]
感谢您的回复
加上参数之后出现了新的报错

>   File "/home/kas/.conda/envs/MiniCPMV/lib/python3.10/site-packages/transformers/hf_argparser.py", line 347, in 
> parse_args_into_dataclasses
>     raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
> ValueError: Some specified arguments are not used by the HfArgumentParser: ['--llm_type', 'llama3']

_Originally posted by @Zmeo in https://github.com/OpenBMB/MiniCPM-V/issues/131#issuecomment-2126727248_

**Comment by YuzaChongyi** [comment]
we have updated the [TrainingArguments](https://github.com/OpenBMB/MiniCPM-V/blob/main/finetune/finetune.py#L49), please fetch the latest finetune code.
