### ISSUE TITLE
int4量化的精度下降了吗，下降多少？

### ISSUE THREAD

**Issue by wodsoe** [OpenBMB/MiniCPM-V#143]
int4量化的精度下降了吗，下降多少？

**Comment by tc-mb** [comment]
> int4量化的精度下降了吗，下降多少？

我们观察到，int4量化目前精度会有一个点以内的轻微损失。

**Comment by Cuiunbo** [comment]
@wodsoe 
目前我们正在集中力量推进llamacpp的集成和进一步提升模型性能。如您有时间，欢迎您成为minicpm-v开源社区开发者之一，欢迎提交fp8版本模型～
