### ISSUE TITLE
小米手机运行 MiniCPM-V 2.0 apk，模型回复异常

### ISSUE THREAD

**Issue by harry0703** [OpenBMB/MiniCPM-V#148]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

小米手机 Redmi Note 13, 8GB内存，运行 MiniCPM-V 2.0 apk，模型回复异常

<img width="323" alt="Snipaste_2024-05-25_21-34-46" src="https://github.com/OpenBMB/MiniCPM-V/assets/4928832/b251a7b8-b810-4137-9e0e-353502d92a67">

### 期望行为 | Expected Behavior

期望如文档里面的GIF图片一样，正常回复

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by iceflame89** [comment]
感谢反馈～ 由于模型量化损失和实现细节差异，导致有一定概率出现重复文字输出，我们将尽快修复～
