### ISSUE TITLE
ipad上支持吗

### ISSUE THREAD

**Issue by wangshengji** [OpenBMB/MiniCPM-V#149]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [ ] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [ ] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Cuiunbo** [comment]
On IOS or ipadOS, the cli way is working correctly with the model using llamacpp, but we don't have the manpower to wrap it into swift, if you want to help support us we would appreciate it.
