### ISSUE TITLE
💡 [REQUEST] - 模型能上传到https://ollama.com/library吗？

### ISSUE THREAD

**Issue by tqangxl** [OpenBMB/MiniCPM-V#157]
### 摘要 | Summary

模型能上传到https://ollama.com/library吗？

### 基本示例 | Basic Example

模型能上传到https://ollama.com/library吗？

### 缺陷 | Drawbacks

https://ollama.com/library上没有该模型，Windows上无法使用，open webui作为交互界面
![image](https://github.com/OpenBMB/MiniCPM-V/assets/9669944/254519ef-554c-44b2-b18b-1425442a8a87)

**Comment by hyphantom** [comment]
> 需要重新编译./ollama文件，参考：https://ollama.com/hhao/openbmb-minicpm-llama3-v-2_5

按教程步骤，编译报错，请求帮助：执行到go generate ./...
内部执行 cmake -S ../llama.cpp -B ../build/windows/amd64_static -G MinGW Makefiles -DCMAKE_C_COMPILER=gcc.exe -DCMAKE_CXX_COMPILER=g++.exe -DBUILD_SHARED_LIBS=off -DLLAMA_NATIVE=off -DLLAMA_AVX=off -DLLAMA_AVX2=off -DLLAMA_AVX512=off -DLLAMA_F16C=off -DLLAMA_FMA=off
cmake version 3.29.3
然后cmake -S ../llama.cpp -B ../build/windows/amd64/cpu -DCMAKE_POSITION_INDEPENDENT_CODE=on -A x64 -DLLAMA_AVX=off -DLLAMA_AVX2=off -DLLAMA_AVX512=off -DLLAMA_FMA=off -DLLAMA_F16C=off -DBUILD_SHARED_LIBS=on -DLLAMA_NATIVE=off -DLLAMA_SERVER_VERBOSE=off -DCMAKE_BUILD_TYPE=Release
cmake version 3.29.3
报错位置：
-- Build files have been written to: xxxxx/ollama/llm/build/windows/amd64/cpu
building with: cmake --build ../build/windows/amd64/cpu --config Release --target ollama_llama_server
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

MSBUILD : error MSB1009: 项目文件不存在。
开关:ollama_llama_server.vcxproj
llm\generate\generate_windows.go:3: running "powershell": exit status 1

实际我确认了 没有生成ollama_llama_server.vcxproj
现在卡在这一步 无法进行

**Comment by tc-mb** [comment]
> ### 起始日期 | Start Date
> _No response_
> 
> ### 实现PR | Implementation PR
> _No response_
> 
> ### 相关Issues | Reference Issues
> _No response_
> 
> ### 摘要 | Summary
> 模型能上传到[https://ollama.com/library吗？](https://ollama.com/library%E5%90%97%EF%BC%9F)
> 
> ### 基本示例 | Basic Example
> 模型能上传到[https://ollama.com/library吗？](https://ollama.com/library%E5%90%97%EF%BC%9F)
> 
> ### 缺陷 | Drawbacks
> [https://ollama.com/library上没有该模型，Windows上无法使用，open](https://ollama.com/library%E4%B8%8A%E6%B2%A1%E6%9C%89%E8%AF%A5%E6%A8%A1%E5%9E%8B%EF%BC%8CWindows%E4%B8%8A%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%EF%BC%8Copen) webui作为交互界面 ![image](https://private-user-images.githubusercontent.com/9669944/334199179-254519ef-554c-44b2-b18b-1425442a8a87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjQ0MjksIm5iZiI6MTcxNzEyNDEyOSwicGF0aCI6Ii85NjY5OTQ0LzMzNDE5OTE3OS0yNTQ1MTllZi01NTRjLTQ0YjItYjE4Yi0xNDI1NDQyYThhODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDI1NTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzljYTVmMjZhOGVjOTYyZDBmZTRjN2Y2Y2RjN2EzNDcxOWUyMjdjYzlhYWZmYTQ5ZDBjZDgxNzRlMjI1MDgyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CllTYXe7AS0AUVY5kTwvJRBzaEmqJoCL8zpwgIV_isE)
> 
> ### 未解决问题 | Unresolved questions
> _No response_

因为ollama依赖llama.cpp，官方ollama使用时候会强制更新llama.cpp，但我们的分支还没合并到llama.cpp中，这导致只使用官方ollama，而不是用我们修改的代码重新编译的话，现阶段是不可能跑对我们的模型的。
所以我们不认为简单的传一个model到ollama的lib中是有意义的。反而会让大家误会既然传了模型就应该能用官方代码跑。

**Comment by tc-mb** [comment]
> > 需要重新编译./ollama文件，参考：https://ollama.com/hhao/openbmb-minicpm-llama3-v-2_5
> 
> 按教程步骤，编译报错，请求帮助：执行到go generate ./... 内部执行 cmake -S ../llama.cpp -B ../build/windows/amd64_static -G MinGW Makefiles -DCMAKE_C_COMPILER=gcc.exe -DCMAKE_CXX_COMPILER=g++.exe -DBUILD_SHARED_LIBS=off -DLLAMA_NATIVE=off -DLLAMA_AVX=off -DLLAMA_AVX2=off -DLLAMA_AVX512=off -DLLAMA_F16C=off -DLLAMA_FMA=off cmake version 3.29.3 然后cmake -S ../llama.cpp -B ../build/windows/amd64/cpu -DCMAKE_POSITION_INDEPENDENT_CODE=on -A x64 -DLLAMA_AVX=off -DLLAMA_AVX2=off -DLLAMA_AVX512=off -DLLAMA_FMA=off -DLLAMA_F16C=off -DBUILD_SHARED_LIBS=on -DLLAMA_NATIVE=off -DLLAMA_SERVER_VERBOSE=off -DCMAKE_BUILD_TYPE=Release cmake version 3.29.3 报错位置： -- Build files have been written to: xxxxx/ollama/llm/build/windows/amd64/cpu building with: cmake --build ../build/windows/amd64/cpu --config Release --target ollama_llama_server 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642 版权所有(C) Microsoft Corporation。保留所有权利。
> 
> MSBUILD : error MSB1009: 项目文件不存在。 开关:ollama_llama_server.vcxproj llm\generate\generate_windows.go:3: running "powershell": exit status 1
> 
> 实际我确认了 没有生成ollama_llama_server.vcxproj 现在卡在这一步 无法进行

收到反馈，我会尽快测试window环境下是否会有编译问题。

**Comment by knsew** [comment]
ollama下载的模型不支持图片识别，有为什么解决办法吗？

**Comment by Cuiunbo** [comment]
> ollama下载的模型不支持图片识别，有为什么解决办法吗？

@tc-mb

**Comment by tc-mb** [comment]
> ollama下载的模型不支持图片识别，有为什么解决办法吗？

在官方没有合并我们你的PR之前，请用我们fork的代码，并按照readme从头build。
https://github.com/OpenBMB/ollama/blob/minicpm-v2.5/examples/minicpm-v2.5/README.md
