### ISSUE TITLE
[BUG] <title> LoRA Finetuning --per_device_train_batch_size argument

### ISSUE THREAD

**Issue by leopeng1995** [OpenBMB/MiniCPM-V#162]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

finetune.py: error: argument --per_device_train_batch_size: invalid int value: 'w'

In finetune_ds.sh，`--per_device_train_batch_size` is set to 2.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by qyc-98** [comment]
We have fixed it, please try our new version "finetue_lora.sh"
