### ISSUE TITLE
Request a technical report

### ISSUE THREAD

**Issue by berry-ding** [OpenBMB/MiniCPM-V#164]
Great work!!!!!!!!!!!!!!!!!!!!!!!!!!! I have used MiniCPM-V-LLaMA3-8b in some downstream tasks, and it shows a remarkable ability compared to others, such as LLaVA-Next. I would like to know if you have any plans to release your technical report detailing the technical aspects.

**Comment by waxnkw** [comment]
Thanks for your interest! We will release the technical report soon.

**Comment by khyati2396** [comment]
Is the technical report out already?
If yes, then will be kind enough to provide the link.
else, can anyone fill us in on when will it be released?

**Comment by Lynncc6** [comment]
> Is the technical report out already? If yes, then will be kind enough to provide the link. else, can anyone fill us in on when will it be released?

MiniCPM-Llama3-V 2.5 technical report is released! 
Check this：https://github.com/OpenBMB/MiniCPM-V/blob/main/docs/MiniCPM_Llama3_V_25_technical_report.pdf
