### ISSUE TITLE
看了v2.5在小米手机上跑起来的效果,比较震撼💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by qwas982** [OpenBMB/MiniCPM-V#166]
### 摘要 | Summary

或许可以使用`比例律/缩放律Scaling Law`, `混合专家/混合深度MoE/MoD`等算法与技术来提升手机与笔记本台式机CPU上的表现,   
我的手机只有8GB内存,笔记本只有16GB内存,期待一个1B的大模型或100M的大模型在应用了上面两种技术后也能达到v2.5在小米手机上跑起来的那种性能.

### 基本示例 | Basic Example

v2.5在小米手机上跑起来的效果

### 缺陷 | Drawbacks

要克服困难勇于创新

**Comment by Cuiunbo** [comment]
您好, 您给出如此高度的评价将是我们保持开源热情和继续进行前沿探索的动力, 我们将持续推进研究更强更快更小的模型在端侧部署!
