### ISSUE TITLE
流式输出

### ISSUE THREAD

**Issue by omige** [OpenBMB/MiniCPM-V#172]
### 摘要 | Summary

如何用miniCPM-V-2.5-int4产生流式输出？

### 基本示例 | Basic Example

answer = chat_model.chat(inputs)

### 缺陷 | Drawbacks

未知

### 未解决问题 | Unresolved questions

尚未找到产生流式输出的方法。希望在官方文档中给出。

**Comment by YuzaChongyi** [comment]
你好，可以参考 hf 上的[使用方式](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5-int4#usage)

**Comment by chuangzhidan** [comment]
> 你好，可以参考 hf 上的[使用方式](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5-int4#usage)

但是要部署成服务，调用服务拿到结果，这个print就不行了
