### ISSUE TITLE
💡 [REQUEST] - <MiniCPM-Llama3-V 2.5 int4 可以进行lora微调吗>

### ISSUE THREAD

**Issue by menghuazou** [OpenBMB/MiniCPM-V#173]
### 摘要 | Summary

如果可以，显存要求多大

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

未知

**Comment by qyc-98** [comment]
您好 目前还没有进行这个尝试 我们会尽快进行这个功能的调试并上线代码
