### ISSUE TITLE
Hello, I encountered an error during deployment.

### ISSUE THREAD

**Issue by yz-Python** [OpenBMB/MiniCPM-V#176]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

The following is the bug information.
AttributeError: 'MiniCPMVConfig' object has no attribute 'dim_model_base'
Package                   Version      Editable project location
------------------------- ------------ -----------------------------------------
accelerate                0.30.1
addict                    2.4.0
aiofiles                  23.2.1
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
attrs                     23.2.0
blis                      0.7.11
catalogue                 2.0.10
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
cloudpathlib              0.16.0
cloudpickle               3.0.0
cmake                     3.29.3
colorama                  0.4.6
confection                0.1.4
contourpy                 1.2.1
cycler                    0.12.1
cymem                     2.0.8
diskcache                 5.6.3
editdistance              0.6.2
einops                    0.7.0
et-xmlfile                1.1.0
exceptiongroup            1.2.1
fairscale                 0.4.0
fastapi                   0.110.3
ffmpy                     0.3.2
filelock                  3.13.1
fonttools                 4.52.4
frozenlist                1.4.1
fsspec                    2024.2.0
gradio                    4.26.0
gradio_client             0.15.1
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.2
idna                      3.7
importlib_resources       6.4.0
interegular               0.3.3
Jinja2                    3.1.3
joblib                    1.4.2
jsonlines                 4.0.0
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
langcodes                 3.4.0
language_data             1.2.0
lark                      1.1.9
llvmlite                  0.42.0
lm-format-enforcer        0.9.8
lxml                      5.2.2
marisa-trie               1.1.1
markdown-it-py            3.0.0
markdown2                 2.4.10
MarkupSafe                2.1.5
matplotlib                3.7.4
mdurl                     0.1.2
more-itertools            10.1.0
mpmath                    1.3.0
msgpack                   1.0.8
murmurhash                1.0.10
nest-asyncio              1.6.0
networkx                  3.2.1
ninja                     1.11.1.1
nltk                      3.8.1
numba                     0.59.1
numpy                     1.24.4
nvidia-cublas-cu11        11.11.3.6
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu11    11.8.87
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu11    11.8.89
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu11  11.8.89
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu11         8.7.0.84
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu11         10.9.0.58
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu11        10.3.0.86
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu11      11.4.1.48
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu11      11.7.5.86
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu11          2.19.3
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.5.40
nvidia-nvtx-cu11          11.8.86
nvidia-nvtx-cu12          12.1.105
opencv-python-headless    4.5.5.64
openpyxl                  3.1.2
orjson                    3.10.3
outlines                  0.0.34
packaging                 23.2
pandas                    2.2.2
Pillow                    10.1.0
pip                       24.0
portalocker               2.8.2
preshed                   3.0.9
prometheus_client         0.20.0
protobuf                  4.25.0
psutil                    5.9.8
py-cpuinfo                9.0.0
pydantic                  2.7.2
pydantic_core             2.18.3
pydub                     0.25.1
Pygments                  2.18.0
pynvml                    11.5.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
ray                       2.23.0
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.2
rich                      13.7.1
rpds-py                   0.18.1
ruff                      0.4.6
sacrebleu                 2.3.2
safetensors               0.4.3
scipy                     1.13.1
seaborn                   0.13.0
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                69.5.1
shellingham               1.5.4
shortuuid                 1.0.11
six                       1.16.0
smart-open                6.4.0
sniffio                   1.3.1
socksio                   1.0.0
spacy                     3.7.2
spacy-legacy              3.0.12
spacy-loggers             1.0.5
srsly                     2.4.8
starlette                 0.37.2
sympy                     1.12
tabulate                  0.9.0
thinc                     8.2.3
tiktoken                  0.6.0
timm                      0.9.10
tokenizers                0.19.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.2.1+cu118
torchaudio                2.2.1+cu118
torchvision               0.17.1+cu118
tqdm                      4.66.1
transformers              4.41.1
triton                    2.2.0
typer                     0.9.4
typing_extensions         4.8.0
tzdata                    2024.1
urllib3                   2.2.1
uvicorn                   0.24.0.post1
uvloop                    0.19.0
vllm                      0.4.1        /root/autodl-tmp/code/MiniCPM-V/vllm/vllm
vllm_nccl_cu12            2.18.1.0.4.0
wasabi                    1.1.2
watchfiles                0.22.0
weasel                    0.3.4
websockets                11.0.3
wheel                     0.43.0
xformers                  0.0.25

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by iceflame89** [comment]
Please make sure the model files not changed from our original model repo.
If that doesn‘t work，please provide the model name and code so that we can  reproduce the error.

**Comment by li904775857** [comment]
怎么处理的呢

**Comment by yz-Python** [comment]
换了个模型  internVL1.5

**Comment by li904775857** [comment]
好的，看了下文档，vllm暂时还不支持2.5
