### ISSUE TITLE
[Request] - Support for mobile NPU deployment

### ISSUE THREAD

**Issue by LongIslandWithoutIceTea** [OpenBMB/MiniCPM-V#180]
Hi guys,

Just wondering if you guys have plans to support quantization and deployment on mobile NPUs like those on the Qualcomm Snapdragon in the future?

Thanks for your time!

**Comment by iceflame89** [comment]
Speeding up with NPU has been in our plan from the beginning. It's almost done,  please stay tuned.

**Comment by AnyangAngus** [comment]
> Speeding up with NPU has been in our plan from the beginning. It's almost done, please stay tuned.

@iceflame89 Hi , is there any update on Android NPU inference?
