### ISSUE TITLE
一样的图片，一样的提示词，每次的结果不一样。能让每次的结果一样吗？通过哪些参数控制。

### ISSUE THREAD

**Issue by cuppersd** [OpenBMB/MiniCPM-V#183]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by YuzaChongyi** [comment]
你好，你可以调用 chat 函数时传入 `sampling=False`, 这会使用默认 `num_beams=3 `的 beam search 解码, 或者你可以每次调用前通过`torch.cuda.manual_seed_all` 方法设定随机数种子, 也可以复现结果
