### ISSUE TITLE
finetune_lora.sh use ds_config_zero3.json error

### ISSUE THREAD

**Issue by zhangchaosunshine** [OpenBMB/MiniCPM-V#184]
I want to use ds_config_zero3.json to reduce GPU memory.I only have 4*24G GPU memory.But error occurred.
`  File "/home/cce/work/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/resampler.py", line 152, in forward
    x + pos_embed,  # L * B * D +  L * B * D
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!`
can you provide  finetune_lora.sh about zero3.

**Comment by shituo123456** [comment]
so do i

**Comment by qyc-98** [comment]
hi we have updated our code ， you can try it again

**Comment by zhangchaosunshine** [comment]
> hi we have updated our code ， you can try it again

Thanks a lot. good work.
