### ISSUE TITLE
lora 和 qlora

### ISSUE THREAD

**Issue by shituo123456** [OpenBMB/MiniCPM-V#186]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

双卡4090 lora ZerO2 OOM，ZerO3 tensor不在一个device。
改成Qlora，报错：
 File "/home/st/mllm/MiniCPM-V/finetune/finetune.py", line 276, in train
    model.base_model.vpm.requires_grad_(True)
  File "/root/anaconda3/envs/minicpmv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2440, in requires_grad_
    p.requires_grad_(requires_grad)
RuntimeError: only Tensors of floating point dtype can require gradients

### 期望行为 | Expected Behavior

麻烦可以修改下ZerO3. 支持一下Qlora吗。谢谢

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by qyc-98** [comment]
您好 我们目前修改好了zero3的代码，您可以尝试我们的新代码，后续我们将更新qlora的代码，谢谢您的关注

**Comment by shituo123456** [comment]
> 您好 我们目前修改好了zero3的代码，您可以尝试我们的新代码，后续我们将更新qlora的代码，谢谢您的关注

您好，我是在双卡4090进行微调，zero2一直oom，使用zero3时报如下错误。
在使用zero3时报了如下错误：
![image](https://github.com/OpenBMB/MiniCPM-V/assets/64970397/d9bc4d6b-2cdd-49e6-9aa6-32388f5be331)
在finetune.py屏蔽掉device_map后，又报如下错误：
![image](https://github.com/OpenBMB/MiniCPM-V/assets/64970397/57ea2e35-bd7c-4145-87a1-7f76e86d1551)
在finetune_lora.sh中将--bf16和--bf16_full_eval设置为false后，再进行训练，就会OOM。

**Comment by shituo123456** [comment]
期待您的回复，不胜感激

**Comment by shituo123456** [comment]
运行环境：
torch                     2.1.2
transformers              4.40.0
torch.version.cuda    12.1

**Comment by YuzaChongyi** [comment]
如果 `--bf16` 设置为 `false` 的话，需要把 `--fp16` 设置为 `true`

**Comment by YuzaChongyi** [comment]
`erfinv_cuda` 的问题在我们测试的时候还没遇到过，这里有一个相关的 issue https://github.com/pytorch/pytorch/issues/123553, 看起来是在初始化 resampler 的时候的问题，你可以把初始化 `weights` 相关的代码都注释了，不影响微调

**Comment by qyc-98** [comment]
please set --bf16 false
--bf16_full_eval false
--fp16 true
--fp16_full_eval true \ this is because zero3 is not compatiable with bf16.please use fp16

**Comment by shituo123456** [comment]
> please set --bf16 false --bf16_full_eval false --fp16 true --fp16_full_eval true \ this is because zero3 is not compatiable with bf16.please use fp16

Thank you very much for your reply. 
After training 15 iter units normally according to your tips, OOM will be reported again. I use 4090 dual GPU, is this normal? How to reduce the video memory occupation to enable normal training? Looking forward to your reply very much.

![image](https://github.com/OpenBMB/MiniCPM-V/assets/64970397/44d0abb8-a480-4ffc-b275-9b48f23e697d)

**Comment by shituo123456** [comment]
复现参数
```
torchrun $DISTRIBUTED_ARGS finetune.py  \
    --model_name_or_path $MODEL \
    --llm_type $LLM_TYPE \
    --data_path $DATA \
    --eval_data_path $EVAL_DATA \
    --remove_unused_columns false \
    --label_names "labels" \
    --prediction_loss_only false \
    --bf16 false \
    --bf16_full_eval false \
    --fp16 true \
    --fp16_full_eval true \
    --do_train \
    --do_eval \
    --tune_vision true \
    --tune_llm false \
    --use_lora true \
    --lora_target_modules "llm\..*layers\.\d+\.self_attn\.(q_proj|k_proj)" \
    --model_max_length 2048 \
    --max_slice_nums 9 \
    --scale_resolution 448 \
    --max_steps 10000 \
    --eval_steps 1000 \
    --output_dir output/output_minicpmv2_lora \
    --logging_dir output/output_minicpmv2_lora \
    --logging_strategy "steps" \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "steps" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-6 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --gradient_checkpointing true \
    --deepspeed ds_config_zero3.json \
    --report_to "tensorboard" # wandb
```

**Comment by winsonxxxx** [comment]
> > please set --bf16 false --bf16_full_eval false --fp16 true --fp16_full_eval true \ this is because zero3 is not compatiable with bf16.please use fp16
> 
> Thank you for your prompt response. Despite following your suggestions and training with 15 iterations, I am still encountering out-of-memory (OOM) issues. I am using a 4090 dual GPU, is this expected? How can I minimize the video memory usage of the graphics card to ensure smooth training? Looking forward to your valuable feedback
> 
> ![image](https://private-user-images.githubusercontent.com/64970397/336649857-44d0abb8-a480-4ffc-b275-9b48f23e697d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjU3NzcsIm5iZiI6MTcxNzU2NTQ3NywicGF0aCI6Ii82NDk3MDM5Ny8zMzY2NDk4NTctNDRkMGFiYjgtYTQ4MC00ZmZjLWIyNzUtOWI0OGYyM2U2OTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1NTQ1NjhhNGIxNDE2OTU2NzY4M2YzM2ZkMTBhZGUxZTEyMWQzOWUwMTY4Y2JkNmVkZTNmMGEyM2ZhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3rHL6p8eI-gGHhNmMbrpPK4j8oVBMqj6GP_zUuuaFT8) ![image](https://private-user-images.githubusercontent.com/64970397/336650337-8c45a40e-f34b-49b4-a5fb-5bc4dc892159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjU3NzcsIm5iZiI6MTcxNzU2NTQ3NywicGF0aCI6Ii82NDk3MDM5Ny8zMzY2NTAzMzctOGM0NWE0MGUtZjM0Yi00OWI0LWE1ZmItNWJjNGRjODkyMTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZmIwYWFjNTNhOTU3ODA3NzdhM2ZmODk5OWMwOTAzNDFiYTU1ZjgzZjU4YzkzMTU5ZTYzYTcyMGE5ZTE4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dSzmmJfsQY4OwJU0n0EzOFF9qJ_drLHpKbcHsu5mPvg)

你好，我也遇到同样问题，跑了几个batch就报OOM，请问这个问题解决了吗

**Comment by shituo123456** [comment]
> > > please set --bf16 false --bf16_full_eval false --fp16 true --fp16_full_eval true \ this is because zero3 is not compatiable with bf16.please use fp16
> > 
> > 
> > Thank you for your prompt response. Despite following your suggestions and training with 15 iterations, I am still encountering out-of-memory (OOM) issues. I am using a 4090 dual GPU, is this expected? How can I minimize the video memory usage of the graphics card to ensure smooth training? Looking forward to your valuable feedback
> > ![image](https://private-user-images.githubusercontent.com/64970397/336649857-44d0abb8-a480-4ffc-b275-9b48f23e697d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjU3NzcsIm5iZiI6MTcxNzU2NTQ3NywicGF0aCI6Ii82NDk3MDM5Ny8zMzY2NDk4NTctNDRkMGFiYjgtYTQ4MC00ZmZjLWIyNzUtOWI0OGYyM2U2OTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1NTQ1NjhhNGIxNDE2OTU2NzY4M2YzM2ZkMTBhZGUxZTEyMWQzOWUwMTY4Y2JkNmVkZTNmMGEyM2ZhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3rHL6p8eI-gGHhNmMbrpPK4j8oVBMqj6GP_zUuuaFT8) ![image](https://private-user-images.githubusercontent.com/64970397/336650337-8c45a40e-f34b-49b4-a5fb-5bc4dc892159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjU3NzcsIm5iZiI6MTcxNzU2NTQ3NywicGF0aCI6Ii82NDk3MDM5Ny8zMzY2NTAzMzctOGM0NWE0MGUtZjM0Yi00OWI0LWE1ZmItNWJjNGRjODkyMTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZmIwYWFjNTNhOTU3ODA3NzdhM2ZmODk5OWMwOTAzNDFiYTU1ZjgzZjU4YzkzMTU5ZTYzYTcyMGE5ZTE4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dSzmmJfsQY4OwJU0n0EzOFF9qJ_drLHpKbcHsu5mPvg)
> 
> 你好，我也遇到同样问题，跑了几个batch就报OOM，请问这个问题解决了吗

``` --tune_vision ``` 设置为false 就可以，也就是只微调resample模块。 
不过我也想微调视觉模块，``` --tune_vision ``` 设置为true时，暂时不知道该调哪里好，``` --model_max_length```调小了也不管用。

**Comment by winsonxxxx** [comment]
> > > > please set --bf16 false --bf16_full_eval false --fp16 true --fp16_full_eval true \ this is because zero3 is not compatiable with bf16.please use fp16
> > > 
> > > 
> > > Thank you for your prompt response. Despite following your suggestions and training with 15 iterations, I am still encountering out-of-memory (OOM) issues. I am using a 4090 dual GPU, is this expected? How can I minimize the video memory usage of the graphics card to ensure smooth training? Looking forward to your valuable feedback
> > > ![image](https://private-user-images.githubusercontent.com/64970397/336649857-44d0abb8-a480-4ffc-b275-9b48f23e697d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjU3NzcsIm5iZiI6MTcxNzU2NTQ3NywicGF0aCI6Ii82NDk3MDM5Ny8zMzY2NDk4NTctNDRkMGFiYjgtYTQ4MC00ZmZjLWIyNzUtOWI0OGYyM2U2OTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1NTQ1NjhhNGIxNDE2OTU2NzY4M2YzM2ZkMTBhZGUxZTEyMWQzOWUwMTY4Y2JkNmVkZTNmMGEyM2ZhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3rHL6p8eI-gGHhNmMbrpPK4j8oVBMqj6GP_zUuuaFT8) ![image](https://private-user-images.githubusercontent.com/64970397/336650337-8c45a40e-f34b-49b4-a5fb-5bc4dc892159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjU3NzcsIm5iZiI6MTcxNzU2NTQ3NywicGF0aCI6Ii82NDk3MDM5Ny8zMzY2NTAzMzctOGM0NWE0MGUtZjM0Yi00OWI0LWE1ZmItNWJjNGRjODkyMTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZmIwYWFjNTNhOTU3ODA3NzdhM2ZmODk5OWMwOTAzNDFiYTU1ZjgzZjU4YzkzMTU5ZTYzYTcyMGE5ZTE4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dSzmmJfsQY4OwJU0n0EzOFF9qJ_drLHpKbcHsu5mPvg)
> > 
> > 
> > 你好，我也遇到同样问题，跑了几个batch就报OOM，请问这个问题解决了吗
> 
> `--tune_vision` 设置为false 就可以，也就是只微调resample模块。 不过我也想微调视觉模块，`--tune_vision` 设置为true时，暂时不知道该调哪里好，` --model_max_length`调小了也不管用。

--tune_vision 我设置了false的，也是报OOM，我是单机3卡V100（每卡16G），是显卡不够吗

**Comment by shituo123456** [comment]
> > > > > please set --bf16 false --bf16_full_eval false --fp16 true --fp16_full_eval true \ this is because zero3 is not compatiable with bf16.please use fp16请设置--bf16 false --bf16_full_eval false --fp16 true --fp16_full_eval true \这是因为zero3与bf16不兼容。请使用fp16
> > > > 
> > > > 
> > > > Thank you for your prompt response. Despite following your suggestions and training with 15 iterations, I am still encountering out-of-memory (OOM) issues. I am using a 4090 dual GPU, is this expected? How can I minimize the video memory usage of the graphics card to ensure smooth training? Looking forward to your valuable feedback感谢您的及时回复。尽管遵循您的建议并进行了 15 次迭代训练，我仍然遇到内存不足 (OOM) 问题。我使用的是 4090 双 GPU，这是预期的吗？如何才能最大限度地减少显卡显存占用，保证训练顺利？期待您的宝贵反馈
> > > > <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/64970397/336649857-44d0abb8-a480-4ffc-b275-9b48f23e697d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjU3NzcsIm5iZiI6MTcxNzU2NTQ3NywicGF0aCI6Ii82NDk3MDM5Ny8zMzY2NDk4NTctNDRkMGFiYjgtYTQ4MC00ZmZjLWIyNzUtOWI0OGYyM2U2OTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1NTQ1NjhhNGIxNDE2OTU2NzY4M2YzM2ZkMTBhZGUxZTEyMWQzOWUwMTY4Y2JkNmVkZTNmMGEyM2ZhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3rHL6p8eI-gGHhNmMbrpPK4j8oVBMqj6GP_zUuuaFT8"> <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/64970397/336650337-8c45a40e-f34b-49b4-a5fb-5bc4dc892159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjU3NzcsIm5iZiI6MTcxNzU2NTQ3NywicGF0aCI6Ii82NDk3MDM5Ny8zMzY2NTAzMzctOGM0NWE0MGUtZjM0Yi00OWI0LWE1ZmItNWJjNGRjODkyMTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZmIwYWFjNTNhOTU3ODA3NzdhM2ZmODk5OWMwOTAzNDFiYTU1ZjgzZjU4YzkzMTU5ZTYzYTcyMGE5ZTE4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dSzmmJfsQY4OwJU0n0EzOFF9qJ_drLHpKbcHsu5mPvg">
> > > 
> > > 
> > > 你好，我也遇到同样问题，跑了几个batch就报OOM，请问这个问题解决了吗
> > 
> > 
> > `--tune_vision` 设置为false 就可以，也就是只微调resample模块。 不过我也想微调视觉模块，`--tune_vision` 设置为true时，暂时不知道该调哪里好，` --model_max_length`调小了也不管用。
> 
> --tune_vision 我设置了false的，也是报OOM，我是单机3卡V100（每卡16G），是显卡不够吗

16G是有些紧张，我是双卡4090， 24G。看finetune/readme.md，zero3显存需要不到15G，这个15G应该就是--tune_vision 为false吧，--tune_vision 为True时，我24G是会OOM的
