### ISSUE TITLE
[Q] 数苹果问题

### ISSUE THREAD

**Issue by zhudongwork** [OpenBMB/MiniCPM-V#190]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

minicpm2.5用到了llava-UHD的技术，但是测试发现依然回答不了数苹果问题。

![image](https://github.com/OpenBMB/MiniCPM-V/assets/32665466/b3f2206d-16cd-44b8-b9de-5043906d53fe)

### 复现方法 | Steps To Reproduce

![微信图片_20240531161611](https://github.com/OpenBMB/MiniCPM-V/assets/32665466/4574e42b-372d-4e12-a032-bdad79d9e175)

### 运行环境 | Environment

```Markdown
官方在线demo
```

**Comment by Cuiunbo** [comment]
Hello, the question you raise is fascinating. Here's the thing, for llavauhd, he solved two problems, 
1. Input HD original-size images, 
2. No overlapping parts of the input images, 

But our model still has some base hallucination, like the objhall benchmark scores as seen in the table.
we'll keep on looking for a solution, so stay tuned!

**Comment by zhudongwork** [comment]
Thanks, looking forward your masterpiece～



---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2024年6月1日(周六) 晚上6:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OpenBMB/MiniCPM-V] [Q] 数苹果问题 (Issue #190)




 
Hello, the question you raise is fascinating. Here's the thing, for llavauhd, he solved two problems,
  
Input HD original-size images,
 
No overlapping parts of the input images,
  
But our model still has some base hallucination, like the objhall benchmark scores as seen in the table.
 we'll keep on looking for a solution, so stay tuned!
