### ISSUE TITLE
Structured output and multiple choice

### ISSUE THREAD

**Issue by ffletcherr** [OpenBMB/MiniCPM-V#191]
Hi, thanks for this great vlm.

Can it be used by structure forcing tools like outlines or guidance for tasks like multiple choice or json generation?

**Comment by Cuiunbo** [comment]
For multichoice, use [this](https://github.com/OpenBMB/MiniCPM-V/blob/bbdf5686985f20153b5dd8cdeb2015d984b79d1f/eval_mm/vlmevalkit/vlmeval/vlm/minicpm_llama3_v_2_5.py#L57)
For  json, Just give a reply example in the format you want at the end of the prompt.
