### ISSUE TITLE
Finetuning Question

### ISSUE THREAD

**Issue by babla9** [OpenBMB/MiniCPM-V#193]
Thanks for your work and the support for peft tuning! 

I have the following questions about finetuning: 

1. Does fine-tuning support text-only based samples? (ie conversations without any images)
2. The finetuning docs say it will work on 2xV100s, curious if that's been tested with DeepSpeed and other deps installed?
3. Lastly, I wanted to ask if SWIFT-finetuned models can be deployed using MiniCPM provided VLLM code? 

Thanks!

**Comment by qyc-98** [comment]
1.yes, we support it 
2.yes,you can directly run our fine-tuning script with support of deepspeed. And with zero3, the minnum memory is about 18GiB
