### ISSUE TITLE
[BUG] <title>是否支持多图？Does MiniCPM support multi-pics？

### ISSUE THREAD

**Issue by Liuziyu77** [OpenBMB/MiniCPM-V#199]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by YuzaChongyi** [comment]
你好，可以参考这个[discussions](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5/discussions/2#664c8889afe6e8c3a91aea25)
