### ISSUE TITLE
按照提供的finetune代码，微调loss为0

### ISSUE THREAD

**Issue by HelloWorld19930113** [OpenBMB/MiniCPM-V#204]
### 摘要 | Summary

按照大佬提供的finetune_ds.sh 训练发现loss为0，不知道哪里有问题

### 基本示例 | Basic Example

按照大佬提供的finetune_ds.sh 训练发现loss为0，不知道哪里有问题

### 缺陷 | Drawbacks

按照大佬提供的finetune_ds.sh 训练发现loss为0，不知道哪里有问题

**Comment by HelloWorld19930113** [comment]
[
    {
      "id": "0",
      "image": 'path/to/image_0.jpg',
      "conversations": [
            {
              'role': 'user', 
              'content': '<image>\n请识别证件照图片中的内容'
            }, 
            {
                'role': 'assistant', 
                'content': '1.公司名称：xxxx\n2.公司代码：xxxx\n3.公司地址：xxxx'
            }
        ]
    }
  ]

**Comment by strawhatboy** [comment]
看看是不是MODEL和LLM_TYPE 没有对应？V-2_5 对应 llama3，V-2 对应 minicpm

**Comment by HelloWorld19930113** [comment]
> 看看是不是MODEL和LLM_TYPE 没有对应？V-2_5 对应 llama3，V-2 对应 minicpm

这个检查了没问题

**Comment by HelloWorld19930113** [comment]
> 看看是不是MODEL和LLM_TYPE 没有对应？V-2_5 对应 llama3，V-2 对应 minicpm

已解决，感谢大佬

**Comment by Kennycao123** [comment]
> > 看看是不是MODEL和LLM_TYPE 没有对应？V-2_5 对应 llama3，V-2 对应 minicpm
> 
> 已解决，感谢大佬

遇到了同样的问题，你是如何解决的
