### ISSUE TITLE
m1 MacBook Pro 跑不起来 WebDemo

### ISSUE THREAD

**Issue by ChenzhengUESTC** [OpenBMB/MiniCPM-V#205]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

按照readme运行demo

### 期望行为 | Expected Behavior

正常运行

### 复现方法 | Steps To Reproduce

PYTORCH_ENABLE_MPS_FALLBACK=1 python web_demo.py --device mps

### 运行环境 | Environment

```Markdown
- OS: osx
- Python: 3.11
- Transformers: 4.40.0
- PyTorch: 2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): None
```

### 备注 | Anything else?

![iTerm2 六月 03 2024 21:29:40](https://github.com/OpenBMB/MiniCPM-V/assets/4604830/fcf23ee0-1502-433a-b204-4ffc880cb131)

**Comment by iceflame89** [comment]
For MiniCPM-V 2.0:  [readme](https://github.com/OpenBMB/MiniCPM-V/blob/main/web_demo.py#L19C1)
```
PYTORCH_ENABLE_MPS_FALLBACK=1 python web_demo.py --device mps --dtype fp16
```

For MiniCPM-Llama3-V 2.5: [readme](https://github.com/OpenBMB/MiniCPM-V/blob/main/web_demo_2.5.py#L17)
```
PYTORCH_ENABLE_MPS_FALLBACK=1 python web_demo_2.5.py --device mps
```
