### ISSUE TITLE
关于报错UserWarning: Could not find a config file in MiniCPM-V-2 - will assume that the vocabulary was not modified.

### ISSUE THREAD

**Issue by daihuidai** [OpenBMB/MiniCPM-V#208]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [x] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

你好，我在微调过程中前几次当验证完进行eval时出现了UserWarning: Could not find a config file in MiniCPM-V-2 - will assume that the vocabulary was not modified.这个报错，我查看了huggingface的issue中该问题的回答，回答说可以忽略，并且模型正常保存和验证，实际上我这边也是正常保存。但是我在验证时，模型的回答和我设置的标签相差较大，请问这个警告是否可以忽略。
![QQ20240604-101616](https://github.com/OpenBMB/MiniCPM-V/assets/43409147/56c02998-4dbe-4bf0-849b-92b23ac9af20)

下面是我的推理代码请问是否正确呢：
![QQ20240604-102244](https://github.com/OpenBMB/MiniCPM-V/assets/43409147/7f730a39-514d-434e-8dfa-962ac10423bc)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
这个标签一般是可以忽略的

**Comment by LDLINGLINGLING** [comment]
> 这个标签一般是可以忽略的
回答和标签的差别大，这是因为你好像没有正确的加载模型
