### ISSUE TITLE
关于许可证

### ISSUE THREAD

**Issue by Pickpate** [OpenBMB/MiniCPM-V#210]
Hi，我想知道具体该如何申请商用许可证，目前我们向cpm@modelbest.cn这个邮箱发送了申请，但是没有得到回复，不知道是不是我们申请的流程不符合贵公司的要求。

**Comment by Cuiunbo** [comment]
![Uploading image.png…]()
👋，即日起商用许可申请可通过该二维码～
@Pickpate

**Comment by Pickpate** [comment]
> https://mp.weixin.qq.com/s/NvM3eTvVBX4A8IUWsh3Y9w 👋，即日起商用许可申请可通过该链接下二维码～ @Pickpate

您好，这个我们申请了下，但是发现贵方给的许可证把被许可人填写成了“填表的个人”而不是我们公司，麻烦贵方关注下这个问题吧。
另外为了方便沟通，请问贵方有比较官方的群或者其他联系方式么？很希望得到贵方的许可。

**Comment by Pickpate** [comment]
您好，我想加一个问题。关于这个条款，我有如下疑问，还请帮忙解答下吧：
If you distribute or provide MiniCPM series model materials (or any derivative works thereof), or use any product or service of them, you must (A) provide a copy of this agreement; and (B) prominently display "Built with 面壁MiniCPM" on the relevant website, user interface, blog post, about page, or product documentation. If you create, train, fine-tune, or improve an AI model using the MiniCPM series models, the model must include "MiniCPM" in its name.
请问下，当把模型部署起来对外提供服务时需要遵守全部的这3个要求么？我理解，除非对外提供API服务，一般基于模型的应用（比如一个bot）层的服务都不会对模型进行命名并对外披露该命名。另外提供协议的copy一般是在在对外分发（发送材料给别人时）模型材料，所以在基于模型对外提供服务时，也需要提供协议副本么？
