### ISSUE TITLE
建一个群，方便用户们讨论和反馈

### ISSUE THREAD

**Issue by chmod777john** [OpenBMB/MiniCPM-V#217]
### 摘要 | Summary

可以考虑建立一个用户社群，这样打击方便提问和给出建议
![image](https://github.com/OpenBMB/MiniCPM-V/assets/146207719/d9063ecd-27a7-4244-86d7-b8acce10fb8e)

### 基本示例 | Basic Example

.

### 缺陷 | Drawbacks

.

**Comment by yiranyyu** [comment]
你好，欢迎加入我们的微信讨论群！

![image](https://github.com/OpenBMB/MiniCPM-V/assets/28106858/141598d1-74f1-4962-a49e-69dac057987e)

**Comment by Cuiunbo** [comment]
可在readme中找到交流群二维码更新
