### ISSUE TITLE
可以指定模型位置么

### ISSUE THREAD

**Issue by asus10tu** [OpenBMB/MiniCPM-V#219]
执行web_demo_2.5.py的时候，一定会默认下载模型，但是我已经手动下载了。

**Comment by iceflame89** [comment]
web_demo_2.5.py 代码中 `model_path = 'openbmb/MiniCPM-Llama3-V-2_5'` 替换成本地路径即可
https://github.com/OpenBMB/MiniCPM-V/blob/main/web_demo_2.5.py#L26-L28
