### ISSUE TITLE
Lora微调后如何进行测试呢

### ISSUE THREAD

**Issue by lyc728** [OpenBMB/MiniCPM-V#222]
预训练模型：MiniCPM-Llama3-V-2_5
```
model = AutoPeftModelForCausalLM.from_pretrained(
    # path to the output directory
    model_path,
    device_map="auto",
    trust_remote_code=True
).eval()

torch.manual_seed(0)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

im_64 = '/6f8028485ed8fcd8.jpg'

# First round chat 
msgs = [{"role": "user", "content": "what is the date of the workshop? Answer the question with detailed explanation."}]


imagefile = Image.open(im_64).convert('RGB')
answer = model.chat(image=imagefile, msgs=msgs, tokenizer=tokenizer,
                         sampling=True,temperature=0.7, stream=True)
print(answer)
```
<img width="547" alt="企业微信截图_17175881184738" src="https://github.com/OpenBMB/MiniCPM-V/assets/88084847/25438a32-22af-45b7-bad4-f2ff87b7fd2d">

推理后直接是在这样的，代码应该如何更改

**Comment by qyc-98** [comment]
您好 关于lora微调 我们即将跟新一版代码，解决其中存在的一些问题，建议您在更新代码后重新进行lora微调。这次更新主要是解决了lora微调后，模型的视觉部分参数没有正常保存，导致您的训练失效，我们深感抱歉。您可以参考最新的lora加载方式，参见finetune下的readme.md。谢谢您的支持

**Comment by lyc728** [comment]
> 您好 关于lora微调 我们即将跟新一版代码，解决其中存在的一些问题，建议您在更新代码后重新进行lora微调。这次更新主要是解决了lora微调后，模型的视觉部分参数没有正常保存，导致您的训练失效，我们深感抱歉。您可以参考最新的lora加载方式，参见finetune下的readme.md。谢谢您的支持

你是已经更新了吗？我现在正在微调训练

**Comment by qyc-98** [comment]
您好 已经更新了 可以尝试一下

**Comment by lihua8848** [comment]
Still have the same problem
![image](https://github.com/OpenBMB/MiniCPM-V/assets/54617440/5780a9de-5c5e-4419-a25d-508b4f7e404f)

**Comment by limllzu** [comment]
你好，请问解决了吗，我在使用MiniCPM-V_2全量微调训练后，在加载模型时也遇到了问题
