### ISSUE TITLE
question about using image/text embedding separately

### ISSUE THREAD

**Issue by zhwuwuwu** [OpenBMB/MiniCPM-V#225]
可以分别单独使用模型的image和text embedding吗？想用embedding结果做retrival。

**Comment by bokesyo** [comment]
你好，这个模型是language modeling，不是CLIP所以不能做检索

**Comment by bokesyo** [comment]
@zhwuwuwu 你好，我们现在训练了一个可以用MiniCPM-V做多模态文档检索的模型，应该能满足你的需求。

模型权重：https://huggingface.co/RhapsodyAI/minicpm-visual-embedding-v0

使用教程：https://github.com/RhapsodyAILab/Awesome-MiniCPMV-Projects/tree/main/visrag
