### ISSUE TITLE
[BUG] <华为Mate60Pro没有上传图片的>

### ISSUE THREAD

**Issue by zhuwo** [OpenBMB/MiniCPM-V#227]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

华为Mate60Pro60Pro使用异常， 没有上传图片的入口

### 期望行为 | Expected Behavior

华为Mate60Pro60Pro可以上传图片，测试OCR能力

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

![image](https://github.com/OpenBMB/MiniCPM-V/assets/9333001/ec28cfb1-5cb0-42e4-8d17-d94d2b3ed95a)

**Comment by iceflame89** [comment]
请先点右上角下载模型
