### ISSUE TITLE
batch inference

### ISSUE THREAD

**Issue by berry-ding** [OpenBMB/MiniCPM-V#228]
hi, great work! how to implement the batch inference in offline environment.

**Comment by BoyuGuan** [comment]
I also want to know because I need to obtain the inference result of MiniCPM-Llama3-V-2_5 on my own dataset.

**Comment by Cuiunbo** [comment]
Hi, thanks a lot for your support, we are not trying to support batch input at the moment, because most of the time bs=1 can already take up a full resource. If you need batch infer, you are welcome to implement it by yourself.
