### ISSUE TITLE
💡 [REQUEST] - 希望有模型部署的 Dockerfile

### ISSUE THREAD

**Issue by hqsh** [OpenBMB/MiniCPM-V#231]
### 摘要 | Summary

能否有个 Dockerfile，方便部署

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by hyphantom** [comment]
同求 windows编译不过去 ollama的分支

**Comment by iceflame89** [comment]
由于人力有限，我们恐怕没办法提供各种平台部署的Dockerfile，我们已提供了huggingface, vllm, llama.cpp, ollama多种部署框架的使用说明，如有问题欢迎提issue～
