### ISSUE TITLE
[BUG] 微信群扫码无法进群，提示人数超过200人需要邀请，麻烦提供可拉人的微信号

### ISSUE THREAD

**Issue by hqsh** [OpenBMB/MiniCPM-V#232]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by iceflame89** [comment]
新群二维码已更新，https://github.com/OpenBMB/MiniCPM-V/blob/main/docs/wechat.md， 请重新扫码加入～

**Comment by White65534** [comment]
还是没办法进群，请拉我进群呀，我们实验室好多人都想进群

**Comment by White65534** [comment]
> 新群二维码已更新，[https://github.com/OpenBMB/MiniCPM-V/blob/main/docs/wechat.md，](https://github.com/OpenBMB/MiniCPM-V/blob/main/docs/wechat.md%EF%BC%8C) 请重新扫码加入～

二维码又过期了
