### ISSUE TITLE
[BUG] xiaomi 14 pro 使用 MiniCPM-V2.5 加载时间很长 

### ISSUE THREAD

**Issue by AkkaXdXd** [OpenBMB/MiniCPM-V#236]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

MiniCPM-V2.5 加载时间很长 大概300s 且加载完之后 发送的图片没有解析
![291d3ac4a06545ba310601e14b45862](https://github.com/OpenBMB/MiniCPM-V/assets/13690362/b77785e9-19ae-4cba-8fec-642768e4bd0e)

### 运行环境 | Environment

```Markdown
- OS: 
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by iceflame89** [comment]
请将app强制退出后重试，正常情况下模型加载时间不会很长，发送图片后，顶部会出现提示“开始解析图片”，等待解析完毕后即可开始提问
