### ISSUE TITLE
Can we use in-context multimodal data for finetuning?

### ISSUE THREAD

**Issue by waltonfuture** [OpenBMB/MiniCPM-V#237]
Thanks for your great work! However, it seems that we can only use data that contains one image for SFT. Can we use in-context multimodal data (i.e., containing multiple images) for finetuning?

**Comment by qyc-98** [comment]
yes, the code supports multi-image finetuning

**Comment by haochuan-li** [comment]
Same problem here. Any update on multi-image sft?

**Comment by waltonfuture** [comment]
@qyc-98 Hello! Can you provide some simple examples of in-context inference or SFT? Thanks a lot!

**Comment by 1SingleFeng** [comment]
@qyc-98 I have encountered the same problem. Have you resolved it

**Comment by pbarker** [comment]
+1 also curious about this
