### ISSUE TITLE
请问MiniCPM-Llama3-V 2.5的手机端部署后续会开源吗？

### ISSUE THREAD

**Issue by xcd-1** [OpenBMB/MiniCPM-V#239]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

请问一下MiniCPM-Llama3-V 2.5的手机端部署后续会开源吗？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by iceflame89** [comment]
你好，手机apk可能不会开源，这部分逻辑比较简单，底层是利用llama.cpp推理，您可自己实现～

**Comment by AnyangAngus** [comment]
> 你好，手机apk可能不会开源，这部分逻辑比较简单，底层是利用llama.cpp推理，您可自己实现～

@iceflame89  安卓 apk调用 minicpm-v llamacpp版本 可以参考https://github.com/ggerganov/llama.cpp/tree/master/examples/llama.android 这个工程demo 实现成功麽
