### ISSUE TITLE
请什么时候可以发布微调代码？

### ISSUE THREAD

**Issue by thesby** [OpenBMB/MiniCPM-V#24]
您好，感谢发布这么优秀的模型。请问什么时候可以提供微调代码呢？

**Comment by qiuhuiGithub** [comment]
同问

**Comment by iceflame89** [comment]
感谢关注，MiniCPM-V 1.0的finetune代码可以参考[swift](https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/minicpm-v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E5%BE%AE%E8%B0%83)中的实现。
