### ISSUE TITLE
[BUG] 4bit模型的结果混乱

### ISSUE THREAD

**Issue by HaoLiuHust** [OpenBMB/MiniCPM-V#241]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在T4显卡上，使用web_demo_2.5.py载入4bit模型，输入图片问问题，基本上都是乱答。然后又使用huggingface上的代码启动，也乱答。
<img width="375" alt="2cd86b2f5372d79338e825f9821f35b" src="https://github.com/OpenBMB/MiniCPM-V/assets/7233091/57e433a1-600b-4406-b87a-2f69dc086165">

<img width="502" alt="251a7dc83fcb4a015eb9cda5d181a59" src="https://github.com/OpenBMB/MiniCPM-V/assets/7233091/c9dd446c-58c7-47ef-864f-2c7c1cd82562">

### 运行环境 | Environment

```Markdown
- OS:ubuntu 18.04
- Python:3.9
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12
```

**Comment by iceflame89** [comment]
请提供原图以便我们复现问题

**Comment by HaoLiuHust** [comment]
使用lmdeloy量化和部署正常
