### ISSUE TITLE
[BUG] resampler frozen while LoRA finetuning

### ISSUE THREAD

**Issue by Fr0do** [OpenBMB/MiniCPM-V#243]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

With default config resampler is neither a LoRA module nor unfrozen for full finetuning. Seems to be the fixable by adding `modules_to_save=['resampler'],` to [`LoraConfig`](https://github.com/OpenBMB/MiniCPM-V/blob/main/finetune/finetune.py#L253).

### 期望行为 | Expected Behavior

Resampler is finetuned during LoRA training.

### 复现方法 | Steps To Reproduce

run `finetune_lora.sh`

### 运行环境 | Environment

```Markdown
requirements.txt
```

**Comment by qyc-98** [comment]
我们重新更新了训练代码，主要是针对lora做的改进，并且修改了huggingface 上的模型代码，您可以重新尝试一下
