### ISSUE TITLE
Multiple frames from video

### ISSUE THREAD

**Issue by Tsardoz** [OpenBMB/MiniCPM-V#244]
Does it work with multiple frames?
I tried reading sequential frames froma folder, converting to base64 and appending but I get an error when using chat_model.chat(inputs). Is this supported?
[test_video.txt](https://github.com/user-attachments/files/15747149/test_video.txt)

**Comment by Cuiunbo** [comment]
hi, this is a very good try. it is capable of inputting multiple images. But of course, it wasn't trained on video scenarios, which leads to the fact that he may not be very good. You can have a try. 
please refer to this link
https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5/discussions/2
