### ISSUE TITLE
[BUG] <title>windows系统使用ollama运行MiniCPM-Llama3-V-2_5的gguf各种量化版本，均不能加载识别图片

### ISSUE THREAD

**Issue by zrainbowk** [OpenBMB/MiniCPM-V#247]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

windows系统使用ollama运行MiniCPM-Llama3-V-2_5的gguf各种量化版本，均不能加载识别图片。
<img width="860" alt="e5c0ea3fe8644b854878abecf52d93c" src="https://github.com/OpenBMB/MiniCPM-V/assets/134673044/6407efb9-17b5-4d73-b996-0fadb3424c06">
同样使用ollama，更换llava模型可以正常加载识别图片。
<img width="852" alt="2943ceea79a94d5a8659bd9bc63a9fe" src="https://github.com/OpenBMB/MiniCPM-V/assets/134673044/e267071d-a579-40c5-9e13-e71ceed9b8f1">

### 期望行为 | Expected Behavior

有什么办法可以使得ollama运行MiniCPM-Llama3-V-2_5的gguf各种量化版本，能成功加载和识别图片

### 运行环境 | Environment

```Markdown
- OS:Windows 11 专业版 26100.1
- Python:3.11.7
- Transformers:4.41.2
- PyTorch:2.3.1+cu121
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.4
```

**Comment by TonyHuang6666** [comment]
老哥你好，请问解决了吗?我也是在Windows, WSL和Ubuntu都没法分析图片

**Comment by nigo81** [comment]
不能用官方的ollama，需要用build的：https://github.com/OpenBMB/MiniCPM-V/issues/171
