### ISSUE TITLE
请问支持中文数据微调/推理吗 

### ISSUE THREAD

**Issue by LianghuiGuo** [OpenBMB/MiniCPM-V#25]
请问支持中文数据微调/推理吗

**Comment by iceflame89** [comment]
感谢关注，MiniCPM-V 1.0的finetune代码可以参考[swift](https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/minicpm-v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E5%BE%AE%E8%B0%83)中的实现。
