### ISSUE TITLE
what does  --ckpt mean in eval script?

### ISSUE THREAD

**Issue by hill2hill** [OpenBMB/MiniCPM-V#251]
```
# model name and model path
--model_name
--model_path
# load model from ckpt
--ckpt
```

when should i set this param? its default [value](https://github.com/OpenBMB/MiniCPM-V/blob/d9cf8604f3816a550772977568fce352c0489bac/eval_mm/vqaeval/eval_utils/getargs.py#L59) is "", but [code](https://github.com/OpenBMB/MiniCPM-V/blob/d9cf8604f3816a550772977568fce352c0489bac/eval_mm/vqaeval/models/MiniCPM/minicpmv.py#L20) only check whether it is None.

**Comment by hill2hill** [comment]
In my case, I just modified the --ckpt to be None. And it looks like working fine, i can reproduce the textVQA result with run_inference.sh. 
One thing might be helpful when somebody meet the error like: TypeError: MiniCPMV.chat() missing 1 required positional argument: 'image'. You can add one line [arg](https://github.com/OpenBMB/MiniCPM-V/blob/d9cf8604f3816a550772977568fce352c0489bac/eval_mm/vqaeval/models/MiniCPM/minicpmv.py#L87) like:
```
res = self.model.chat(
            image=image,
            msgs=msgs,
            context=None,
            tokenizer=self.tokenizer,
            **default_kwargs
        )
```
if using --generate_method interleave in run_inference.sh

**Comment by Cuiunbo** [comment]
thanks～
