### ISSUE TITLE
macbook m3 运行web_demo_2.5.py，不能返回正常中文信息[BUG] <title>

### ISSUE THREAD

**Issue by nigo81** [OpenBMB/MiniCPM-V#258]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我按Readme文档安装后，执行`PYTORCH_ENABLE_MPS_FALLBACK=1 python3 web_demo_2.5.py --device mps`,在网页上传图片并提问，返回的都是无意义的非中文文字。
<img width="1196" alt="image" src="https://github.com/OpenBMB/MiniCPM-V/assets/38601513/19d257c6-3c13-4821-8b24-9c9587cab6c1">
<img width="1486" alt="image" src="https://github.com/OpenBMB/MiniCPM-V/assets/38601513/6a75e586-3ab8-4e17-9884-733e19b047a6">

### 期望行为 | Expected Behavior

希望能和示例demo效果一样，能使用模型返回正确中文信息。

### 运行环境 | Environment

```Markdown
- OS:macOS 14.4.1 23E224 arm64
- Python:Python 3.10.14
- Transformers:transformers==4.40.0
- PyTorch:torch==2.1.2，torchvision==0.16.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):None
```

**Comment by iceflame89** [comment]
你好，为方便调试，麻烦提供可复现的图像和prompt～
