### ISSUE TITLE
fine tune

### ISSUE THREAD

**Issue by betterftr** [OpenBMB/MiniCPM-V#26]
Hello, is it possible (will it be) to fine tune with peft lora and quantization?

**Comment by iceflame89** [comment]
Finetune code for MiniCPM-V 1.0 is available in [swift](https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/minicpm-v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E5%BE%AE%E8%B0%83)  .
