### ISSUE TITLE
官方提供的web_demo_2.5.py在mmbench上测试 指令遵从能力很差 不能输出abcd

### ISSUE THREAD

**Issue by linwenzhao1** [OpenBMB/MiniCPM-V#271]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

<img width="658" alt="DAF80036-509F-4B1A-A408-B53046B51AF1" src="https://github.com/OpenBMB/MiniCPM-V/assets/51796215/c701853e-3792-43f4-bd06-1a66a89812d0">

### 期望行为 | Expected Behavior

简洁的答案：A B C D

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Cuiunbo** [comment]
您好，可尝试更直观的prompt，如通过给出全部输出的格式来使模型输出有参考。或者参考我们的评测代码
https://github.com/OpenBMB/MiniCPM-V/blob/main/eval_mm/vlmevalkit/vlmeval/vlm/minicpm_llama3_v_2_5.py#L63

**Comment by linwenzhao1** [comment]
> 您好，可尝试更直观的prompt，如通过给出全部输出的格式来使模型输出有参考。或者参考我们的评测代码 https://github.com/OpenBMB/MiniCPM-V/blob/main/eval_mm/vlmevalkit/vlmeval/vlm/minicpm_llama3_v_2_5.py#L63

中文的prompt有吗？
