### ISSUE TITLE
[BUG] <title>LORA微调后保存的权重没有vpm_resampler_embedtokens.pt

### ISSUE THREAD

**Issue by 1SingleFeng** [OpenBMB/MiniCPM-V#272]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

https://github.com/OpenBMB/MiniCPM-V/tree/main/finetune#lora-finetuning
根据这个链接下的信息，按理说lora微调训练后保存的权重应该有vpm_resampler_embedtokens.pt，但是在我的训练结果下并没有发现

### 期望行为 | Expected Behavior

lora微调训练后保存的权重应该有vpm_resampler_embedtokens.pt

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by 1SingleFeng** [comment]
我是在zero3配置下训练的结果

**Comment by 1SingleFeng** [comment]
> 我是在zero3配置下训练的结果

在训练脚本里，我也开启了    --tune_vision true

**Comment by 1SingleFeng** [comment]
> the same issue #243 I don't know why it took so long to fix it.

你好，最新版的代码貌似解决了这个问题，我还在验证

**Comment by whyiug** [comment]
> > the same issue #243 I don't know why it took so long to fix it.
> 
> 你好，最新版的代码貌似解决了这个问题，我还在验证

 still not fixed. using zero2.
 ping @qyc-98

**Comment by 1SingleFeng** [comment]
> > > the same issue #243 I don't know why it took so long to fix it.
> > 
> > 
> > 你好，最新版的代码貌似解决了这个问题，我还在验证
> 
> still not fixed. using zero2. ping @qyc-98

你好，我使用了zero3解决了这个问题

**Comment by LDLINGLINGLING** [comment]
import torch
# 文件路径
file_path = '/root/ld/ld_project/pull_request/MiniCPM-V/finetune/output/output_minicpmv2_lora/checkpoint-10/vpm_resampler_embedtokens.pt'
# 使用torch.load加载文件
checkpoint = torch.load(file_path, map_location=torch.device('cpu'))  # 或'mcuda:0'如果你在GPU上运行
print(checkpoint.keys())

**Comment by whyiug** [comment]
@LDLINGLINGLING If you train with zero2, the vpm_resampler_embedtokens.pt file is saved as 1000B in size, i.e. it's empty!

**Comment by whyiug** [comment]
@LDLINGLINGLING Here's why, even if you don't use zero3's lora finetune, you'll still get here. [See code](https://github.com/OpenBMB/MiniCPM-V/blob/ef7cfa81ec4b9af5096a4b05f7e92da1c58093f8/finetune/finetune.py#L119) , and only keep the lora parameter.

**Comment by whyiug** [comment]
@LDLINGLINGLING any update?
