### ISSUE TITLE
mincpm v2可以输出置信度吗，应该修改哪部分代码💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by dsdsdsdssdsfth** [OpenBMB/MiniCPM-V#275]
### 摘要 | Summary

mincpm v2可以输出置信度吗，应该修改哪部分代码

### 基本示例 | Basic Example

mincpm v2可以输出置信度吗，应该修改哪部分代码

### 缺陷 | Drawbacks

mincpm v2可以输出置信度吗，应该修改哪部分代码

**Comment by LDLINGLINGLING** [comment]
你要生成什么的置信度呢，生成的文本是一串字符，每一个字符都可以生成置信度，但是总体置信度显然不适合使用每个字符的概率连乘

**Comment by 128Ghe980** [comment]
> 你要生成什么的置信度呢，生成的文本是一串字符，每一个字符都可以生成置信度，但是总体置信度显然不适合使用每个字符的概率连乘

您好，现在minicpmv-2.6应该如何输出每个字符对应的置信度呢？
