### ISSUE TITLE
[BUG] --max_slice_nums > than 9 will not work

### ISSUE THREAD

**Issue by joaomsimoes** [OpenBMB/MiniCPM-V#277]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

When setting max_slice_nums > 9 for lora fine tune it gives the following error `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"`. There is any way to increase this number?

### 期望行为 | Expected Behavior

Fine tune the model

### 复现方法 | Steps To Reproduce

Follow the lora finetune instructions

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by qyc-98** [comment]
hi this is a bug, please fix the value to 9

**Comment by joaomsimoes** [comment]
There will be any future update? I would like to increase this value so I can improve for OCR tasks
