### ISSUE TITLE
💡 [REQUEST] - <是否有说明可以将该模型发布成openai 适配的api>

### ISSUE THREAD

**Issue by weiminw** [OpenBMB/MiniCPM-V#280]
### 摘要 | Summary

说明可以将该模型发布成openai 适配的api

### 基本示例 | Basic Example

说明可以将该模型发布成openai 适配的api

### 缺陷 | Drawbacks

说明可以将该模型发布成openai 适配的api

**Comment by Cuiunbo** [comment]
https://github.com/OpenBMB/MiniCPM-V/issues/119#issuecomment-2131081725
check this
