### ISSUE TITLE
Question about full-parameter finetuning

### ISSUE THREAD

**Issue by dydxdt** [OpenBMB/MiniCPM-V#282]
Thx for your great work!
I have a question about training arguments, i.e. is the parameter max_steps=10000 proper for full-parameter finetuning? 

I use my own train datset for full-parameter finetuning and the dataset has around 240,000 data. After I use the default training setting to train the model, I see the training log shows : "epoch: 0.32", which means it uses 1/3 data of the training data. My training dataset contains 3 different tasks(caption,ocr,...). Then I use the num_train_epochs(=5, same as qwen) instead of max_steps to train, but I found the model with 5 epochs performs worse than that with 10000 steps when testing on my caption testset. The loss seems normal. So Can you give some advice for this situation? Thx!

10000 step: (corresponding to red line, ignore blue line)
![image](https://github.com/OpenBMB/MiniCPM-V/assets/46140371/38ed0dae-3691-464e-a22b-3ced8c95978a)

~5 epoch:
![企业微信截图_e7e709a1-4fab-4034-a4b1-3591945db1dc](https://github.com/OpenBMB/MiniCPM-V/assets/46140371/e78e09a0-6498-414a-adc4-aacdff019bdc)

**Comment by 1SingleFeng** [comment]
请问

> Thx for your great work! I have a question about training arguments, i.e. is the parameter max_steps=10000 proper for full-parameter finetuning?
> 
> I use my own train datset for full-parameter finetuning and the dataset has around 240,000 data. After I use the default training setting to train the model, I see the training log shows : "epoch: 0.32", which means it uses 1/3 data of the training data. My training dataset contains 3 different tasks(caption,ocr,...). Then I use the num_train_epochs(=5, same as qwen) instead of max_steps to train, but I found the model with 5 epochs performs worse than that with 10000 steps when testing on my caption testset. The loss seems normal. So Can you give some advice for this situation? Thx!
> 
> 10000 step: (corresponding to red line, ignore blue line) ![image](https://private-user-images.githubusercontent.com/46140371/340601681-38ed0dae-3691-464e-a22b-3ced8c95978a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM4MjcsIm5iZiI6MTcxODg1MzUyNywicGF0aCI6Ii80NjE0MDM3MS8zNDA2MDE2ODEtMzhlZDBkYWUtMzY5MS00NjRlLWEyMmItM2NlZDhjOTU5NzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YmFhMWE2MTQwMGFhYTY0MTM0ZjI5NGI2NWY4ZTdmYTNhZjIxMWQyNzU0YjU1ZjVlZDNkMTNlNGM1ZDhiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6aiP82DzUf8YBw1qhddZ_LDS6l3tmzkWB5qOvBFMbx0)
> 
> ~5 epoch: ![企业微信截图_e7e709a1-4fab-4034-a4b1-3591945db1dc](https://private-user-images.githubusercontent.com/46140371/340602015-e78e09a0-6498-414a-adc4-aacdff019bdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM4MjcsIm5iZiI6MTcxODg1MzUyNywicGF0aCI6Ii80NjE0MDM3MS8zNDA2MDIwMTUtZTc4ZTA5YTAtNjQ5OC00MTRhLWFkYzQtYWFjZGZmMDE5YmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NDg5MzRlMTY2NjYzYjVhYWM5YTFhZmFiMDU0YTNmYzBiYTAxMGE2MDQ2YjA1MGRhYjRiYmI1YzU1YzZlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRk-KpmIonXmY5v2M-O3ZusbXqTXYDHKBguCWyZ4_Ig)



> Thx for your great work! I have a question about training arguments, i.e. is the parameter max_steps=10000 proper for full-parameter finetuning?
> 
> I use my own train datset for full-parameter finetuning and the dataset has around 240,000 data. After I use the default training setting to train the model, I see the training log shows : "epoch: 0.32", which means it uses 1/3 data of the training data. My training dataset contains 3 different tasks(caption,ocr,...). Then I use the num_train_epochs(=5, same as qwen) instead of max_steps to train, but I found the model with 5 epochs performs worse than that with 10000 steps when testing on my caption testset. The loss seems normal. So Can you give some advice for this situation? Thx!
> 
> 10000 step: (corresponding to red line, ignore blue line) ![image](https://private-user-images.githubusercontent.com/46140371/340601681-38ed0dae-3691-464e-a22b-3ced8c95978a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM4MjcsIm5iZiI6MTcxODg1MzUyNywicGF0aCI6Ii80NjE0MDM3MS8zNDA2MDE2ODEtMzhlZDBkYWUtMzY5MS00NjRlLWEyMmItM2NlZDhjOTU5NzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YmFhMWE2MTQwMGFhYTY0MTM0ZjI5NGI2NWY4ZTdmYTNhZjIxMWQyNzU0YjU1ZjVlZDNkMTNlNGM1ZDhiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6aiP82DzUf8YBw1qhddZ_LDS6l3tmzkWB5qOvBFMbx0)
> 
> ~5 epoch: ![企业微信截图_e7e709a1-4fab-4034-a4b1-3591945db1dc](https://private-user-images.githubusercontent.com/46140371/340602015-e78e09a0-6498-414a-adc4-aacdff019bdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM4MjcsIm5iZiI6MTcxODg1MzUyNywicGF0aCI6Ii80NjE0MDM3MS8zNDA2MDIwMTUtZTc4ZTA5YTAtNjQ5OC00MTRhLWFkYzQtYWFjZGZmMDE5YmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NDg5MzRlMTY2NjYzYjVhYWM5YTFhZmFiMDU0YTNmYzBiYTAxMGE2MDQ2YjA1MGRhYjRiYmI1YzU1YzZlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRk-KpmIonXmY5v2M-O3ZusbXqTXYDHKBguCWyZ4_Ig)



> Thx for your great work! I have a question about training arguments, i.e. is the parameter max_steps=10000 proper for full-parameter finetuning?
> 
> I use my own train datset for full-parameter finetuning and the dataset has around 240,000 data. After I use the default training setting to train the model, I see the training log shows : "epoch: 0.32", which means it uses 1/3 data of the training data. My training dataset contains 3 different tasks(caption,ocr,...). Then I use the num_train_epochs(=5, same as qwen) instead of max_steps to train, but I found the model with 5 epochs performs worse than that with 10000 steps when testing on my caption testset. The loss seems normal. So Can you give some advice for this situation? Thx!
> 
> 10000 step: (corresponding to red line, ignore blue line) ![image](https://private-user-images.githubusercontent.com/46140371/340601681-38ed0dae-3691-464e-a22b-3ced8c95978a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM4MjcsIm5iZiI6MTcxODg1MzUyNywicGF0aCI6Ii80NjE0MDM3MS8zNDA2MDE2ODEtMzhlZDBkYWUtMzY5MS00NjRlLWEyMmItM2NlZDhjOTU5NzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YmFhMWE2MTQwMGFhYTY0MTM0ZjI5NGI2NWY4ZTdmYTNhZjIxMWQyNzU0YjU1ZjVlZDNkMTNlNGM1ZDhiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6aiP82DzUf8YBw1qhddZ_LDS6l3tmzkWB5qOvBFMbx0)
> 
> ~5 epoch: ![企业微信截图_e7e709a1-4fab-4034-a4b1-3591945db1dc](https://private-user-images.githubusercontent.com/46140371/340602015-e78e09a0-6498-414a-adc4-aacdff019bdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM4MjcsIm5iZiI6MTcxODg1MzUyNywicGF0aCI6Ii80NjE0MDM3MS8zNDA2MDIwMTUtZTc4ZTA5YTAtNjQ5OC00MTRhLWFkYzQtYWFjZGZmMDE5YmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NDg5MzRlMTY2NjYzYjVhYWM5YTFhZmFiMDU0YTNmYzBiYTAxMGE2MDQ2YjA1MGRhYjRiYmI1YzU1YzZlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRk-KpmIonXmY5v2M-O3ZusbXqTXYDHKBguCWyZ4_Ig)

请问你使用了多少资源进行全参数微调，我使用2张v100和4张v100均不行

**Comment by todaydeath** [comment]
我在全参微调的时候，控制台不打印loss信息，这个有遇到过么

**Comment by LDLINGLINGLING** [comment]
> 请问你使用了多少资源进行全参数微调，我使用2张v100和4张v100均不行

全量微调的话可能要8张v100

**Comment by LDLINGLINGLING** [comment]
> Thx for your great work!感谢您的出色工作！ I have a question about training arguments, i.e. is the parameter max_steps=10000 proper for full-parameter finetuning?我有一个关于训练参数的问题，即参数 max_steps=10000 是否适合全参数微调？
> 
> I use my own train datset for full-parameter finetuning and the dataset has around 240,000 data. After I use the default training setting to train the model, I see the training log shows : "epoch: 0.32", which means it uses 1/3 data of the training data. My training dataset contains 3 different tasks(caption,ocr,...). Then I use the num_train_epochs(=5, same as qwen) instead of max_steps to train, but I found the model with 5 epochs performs worse than that with 10000 steps when testing on my caption testset. The loss seems normal. So Can you give some advice for this situation? Thx!我使用自己的训练数据集进行全参数微调，数据集大约有 240,000 个数据。使用默认训练设置训练模型后，我看到训练日志显示：“epoch：0.32”，这意味着它使用了训练数据的 1/3 数据。我的训练数据集包含 3 个不同的任务（caption、ocr,...）。然后我使用 num_train_epochs（=5，与 qwen 相同）而不是 max_steps 进行训练，但我发现在我的标题测试集上测试时，具有 5 个 epochs 的模型比具有 10000 步的模型性能更差。损失似乎很正常。那么，您能为这种情况提供一些建议吗？感谢！
> 
> 10000 step: (corresponding to red line, ignore blue line)10000步：（对应红线，忽略蓝线） ![image](https://private-user-images.githubusercontent.com/46140371/340601681-38ed0dae-3691-464e-a22b-3ced8c95978a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ4NjAsIm5iZiI6MTcyMDA4NDU2MCwicGF0aCI6Ii80NjE0MDM3MS8zNDA2MDE2ODEtMzhlZDBkYWUtMzY5MS00NjRlLWEyMmItM2NlZDhjOTU5NzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5MTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYWU5ZGI0YTlmNDAwNWQ5ZWUwMTdmYjc5MmI5NWI0MjEwMDRiMzkxNzkxODhiMDc3NDIyNGYzM2I0MGFjN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3SGcijHRzkZiY1L3A_71GgrMWhNPEvh8f1Zg2--1gqo)
> 
> ~5 epoch: ~5 纪元： ![企业微信截图_e7e709a1-4fab-4034-a4b1-3591945db1dc](https://private-user-images.githubusercontent.com/46140371/340602015-e78e09a0-6498-414a-adc4-aacdff019bdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ4NjAsIm5iZiI6MTcyMDA4NDU2MCwicGF0aCI6Ii80NjE0MDM3MS8zNDA2MDIwMTUtZTc4ZTA5YTAtNjQ5OC00MTRhLWFkYzQtYWFjZGZmMDE5YmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5MTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNTZkNDk1MDUxZGIwYmI3ZDIxYTZhYmNiMGVhMzJlZDM5ODQ3MjQzNjFhYWEyNWZiYjUzZWIyMDI5NjU4N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RNlrEknoVF0udFm0Juat5eex4Aj-rVpp7Bk8bowAwt4)

The picture you gave only shows the train loss, which cannot reflect the real effect, so it is meaningless to only look at the loss.
