### ISSUE TITLE
MiniCPM-Llama3-V 2.5 全参数微调最小的显存需求

### ISSUE THREAD

**Issue by Millie-Xu** [OpenBMB/MiniCPM-V#286]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 期望行为 | Expected Behavior

针对 MiniCPM-Llama3-V 2.5，我使用两张2张v100或者4张v100，batchsize设置为1，deepspeed zero3配置，并尽可能将所有参数放置在cpu上，仍然显示显存不够，请问该模型全参数微调所需的最小显存需求是什么？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yihp** [comment]
@Millie-Xu offload到cpu都不够吗？另外请问您使用的是什么微调脚本呢？

**Comment by Millie-Xu** [comment]
你好，我已经解决啦，谢谢

**Comment by todaydeath** [comment]
> 你好，我已经解决啦，谢谢
请问你是怎么解决的呢？最终占用了多少显存？

**Comment by Millie-Xu** [comment]
用了8张V100，显存差不多占满了

**Comment by Millie-Xu** [comment]
> > 你好，我已经解决啦，谢谢
> > 请问你是怎么解决的呢？最终占用了多少显存？

用了8张V100，显存差不多占满了

**Comment by LDLINGLINGLING** [comment]
那你应该是全量微调对吧
