### ISSUE TITLE
请问minicpm-llama3-v-2_5可以支持哪些量化措施，支持awq量化吗

### ISSUE THREAD

**Issue by 1SingleFeng** [OpenBMB/MiniCPM-V#287]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

**Comment by LDLINGLINGLING** [comment]
awq的量化我们正在对接，积极跟autoawq沟通
