### ISSUE TITLE
[BUG] minicpm-llama3-v-2_5(int4)只能使用PIL打开图像吗

### ISSUE THREAD

**Issue by morestart** [OpenBMB/MiniCPM-V#289]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by iceflame89** [comment]
是的，只支持PIL image输入
