### ISSUE TITLE
[BUG] <title>Can't the chat method pass in the max_tokens or max_new_tokens parameters? What if the length is managed?

### ISSUE THREAD

**Issue by orderer0001** [OpenBMB/MiniCPM-V#295]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

The chat method cannot pass in the max_tokens or max_new_tokens parameters

### 期望行为 | Expected Behavior

Want the ability to generate content length management

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
chat其实是在generate的方法上进行封装，因此可以把生成参数通过chat传到generate里面，
