### ISSUE TITLE
微信二维码过期，帮忙更新，谢谢！[BUG] <title>

### ISSUE THREAD

**Issue by baleli668** [OpenBMB/MiniCPM-V#297]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 期望行为 | Expected Behavior

微信二维码过期了，帮忙更新，谢谢

### 复现方法 | Steps To Reproduce

微信二维码过期了，帮忙更新，谢谢

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

微信二维码过期了，帮忙更新，谢谢

**Comment by jctime** [comment]
更新了
