### ISSUE TITLE
[Data info] MiniCPM-llama3-V 2.5

### ISSUE THREAD

**Issue by emanuelevivoli** [OpenBMB/MiniCPM-V#300]
Hello, and Thanks for the amazing work! Very much appreciated :)

I have read the [MiniCPM-V 2 blog](https://openbmb.vercel.app/minicpm-v-2-en) and the sources you cite in the blog post, as well as the [MiniCPM blogpost](https://openbmb.vercel.app/minicpm-en). Also, I tried to check the available dataset you provide on the [huggingface dataset page](https://huggingface.co/openbmb) and also a recent [issue discussion where you named the training data](https://github.com/OpenBMB/MiniCPM-V/issues/196#issuecomment-2143920646) but I couldn't find the details I'm looking for.

My questions are:
- I suppose for the MiniCPM-llama3-V 2.5, you followed the same pre-training, sft, and alignment schema, but on what data?
- Is the data you trained **MiniCPM-llama3-V 2.5** open? It seems the details in the MiniCPM series are only related to text input.
- Where can I find more details on the pre-training / fine-tuning settings and data for MiniCPM-llama3-V 2.5?

Moreover, For the MiniCPM series, you released many versions, such as the sft, aligned and I suppose the base too.
Regarding the MiniCPM-llama3-V 2.5 it seems there is available only one model (full, int4), but only the (I think) aligned version (after the RLAIF-V alignment).

Can you provide more details or some references to better grasp that information? 
Thanks, Lele

**Comment by iceflame89** [comment]
Thanks for your attention, We have published the [technical report](https://github.com/OpenBMB/MiniCPM-V/blob/main/docs/MiniCPM_Llama3_V_25_technical_report.pdf), please read it for more detail.
