### ISSUE TITLE
[BUG] 你好，我想问下训练数据是图片的话，坐标里的xy对应的是图片的宽高吗

### ISSUE THREAD

**Issue by leohl1997** [OpenBMB/MiniCPM-V#305]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 期望行为 | Expected Behavior

你好，我想问下训练数据是图片的话，坐标里的xy对应的是图片的宽高吗

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
请问你说的坐标是什么坐标，能例举一下么
