### ISSUE TITLE
Whether the model supports batch inference？and whether the relevant example code can be provided？

### ISSUE THREAD

**Issue by MrHuangAm** [OpenBMB/MiniCPM-V#306]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

**Comment by zzhanghub** [comment]
I also need batch reasoning very much. The pad part of my own experiments always has problems

**Comment by zzhanghub** [comment]
I am also looking forward to batch infer. There are some issues with the pad part that I have implemented myself.

**Comment by MrHuangAm** [comment]
这是来自黄彦浩的自动回复邮件。你好，你的邮件我已经收到

**Comment by emanuelevivoli** [comment]
Apparently, there is a similar (more recent) issue with a proposed solution #339.
I'll check it out and let you know if it works 😃

**Comment by Zhouziyi828** [comment]
> Apparently, there is a similar (more recent) issue with a proposed solution #339. I'll check it out and let you know if it works 😃

Hello, I counter an error:
Segmentation fault (core dumped)

**Comment by emanuelevivoli** [comment]
It worked for me, with the following code:
```python
from lmdeploy import pipeline, TurbomindEngineConfig
from lmdeploy.vl import load_image

pipe = pipeline('openbmb/MiniCPM-Llama3-V-2_5', backend_config=TurbomindEngineConfig(session_len=2048, tp=2))

# if you use a notebook or interactive way, uncomment the following:
# import nest_asyncio
# nest_asyncio.apply()

image_urls=[
    "/path/to/image_1.jpg",
    "/path/to/image_2.jpg",
    # ...
    "/path/to/image_16.jpg",
]

prompts = [(' your prompt here', load_image(img_url)) for img_url in image_urls]
response = pipe(prompts)

print(response)
```

Now I'm trying to see whether it is convenient to use in terms of speed. It should be faster, but with batchsize=16 it takes 14 seconds, with full-resolution images and 2048 context window ... I'm comparing with single-image batchsize and/or quantized int4 version.

**Comment by qyc-98** [comment]
最新的minicpmv-llama3模型是支持batch inference的，请更新huggingface的模型代码
![image](https://github.com/user-attachments/assets/7e245987-0319-4c36-9538-499496fd8f38)
