### ISSUE TITLE
对齐和SFT所用的预训练数据集是什么

### ISSUE THREAD

**Issue by AshOneN** [OpenBMB/MiniCPM-V#307]
### 起始日期 | Start Date

none

### 实现PR | Implementation PR

none

### 相关Issues | Reference Issues

none

### 摘要 | Summary

none

### 基本示例 | Basic Example

none

### 缺陷 | Drawbacks

none

### 未解决问题 | Unresolved questions

none

**Comment by THUCSTHanxu13** [comment]
https://github.com/thunlp/UltraChat
https://github.com/OpenBMB/UltraFeedback
