### ISSUE TITLE
[BUG] Pre-training unstable

### ISSUE THREAD

**Issue by orrzohar** [OpenBMB/MiniCPM-V#309]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [x] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I am trying to pre-train MiniCPM-V-LLaMA3.
I tried the following: 
* lr 1e-3 to 1e-5
* batch size 128 to 1024
However, I keep getting NaNs in/after the perceiver resampler. 

### 期望行为 | Expected Behavior

Stable training

### 复现方法 | Steps To Reproduce

1. Clone this repo
2. download image pre-training datasets
3. do pretraining

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by qyc-98** [comment]
我们更新了模型代码和训练代码，可以重新尝试一下
