### ISSUE TITLE
请问什么时候可以开源微调代码？

### ISSUE THREAD

**Issue by cdxzyc** [OpenBMB/MiniCPM-V#31]

**Comment by SeanLiaoy** [comment]
https://github.com/OpenBMB/OmniLMM/pull/36
我实现了一版支持单图片的训练，可能有很多不完善的地方~希望能提供帮助

**Comment by iceflame89** [comment]
感谢关注，MiniCPM-V 1.0的finetune代码可以参考[swift](https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/minicpm-v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E5%BE%AE%E8%B0%83)中的实现。

**Comment by rover5056** [comment]
V

> 感谢关注，MiniCPM-V 1.0的finetune代码可以参考[swift](https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/minicpm-v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E5%BE%AE%E8%B0%83)中的实现。

v2.0的微调可以完全复用V1的 swift嘛
