### ISSUE TITLE
[Issue] AttributeError: 'LoraModel' object has no attribute '_enable_peft_forward_hooks'

### ISSUE THREAD

**Issue by ssuncheol** [OpenBMB/MiniCPM-V#310]
When I try to fine-tune MiniCPM-Llama3-V 2.5 in my workspace, the following error occurs. How do I solve it?

**Comment by LDLINGLINGLING** [comment]
你使用的是lora微调么？可以是试着更新peft和transformer版本试试

**Comment by ssuncheol** [comment]
> 你使用的是lora微调么？可以是试着更新peft和transformer版本试试

I would appreciate it if you could tell me the version of Peft and Transformer you are using.

**Comment by qyc-98** [comment]
这个应该是peft版本的问题，我的是0.11.0，您可以切换过来试试

**Comment by ssuncheol** [comment]
I'll try. thanks!
