### ISSUE TITLE
请问，商用的请求已经过去了 7 个工作日，还是没有收到回复的消息

### ISSUE THREAD

**Issue by zhjunqin** [OpenBMB/MiniCPM-V#311]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

请问一下，商用的请求已经过去了 7 个工作日，还是没有收到回复的消息，该怎么弄？

**Comment by zhjunqin** [comment]
https://modelbest.feishu.cn/share/base/form/shrcnpV5ZT9EJ6xYjh3Kx0J6v8g  填的这个表单

**Comment by jctime** [comment]
感谢您的关注与申请，由于最近申请量较大，所以有些延迟，我们会在本周内授权完剩下的所有
