### ISSUE TITLE
what is lr and batch_size in pretrain stage

### ISSUE THREAD

**Issue by aoji0606** [OpenBMB/MiniCPM-V#313]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

**Comment by qyc-98** [comment]
We will declare it in the paper which will be published in the future

**Comment by Wangman1** [comment]
请问大佬，如果从头开始训练pretrain阶段的话，启动命令应该怎么修改呢
