### ISSUE TITLE
[BUG] <OCR精度问题>

### ISSUE THREAD

**Issue by weiminw** [OpenBMB/MiniCPM-V#314]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

模型在OCR提取文字过程中, 比如营业执照, 有较大概率识别营业执照号码不正确, 经常是中间少一位. 请问有什么办法能提高OCR精度?

### 期望行为 | Expected Behavior

模型在OCR提取文字过程中, 比如营业执照, 有较大概率识别营业执照号码不正确, 经常是中间少一位. 请问有什么办法能提高OCR精度?

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by austingg** [comment]
可以看看中间错误，具体位置是否在slice 网格边界上。

**Comment by weiminw** [comment]
> 可以看看中间错误，具体位置是否在slice 网格边界上。 

有道理，我把图片大小做了修改后，识别成功了，感谢提醒
