### ISSUE TITLE
vllm推理无法安装环境

### ISSUE THREAD

**Issue by iiinsight** [OpenBMB/MiniCPM-V#315]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

g3001
Using virtual environment: /home/yangting/anaconda3/envs/vllm/bin/python
Obtaining file:///home/yangting/project/vllm
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fc669ad7290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cmake/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fc6682ac050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cmake/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fc6682b8910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cmake/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fc6682b9390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cmake/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fc6682ba250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/cmake/
      ERROR: Could not find a version that satisfies the requirement cmake>=3.21 (from versions: none)
      ERROR: No matching distribution found for cmake>=3.21
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
ImportError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yangting/project/vllm/examples/minicpmv_example.py", line 6, in <module>
    raise ImportError('Please install timm==0.9.10') from ImportError
ImportError: Please install timm==0.9.10

### 期望行为 | Expected Behavior

没有正常安装，一直报错是 error: subprocess-exited-with-error，请问这个需要怎么解决？

### 复现方法 | Steps To Reproduce

![image](https://github.com/OpenBMB/MiniCPM-V/assets/108727971/b96d6872-6180-474b-8f8b-16fd967ed56e)

### 运行环境 | Environment

```Markdown
- OS:Ubuntu
- Python:3.11
- Transformers:
- PyTorch:2.21
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

### 备注 | Anything else?

完全按照官网来运行，使用了集群slurm提交

**Comment by LDLINGLINGLING** [comment]
报错好像是timm==0.9.10这个包找不到啊
