### ISSUE TITLE
Where can i find the exact architecture used to train MiniCPM-Llama3-V 2.5 and implementation details

### ISSUE THREAD

**Issue by Abhinay2323** [OpenBMB/MiniCPM-V#319]
### 摘要 | Summary

Where can i find the exact architecture used to train MiniCPM-Llama3-V 2.5 and implementation details

### 基本示例 | Basic Example

..

### 缺陷 | Drawbacks

..

**Comment by LDLINGLINGLING** [comment]
我们近期可能会推出一些文章，请关注吧，也可以先看llava-UHd的论文

**Comment by Abhinay2323** [comment]
thanks
