### ISSUE TITLE
finetune on NPUs

### ISSUE THREAD

**Issue by EasonXiao-888** [OpenBMB/MiniCPM-V#320]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Hi, thanks for the perfect work, I want to ask if there is an official finetune code adapted for NPUs. I have already tried to manually migrate code from GPUs to NPUs, but I have encountered many bugs.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
Hi,what is your device, We look forward to your excellent work

**Comment by THUCSTHanxu13** [comment]
You can pay attention to our distributed toolkit BMTrain (https://github.com/OpenBMB/BMTrain). We will recently provide some branches running on NPUs.

**Comment by EasonXiao-888** [comment]
@THUCSTHanxu13 @LDLINGLINGLING Thanks a lot for your reply! My device is 910B and I will continue to pay attention on BMTrain.
By the way, could you please share the dataset during pre-training and supervised fine-tuning of MiniCPM-V2. I want to know whether there will be a significant performance degradation if I modify the model structure and fine-tune it on sharegpt-4v.
