### ISSUE TITLE
不同语言微调的问题💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by y-x-x123** [OpenBMB/MiniCPM-V#321]
### 摘要 | Summary

如果使用英文预料来微调，中文提问时推理能力会不会提升

### 基本示例 | Basic Example

...

### 缺陷 | Drawbacks

....

### 未解决问题 | Unresolved questions

.

**Comment by LDLINGLINGLING** [comment]
我个人任务能力应该有一定提升
