### ISSUE TITLE
💡 [REQUEST] - minicpm是否可以用来做目标检测任务呢？

### ISSUE THREAD

**Issue by xyw1** [OpenBMB/MiniCPM-V#323]
### 摘要 | Summary

minicpm是否可以用来做目标检测任务呢？
图像数据标注为目标的坐标和标签

### 基本示例 | Basic Example

图像数据标注为目标的坐标和标签

### 缺陷 | Drawbacks

未知

**Comment by LDLINGLINGLING** [comment]
目前minicpmv的预训练中这一类任务较少，可能需要补充大量数据

**Comment by daihuidai** [comment]
经过测试MiniCPM2.0 lora微调或仅微调对齐模块后的定位能力很差，能简单识别，但是定位偏差很大。没有做过全量微调测试

**Comment by LDLINGLINGLING** [comment]
经过用于以及我方多模态同学测试，训练后，2.5版本定位能力不错

**Comment by qyc-98** [comment]
您好我们更新了lora微调和加载参数的方式，模型代码也有更新，您可以重新尝试一下

**Comment by gjd2017** [comment]
> 经过用于以及我方多模态同学测试，训练后，2.5版本定位能力不错

有测评文档么？
