### ISSUE TITLE
关于3b模型在MME上精度结果不一致问题

### ISSUE THREAD

**Issue by sundayKK** [OpenBMB/MiniCPM-V#33]
我下载了3b模型跑了官方的MME测试集，使用prompt为官方的默认prompt，算出来的分数为1378.67，和给出的1452差别较大。请问是测试结果使用的prompt不一致导致的吗？

**Comment by Cuiunbo** [comment]
您好，请问方便给出您使用的具体代码吗，方便我们排查可能的问题，感觉可能是模型精度或者生成参数不同导致的
