### ISSUE TITLE
[BUG] <MiniCPMv2.5是否支持vllm 推理框架>

### ISSUE THREAD

**Issue by weiminw** [OpenBMB/MiniCPM-V#330]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
目前还在研发中，敬请期待

**Comment by iceflame89** [comment]
@weiminw  MiniCPM-Llama3-V 2.5  support vLLM now，see https://github.com/OpenBMB/MiniCPM-V?tab=readme-ov-file#vllm
