### ISSUE TITLE
LORA 微调效果不理想

### ISSUE THREAD

**Issue by lyc728** [OpenBMB/MiniCPM-V#333]
你好 我现在对比了swift框架下支持的这个模型，发现它微调后效果能达到这边支持的全量微调，而本代码支持的lora训练后推理效果不是很理想，请问这大概是什么导致的（全量微调效果还是很不错的）

**Comment by LDLINGLINGLING** [comment]
这可能是因为swift默认微调的是语言模型的所有q,k,v矩阵，官方代码仅微调q，k矩阵。另外可能lora的秩也更大等等，应该主要取决于训练模块的设置。

**Comment by Single430** [comment]
我这边也进行了lora微调，效果也是不理想，目前还没解决

**Comment by LDLINGLINGLING** [comment]
以下是swift的lora主要参数
r=8, target_modules={'k_proj', 'v_proj', 'q_proj'}, lora_alpha=32, lora_dropout=0.05
以下是官方lora代码主要参数：
lora_r: int = 64
lora_alpha: int = 64
lora_dropout: float = 0.05
lora_target_modules: str ="llm\..*layers\.\d+\.self_attn\.(q_proj|k_proj)" 
另外官方代码lora训练额外会训练resample和llm.embedding.

以上这些是我所看到的区别

**Comment by LDLINGLINGLING** [comment]
能否说一下怎么进行评价效果不理想的

**Comment by Single430** [comment]
> 能否说一下怎么进行评价效果不理想的

我是根据微调数据来说的，知识没有注入到模型中，微调前后对新知识的回答变化不大

**Comment by LDLINGLINGLING** [comment]
确定lora正常加载了吧，包括图像和llm的lora，另外evalloss最终多少

**Comment by Single430** [comment]
> 确定lora正常加载了吧，包括图像和llm的lora，另外evalloss最终多少

有正常加载，昨天重新调整lr=1e-4，效果有改善

**Comment by lyc728** [comment]
感觉还是这里的问题lora_target_modules 其它参数应该没有对模型有太大的影响

**Comment by qyc-98** [comment]
您好 我们更新了lora的微调方式，可以重新尝试一下

**Comment by qyc-98** [comment]
这次更新主要是针对lora里modules_to_save来改进，加载的方式以及模型huggingface源代码都有改变，可以更新一下再试试

**Comment by lyc728** [comment]
更新了最新的代码和huggiface代码 现在会报错了 你们有测试过吗？
<img width="755" alt="企业微信截图_17210273195621" src="https://github.com/user-attachments/assets/a68a9a20-0b7c-4e38-a6ac-d4eb8ffa85ae">

**Comment by qyc-98** [comment]
您好 我这边尝试了是可以正常训练的，
![image](https://github.com/user-attachments/assets/9b7f5294-20a5-4b2c-a299-278d068b3f36)
这一步你执行了吗？
![image](https://github.com/user-attachments/assets/aedc2cba-3795-4689-9280-a56999dfe20d)

**Comment by lyc728** [comment]
执行了  配置中这个是--tune_vision true 打开的

**Comment by KaidiKang** [comment]
我也遇到了一样的问题, 在用swift进行lora微调时如果设置--lora_target_modules All也会报错, default就可以正常训练. 是视觉模块的问题吗

参考: --lora_target_modules: 指定lora模块, 默认为['DEFAULT']. 如果lora_target_modules传入'DEFAULT' or 'AUTO', 则根据model_type查找MODEL_MAPPING中的lora_target_modules(默认指定为qkv). 如果传入'ALL', 则将所有的Linear层(不含head)指定为lora模块. 如果传入'EMBEDDING', 则Embedding层指定为lora模块. 如果内存允许, 建议设置成’ALL’.

**Comment by SHIMURA0** [comment]
> 更新了最新的代码和huggiface代码 现在会报错了 你们有测试过吗？ <img alt="企业微信截图_17210273195621" width="755" src="https://private-user-images.githubusercontent.com/88084847/348623037-a68a9a20-0b7c-4e38-a6ac-d4eb8ffa85ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjAwNjgsIm5iZiI6MTcyMTExOTc2OCwicGF0aCI6Ii84ODA4NDg0Ny8zNDg2MjMwMzctYTY4YTlhMjAtMGI3Yy00ZTM4LWE2YWMtZDRlYjhmZmE4NWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA4NDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YzA2YmVmZWNlYTUzMGUyOTlhMzU2YmU0MjFiNDQ5YTU3ODRlZTRjMzlmY2MxOTE2YzgwMzZjNzNjYTMwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1OjFdpdw3qDp0XudlU0F-gHgtHsILdxFN8OuLQCtg1I">

对的，同样的bug

**Comment by qyc-98** [comment]
您好 针对这个问题 我们更新了代码，应该已经修复了这个问题 请重新尝试一下

**Comment by lileilai** [comment]
> 你好 我现在对比了swift框架下支持的这个模型，发现它微调后效果能达到这边支持的全量微调，而本代码支持的lora训练后推理效果不是很理想，请问这大概是什么导致的（全量微调效果还是很不错的）

请问当前仓库支持的全量微调在你的数据下效果正常吗？以及Loss下降的情况正常吗？，我按照bs=8,  lr=1e-6的参数设定，deespeed=stage3、全量参数微调；Loss情况如下，请问这正常吗？



@qyc-98 @lyc728

**Comment by qyc-98** [comment]
貌似其他issue里反应的是全量微调效果是可以的，然后针对lora，我们修复了一个问题：我们最后的保存除了问题，你可以试试中间checkpoint的保存结果 ，最后那个保存没有把vpm resampler embed tokens这些权重更新完的模块保存下来
