### ISSUE TITLE
CPMV2.0使用zero3全量微调依然报错

### ISSUE THREAD

**Issue by daihuidai** [OpenBMB/MiniCPM-V#335]
下载hugging face上最新的模型以及仓库最新的代码，使用zero3配置文件全量微调MiniCPMV2.0报错，设备为一个节点两张卡，错误如下图：
![image](https://github.com/user-attachments/assets/6bb52594-8b88-4c27-ae14-5d41e6fcc5f1)

同样的数据使用finetune_lora.sh可以正常微调。

### 运行环境 | Environment

```Markdown
transformers              4.40.0
```

**Comment by qyc-98** [comment]
这个是因为vision transformer的加载使用的timm，需要您这边自己改一下vision transformer的源代码，我的理解是把关于self.pos_embed的操作参考我们resampler的操作 试一下，顺便提一下
您可以自己尝试一下 把vision transformer改一下，把里面和初始化相关的操作注释掉，这样的话可以使用zero3+bf16

**Comment by qyc-98** [comment]
我建议你在zero2 的shi后修改，因为zero3下所有参数没有被调用时都是空的

**Comment by daihuidai** [comment]
@qyc-98 放弃了，尝试修改了半天也不行

**Comment by DwanZhang-AI** [comment]
Same problem
