### ISSUE TITLE
我可以看一下你们用vs code debugger时运行 finetune_lora.sh的lauch.json嘛？

### ISSUE THREAD

**Issue by XuanRen4470** [OpenBMB/MiniCPM-V#336]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我总是无法把模型load到gpu上，我不知道是否和lauch.json 的setup有关。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Cuiunbo** [comment]
您好，希望我的回复没有太晚，我们并未使用vs code debugger来运行过该脚本， 请可以试用其他的环境运行该框架～ 如后续遇到更多问题也欢迎讨论。
