### ISSUE TITLE
💡 [REQUEST] - 大佬们可不可以更新一下微信社区二维码

### ISSUE THREAD

**Issue by hankerbiao** [OpenBMB/MiniCPM-V#337]
### 摘要 | Summary

大佬们可不可以更新一下微信社区二维码

### 基本示例 | Basic Example

大佬们可不可以更新一下微信社区二维码

### 缺陷 | Drawbacks

大佬们可不可以更新一下微信社区二维码

**Comment by qyc-98** [comment]
![20240718-215813](https://github.com/user-attachments/assets/b7f344d4-c112-47c1-b736-e135aabdc6ce)
