### ISSUE TITLE
[BUG] <title>8*A100（80G）lora训练为啥会OOM，每次50步的时候oom

### ISSUE THREAD

**Issue by lvjianxin** [OpenBMB/MiniCPM-V#338]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

CUDA_VISIBLE_DEVICES 0,1,2,3,4,5,6,7 \
swift sft \
    --model_type minicpm-v-v2_5-chat \
    --model_id_or_path "/mnt/workspace/pre_train_model/openbmb/MiniCPM-Llama3-V-2_5" \
    --dataset "/mnt/workspace/app_source/data/last_1000_records.json" \
    --output_dir "/mnt/workspace/app_source/output" \
    --max_length 1024  \
    --batch_size 1 \
    --gradient_accumulation_steps 8 \
    --resume_only_model True \
    --sft_type 'lora'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB. GPU 6 has a total capacty of 79.15 GiB of which 15.31 MiB is free. Process 122606 has 79.12 GiB memory in use. Of the allocated memory 77.49 GiB is allocated by PyTorch, and 683.81 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by qyc-98** [comment]
您可以打印一下输入的shape是不是第50步的时候 输入比较大

**Comment by LDLINGLINGLING** [comment]
swift的eval有问题，在训练中作验证时导致非常大的显存增加，此时应该避免eval，将eval_steps调整到一个非常大的值
