### ISSUE TITLE
是否支持批量推理?

### ISSUE THREAD

**Issue by Zhouziyi828** [OpenBMB/MiniCPM-V#339]
看到了支持单个图片调用模型进行推理,是否支持批量的推理?

**Comment by LDLINGLINGLING** [comment]
可以使用LMdeploy,代码如下
from lmdeploy import pipeline, TurbomindEngineConfig
from lmdeploy.vl import load_image

# 可将MiniCPM-Llama3-V 2.5换成本地路径
#session_len=2048 代表上下文长度
#tp=8 代表使用显卡数，必须是2**n，比如1，2，4，8
pipe = pipeline('MiniCPM-Llama3-V 2.5',
                backend_config=TurbomindEngineConfig(session_len=2048,tp=8),)

# 图片的url或者本地路径
image_urls=[
    "/root/ld/ld_project/MiniCPM-V/assets/minicpmv2-cases.png",
    "/root/ld/ld_project/MiniCPM-V/assets/llavabench_compare_phi3.png",
    "/root/ld/ld_project/MiniCPM-V/assets/MiniCPM-Llama3-V-2.5-peformance.png",
    "/root/ld/ld_project/MiniCPM-V/assets/zhihu.webp",
    "/root/ld/ld_project/MiniCPM-V/assets/thunlp.png"
]
prompts = [('describe this image', load_image(img_url)) for img_url in image_urls]
response = pipe(prompts)
print([i.text for i in response])

**Comment by qyc-98** [comment]
最新的minicpmv-llama3模型已经可以batch inference了
![image](https://github.com/user-attachments/assets/2106114e-8415-4a9b-ab30-044867ba3a25)

**Comment by whyiug** [comment]
> 最新的minicpmv-llama3模型已经可以batch inference了 ![image](https://private-user-images.githubusercontent.com/38046403/350181888-2106114e-8415-4a9b-ab30-044867ba3a25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDY3MzYsIm5iZiI6MTcyMTY0NjQzNiwicGF0aCI6Ii8zODA0NjQwMy8zNTAxODE4ODgtMjEwNjExNGUtODQxNS00YTliLWFiMzAtMDQ0ODY3YmEzYTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDExMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MDQ3NGNlOTg4YjJhY2M5YTNiOGI5NDRlNDZiODA0MDkzMmM2Nzc1ZmQwZDM4MWVhMzIzZTA4OWI3Y2VjNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4CJ8FPwR5yt19m2ccIGXi6V273HGan4RDzocgygwH8I)

这段代码是报错的。用的最新的model commit 3b6aeff3850ce9d5087751911e4771c78004b2b3

**Comment by dengruoqing** [comment]
[MiniCPM-V](https://github.com/OpenBMB/MiniCPM-V)

**Comment by dengruoqing** [comment]
[MiniCPM-V](https://github.com/OpenBMB/MiniCPM-V)
请求该项目支持图片以url输入吗？

**Comment by dengruoqing** [comment]
[MiniCPM-V](https://github.com/OpenBMB/MiniCPM-V)
请问该项目支持图片以url输入吗？

**Comment by 1223243** [comment]
请问一下，有在开源微信社区里的吗

**Comment by LDLINGLINGLING** [comment]
![image](https://github.com/user-attachments/assets/ca16b012-3010-4a7e-8430-4ba0528e4578)
