### ISSUE TITLE
请问MiniCPM-V能使用类似stream为True的参数来实现流式生成吗？

### ISSUE THREAD

**Issue by huu3301** [OpenBMB/MiniCPM-V#34]
请问MiniCPM-V如何使用流式的方式生成？像是使用transformers的streamer之类的。

另外，好像model.chat输入temperature或top_p是不生效的，看代码是已经写死了。
![image](https://github.com/OpenBMB/OmniLMM/assets/44219645/c7884a8d-8c6c-4657-8dee-f8c5fd38cf20)

**Comment by iceflame89** [comment]
感谢关注，我们近期会支持流式输出

**Comment by Cuiunbo** [comment]
Add this to future plan

**Comment by chuangzhidan** [comment]
> 感谢关注，我们近期会支持流式输出

现在可以了吗
