### ISSUE TITLE
有兴趣可以加一下多模态群，大家一起交流多模态技术实战中遇到的问题

### ISSUE THREAD

**Issue by feihuamantian** [OpenBMB/MiniCPM-V#340]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

如果二维码失效，可以加微信拉入群：yx116169
![20240716-114139](https://github.com/user-attachments/assets/cd206e6d-42ce-4b41-9c67-81d6bb2885cb)

### 期望行为 | Expected Behavior

0

### 运行环境 | Environment

```Markdown
0
```

### 备注 | Anything else?

0

**Comment by qyc-98** [comment]
Thank you
