### ISSUE TITLE
Can MiniCPM-V trained with text-only instructions?

### ISSUE THREAD

**Issue by simplelifetime** [OpenBMB/MiniCPM-V#344]
Thanks for your great work! I notice that the fine-tune document only shows the required format for vision-language instructions. Does the model support training with both vision-language examples and language-only examples?

**Comment by LDLINGLINGLING** [comment]
hello，I recently completed a demo-level fine-tuning of plain text and mixed-modal fine-tuning. I will send you the link after I upload the code.

**Comment by simplelifetime** [comment]
Thanks very much!

**Comment by LDLINGLINGLING** [comment]
Hi，please use follow branch code：https://github.com/LDLINGLINGLING/MiniCPM-V/tree/ft_language
and you can follow the Tutorial：https://modelbest.feishu.cn/docx/I18Fd2HLRoESOYxuyc6cUZqvnhd?from=from_copylink ，any problem you can tell me

**Comment by simplelifetime** [comment]
Appreciate it! I will try it later.

**Comment by LDLINGLINGLING** [comment]
if the code work，please tell me, I will close the issue.

**Comment by univa-JASON** [comment]
i tried to follow it, but i got this error
```
[93,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [350,0,0], thread: [94,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [350,0,0], thread: [95,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
...
...
```
can you help me?

**Comment by LDLINGLINGLING** [comment]
Have you replaced the file and used the branch of ft_language?

**Comment by LDLINGLINGLING** [comment]
This issue has been completed. The above problems have not occurred. I have no problems running it locally. Please first make sure whether you strictly follow the tutorial.
