### ISSUE TITLE
RuntimeError: Expected index [1728, 4096] to be smaller than self [2048, 4096] apart from dimension 0 and to be smal ler size than src [864, 4096]

### ISSUE THREAD

**Issue by aoji0606** [OpenBMB/MiniCPM-V#345]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

sft时，训练到某张图时报错。
modeling_minicpmv.py
in get_vllm_embedding
    cur_vllm_emb.scatter_(0, image_indices.view(-1, 1).repeat(1, cur_vllm_emb.shape[-1]),                           
RuntimeError: Expected index [1728, 4096] to be smaller than self [2048, 4096] apart from dimension 0 and to be smal
ler size than src [864, 4096]

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by qyc-98** [comment]
我们刚刚更新了代码 可以重新试一试

**Comment by Liu0329** [comment]
@qyc-98 I still have this problem with max_slice_nums=1. Is that because the tokens are too many ? Can you give an explanation about what the code does here, thanks !
![企业微信截图_17248992561728](https://github.com/user-attachments/assets/9cf302af-e139-4851-aa43-ee0b9f6a8bf8)

**Comment by laoShuaiGe** [comment]
@Liu0329 I'm encountering the same issue.

**Comment by hangzh2012** [comment]
Install DeepSpeed from source. Don't use "pip install deepspeed" directly.

**Comment by expection1985** [comment]
mark
