### ISSUE TITLE
TypeError: MiniCPMV.chat() missing 2 required positional arguments: 'images_list' and 'msgs_list'

### ISSUE THREAD

**Issue by wailokkwok** [OpenBMB/MiniCPM-V#351]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

from peft import AutoPeftModelForCausalLM
import torch
from chat import MiniCPMVChat, img2base64
import json
from transformers import AutoTokenizer
from PIL import Image
import os
import re

path_to_adapter = "/mnt/second/data/output_minicpmv2_lora/checkpoint-400"
tokenizer = AutoTokenizer.from_pretrained(path_to_adapter, trust_remote_code=True)
model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter,
    device_map="cuda:0",
    trust_remote_code=True
).eval()
vpm_resampler_embedtokens_weight = torch.load(f"{path_to_adapter}/vpm_resampler_embedtokens.pt")
model.load_state_dict(vpm_resampler_embedtokens_weight, strict=False)

img_lst = sorted(os.listdir('/home/matthew_kwok_tictag_io/minicpm/test_copy/image'))
total_samples = len(img_lst)
correct_predictions = 0

with open('/home/matthew_kwok_tictag_io/minicpm/test_copy/output.json') as f:
    json_data = json.load(f)

total_char = 0

for data in json_data:
    char_count = len(data['conversations'][1]['content'])
    total_char += char_count

total_samples = len(json_data)
correct_predictions = 0
correct_char = 0
correct_len = 0

for data in json_data:
    img_path = data['image']
    print(img_path)
    category_name = data['conversations'][1]['content']  # assuming the correct answer is in the second conversation
    
    # Remove leading zeros from the truth value
    category_name = category_name.lstrip('0')
    
    response = model.chat(
        image=Image.open(img_path).convert("RGB"),
        msgs_list=[
            {
                "role": "user",
                "content": f"what does the odometer reading on the bottom of the image show?"
            }
        ],
        tokenizer=tokenizer
    )
    # Extract the number from the response
    number_pattern = re.compile(r'\d+')
    match = number_pattern.search(response)
    if match:
        predicted_value = match.group()
        predicted_value = predicted_value.lstrip("0")
        if predicted_value == category_name:
            correct_predictions += 1

        if len(predicted_value) == len(category_name):
            correct_len += 1

        min_len = min(len(predicted_value), len(category_name))
        for i in range(min_len):
            if predicted_value[i] == category_name[i]:
                correct_char += 1
    else:
        print("No number found in the response.")

    # print('prediction')
    # print(predicted_value)
    # print('truth')
    # print(category_name)

accuracy = correct_predictions / total_samples * 100
print(f"Accuracy: {accuracy}%")

char_accuracy = correct_char/ total_char * 100 
print(f"Char Accuracy: {char_accuracy}%")

len_accuracy = correct_len/ total_samples * 100 
print(f"Len Accuracy: {len_accuracy}%")

this code was still working yesterday, but today it showed this error

TypeError: MiniCPMV.chat() missing 2 required positional arguments: 'images_list' and 'msgs_list'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by hszyq1234** [comment]
这是因为huggingface把模型代码更新了，modules/transformers_modules/openbmb/MiniCPM-Llama3-V-2_5/XXX/modeling_minicpmv.py里的chat函数的入参变了。你把这个文件替换成老的就行了。或者等github更新web_demo，重新给示例

**Comment by Labmem009** [comment]
> 这是因为huggingface把模型代码更新了，modules/transformers_modules/openbmb/MiniCPM-Llama3-V-2_5/XXX/modeling_minicpmv.py里的chat函数的入参变了。你把这个文件替换成老的就行了。或者等github更新web_demo，重新给示例

请问modeling_minicpmv.py这个文件要改成哪个老的版本？

**Comment by Labmem009** [comment]
> > 这是因为huggingface把模型代码更新了，modules/transformers_modules/openbmb/MiniCPM-Llama3-V-2_5/XXX/modeling_minicpmv.py里的chat函数的入参变了。你把这个文件替换成老的就行了。或者等github更新web_demo，重新给示例
> 
> 请问modeling_minicpmv.py这个文件要改成哪个老的版本？

找到了，一周前的版本和今天更新的版本都没这个images_list问题，就四天前的那个有问题正好我撞上了hhh
