### ISSUE TITLE
[BUG] 推理模型出现 IndexError: index is out of bounds for dimension with size 0

### ISSUE THREAD

**Issue by Uooga** [OpenBMB/MiniCPM-V#357]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

全量调参模型，测试的时候发现以下问题，
<img width="872" alt="image" src="https://github.com/user-attachments/assets/e5afefda-1537-4c3e-8aba-c40a5c7c984b">

之前在相同环境下可以成功测试相同的模型和数据集，现在测试也会报这个错误

测试代码
def load_model_full(model_path, tokenizer_path, device_map='cuda'):
    #global model_path, tokenizer_path
    #device_map = 'cuda'
    model = AutoModel.from_pretrained(model_path, trust_remote_code=True, torch_dtype=torch.bfloat16)
    model = model.to(device=device_map, dtype=torch.float16)
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, trust_remote_code=True)
    return model, tokenizer

def inference_single(model, tokenizer, image, question, label, line, outfile):
    image = Image.open(image).convert('RGB')
    msgs = [{'role': 'user', 'content': question}]
    bt = time.time()
    answer, context, _ = model.chat(
        image=image,
        msgs=msgs,
        context=None,
        tokenizer=tokenizer,
        sampling=True
    )

### 运行环境 | Environment

```Markdown
- OS: Linux 
- Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
- Transformers: 4.42.4
- PyTorch: 2.3.1+cu121
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

**Comment by EchizenMike** [comment]
Transformers: 4.42.4版本太高了，改成4.36.0就好了。
