### ISSUE TITLE
💡 [REQUEST] - <现在MiniCPM-V能否支持纯文本的微调呢，没有image token>

### ISSUE THREAD

**Issue by NieyYuanbi** [OpenBMB/MiniCPM-V#358]
### 摘要 | Summary

希望能够支持纯文本的微调

### 基本示例 | Basic Example

[
{ 
      "id": "0",
      "conversations": [
            {
              'role': 'user', 
              'content': 'How's the weather?'
            }, 
            {
                'role': 'assistant', 
                'content': 'xxxx.'
            }, 
}
]

### 缺陷 | Drawbacks

no impact

**Comment by LDLINGLINGLING** [comment]
我最近完成了一个demo级的纯文本微调，以及混合模态微调，到时候发给链接给你吧

**Comment by NieyYuanbi** [comment]
非常感谢！

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月23日 15:26 |
| 收件人 | OpenBMB/MiniCPM-V ***@***.***> |
| 抄送人 | Nieyuanbi ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [OpenBMB/MiniCPM-V] 💡 [REQUEST] - <现在MiniCPM-V能否支持纯文本的微调呢，没有image token> (Issue #358) |

我最近完成了一个demo级的纯文本微调，以及混合模态微调，到时候发给链接给你吧

**Comment by LDLINGLINGLING** [comment]
https://github.com/LDLINGLINGLING/MiniCPM-V/tree/ft_language这个分支，用https://modelbest.feishu.cn/docx/I18Fd2HLRoESOYxuyc6cUZqvnhd?from=from_copylink这个教程，跑不起来跟我说，我本地是跑起来没有问题的，传文件的时候不知道传齐了没有

**Comment by NieyYuanbi** [comment]
非常感谢您！

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月24日 08:32 |
| 收件人 | OpenBMB/MiniCPM-V ***@***.***> |
| 抄送人 | Nieyuanbi ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [OpenBMB/MiniCPM-V] 💡 [REQUEST] - <现在MiniCPM-V能否支持纯文本的微调呢，没有image token> (Issue #358) |

https://github.com/LDLINGLINGLING/MiniCPM-V/tree/ft_language这个分支，用https://modelbest.feishu.cn/docx/I18Fd2HLRoESOYxuyc6cUZqvnhd?from=from_copylink这个教程，跑不起来跟我说，我本地是跑起来没有问题的，传文件的时候不知道传齐了没有

**Comment by LDLINGLINGLING** [comment]
跑起来了说一声，我关闭issue

**Comment by NieyYuanbi** [comment]
好的，我今晚跑一下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月24日 14:34 |
| 收件人 | OpenBMB/MiniCPM-V ***@***.***> |
| 抄送人 | Nieyuanbi ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [OpenBMB/MiniCPM-V] 💡 [REQUEST] - <现在MiniCPM-V能否支持纯文本的微调呢，没有image token> (Issue #358) |

跑起来了说一声，我关闭issue

**Comment by NieyYuanbi** [comment]
您好，问题已解决，您可以关闭issue了！
非常感谢您的工作！


| |
聂远碧
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月24日 14:34 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [OpenBMB/MiniCPM-V] 💡 [REQUEST] - <现在MiniCPM-V能否支持纯文本的微调呢，没有image token> (Issue #358) |

跑起来了说一声，我关闭issue

**Comment by resi1ience** [comment]
请问MiniCPM-V 2.6有对应的纯文本微调方法嘛
