### ISSUE TITLE
请问是否支持转换为TensorRT格式

### ISSUE THREAD

**Issue by hhhhrc** [OpenBMB/MiniCPM-V#360]
### 摘要 | Summary

有无适配计划呢，例如tensorrt_llm支持

### 基本示例 | Basic Example

基本实例

### 缺陷 | Drawbacks

1

**Comment by iceflame89** [comment]
你好，由于人力有限，暂无计划支持TensorRT～

**Comment by hhhhrc** [comment]
> 你好，由于人力有限，暂无计划支持TensorRT～

感谢回复~ 
我正在使用tensorrt_llm，vit已经成功转换，但是在传入llm时发现只能输入input_ids,不支持输入input_embeds，想问一下可否能用prompt_table的方式传递vit信息，大佬有什么建议吗

**Comment by Single430** [comment]
> > 你好，由于人力有限，暂无计划支持TensorRT～
> 
> 感谢回复~ 我正在使用tensorrt_llm，vit已经成功转换，但是在传入llm时发现只能输入input_ids,不支持输入input_embeds，想问一下可否能用prompt_table的方式传递vit信息，大佬有什么建议吗

你好，不约而同，现在我也遇到了这个问题（llm时发现只能输入input_ids），请问现在你解决问题了吗？
