### ISSUE TITLE
[BUG] <title>回复出现死循环的现象

### ISSUE THREAD

**Issue by lcystudy** [OpenBMB/MiniCPM-V#364]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![问题](https://github.com/user-attachments/assets/ad6d8498-02ad-401c-b096-a0e5676de38f)
![问题2](https://github.com/user-attachments/assets/97635995-2a3f-414d-a2f7-5bc1c7077009)
在对图片进行提问时，第一次提问没有问题，后续回复进入到死循环，而且循环词都是奖品，这个问题在之前也遇到过，如下图：
![问题3](https://github.com/user-attachments/assets/910986d3-e3cb-4526-aeec-79a55ab41b97)
该问题导致没法对图片进行多轮的提问。

### 期望行为 | Expected Behavior

正确根据提问进行合理的回答。

### 运行环境 | Environment

```Markdown
- OS:HperOS 1.0.8.0
- Android 14
- Redmi K60
- CPU: Qualcomm Snapdragon 8+
```

**Comment by renjingneng** [comment]
有个参数是重复惩罚 可以试着调大一点

**Comment by lcystudy** [comment]
在终端调用的时候可以调参，但是在手机上使用你们的demo的时候，直接对话的时候怎么设置这些参数呀

**Comment by renjingneng** [comment]
> 在终端调用的时候可以调参，但是在手机上使用你们的demo的时候，直接对话的时候怎么设置这些参数呀

我理解的这只是个demo
用的话得另外开发了

**Comment by lcystudy** [comment]
好的好的，感谢回复
