### ISSUE TITLE
The number of the data samples during the PT and SFT?

### ISSUE THREAD

**Issue by shufangxun** [OpenBMB/MiniCPM-V#365]
Hello, can you provide the number of the data samples during the PT and SFT?

**Comment by Haoye17** [comment]
Hello @shufangxun,
Thank you for your interest in our work! 
Regarding the issue you mentioned, we have released a [technical report](https://github.com/OpenBMB/MiniCPM-V/blob/main/docs/MiniCPM_Llama3_V_25_technical_report.pdf) that provides detailed information. 
We hope this helps, and please feel free to reach out if you have any further questions ~
