### ISSUE TITLE
💡 [REQUEST] - <title>  MiniCPM-Llama3-V-2_5 量化成gguf 能在python里调用吗  

### ISSUE THREAD

**Issue by y-x-x123** [OpenBMB/MiniCPM-V#367]
### 实现PR | Implementation PR

比如支持llama-cpp-python吗

### 摘要 | Summary

-

### 基本示例 | Basic Example

-

### 缺陷 | Drawbacks

-

### 未解决问题 | Unresolved questions

-

**Comment by LDLINGLINGLING** [comment]
可以的，看这个教程的llama.cpp部署，使用python调用llama.cpp，或者llama.cpp起一个server服务并且让python调用llamac p p接口

**Comment by y-x-x123** [comment]
> 可以的，看这个教程的llama.cpp部署，使用python调用llama.cpp，或者llama.cpp起一个server服务并且让python调用llamac p p接口

您好，可以提供一下链接吗  谢谢
