### ISSUE TITLE
Is this able to do grounding like CogVLM?

### ISSUE THREAD

**Issue by husnoo** [OpenBMB/MiniCPM-V#370]
For example, "Give the position of the red box in the image." -> [x1,x2,y1,y2]

**Comment by LDLINGLINGLING** [comment]
This feature requires a small amount of data fine-tuning. For specific operations, please refer to this  tutorial  https://modelbest.feishu.cn/wiki/HLRiwNgKEic6cckGyGucFvxQnJw?from=from_copylink
