### ISSUE TITLE
使用beam search后能否返回多个回应？

### ISSUE THREAD

**Issue by lingyu123-su** [OpenBMB/MiniCPM-V#371]
开发者您好，我在使用最新的V2.5模型时发现，chat方法只能调节num_beam和重复惩罚，无法调节返回的序列数量；请问这样设计是基于什么样的考虑？返回多个回应是否可行呢？
非常感谢，非常优秀的工作！祝工作生活顺利。

**Comment by LDLINGLINGLING** [comment]
其实调节了num_beam就是已经在调节返回的序列数量了，解码过程中一直保持了多个beam_search中最好的序列，只不过最终给用户的的是最好的那个而已。这是由于对于一般应用，也不回需要多个回答，特别是小概率下这几个回复可能有矛盾的地方。
