### ISSUE TITLE
[BUG] Running chat.py with the finetuned model

### ISSUE THREAD

**Issue by torhada** [OpenBMB/MiniCPM-V#372]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I encounter an error when running chat.py with the finetuned model.

【error】
Traceback (most recent call last):
  File "/home/name/llama3/chat.py", line 210, in <module>
    answer = chat_model.chat(input)
  File "/home/name/llama3/chat.py", line 197, in chat
    return self.model.chat(input)
  File "/home/name/llama3/chat.py", line 153, in chat
    answer, context, _ = self.model.chat(
  File "/home/name/.cache/huggingface/modules/transformers_modules/openbmb/MiniCPM-Llama3-V-2_5/287e3f85192a7c4acf2564fc6bda0637439a9d78/modeling_minicpmv.py", line 324, in chat
    prompt = processor.tokenizer.apply_chat_template(copy_msgs, tokenize=False, add_generation_prompt=True)
AttributeError: 'MiniCPMVTokenizerFast' object has no attribute 'tokenizer'. Did you mean: '_tokenizer'?

【code】chat.py
model_path = '/home/name/llama3/finetune/output/output_minicpmv2' ← finetuned model path
chat_model = MiniCPMVChat(model_path)

### 复现方法 | Steps To Reproduce

Run finetune_ds.sh
Pass the path of the finetuned model to chat.py and execute
An error occurs

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.10.14
- Transformers:4.41.2
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by zysNLP** [comment]
Hi, can you provide your all code related or continue add by my these codes: 

from peft import PeftModel
from transformers import AutoModel

model_type = "path to your origin model paras downloaded"  # or openbmb/MiniCPM-V-2
path_to_adapter = "path/to/output/output_minicpmv2_lora/checkpoint-2000/"  # finetuned by lora

model = AutoModel.from_pretrained(
    model_type,
    trust_remote_code=True
)

lora_model = PeftModel.from_pretrained(
    model,
    path_to_adapter,
    device_map="auto",
    trust_remote_code=True
).eval().cuda()

I have a similar question. The code here on the github website seems to only write the step of loading the model. May I ask how to continue reading data for chat or prediction after loading the model, especially the lora model?
我有相似的疑问，github官网这里的代码似乎只写到了加载模型这一步，请问加载完模型后，特别是lora模型后怎么继续读取数据进行chat或者预测呢？@MrChen314

**Comment by zysNLP** [comment]
@iceflame89 你好，可以回答我的留言吗。。。感谢！

**Comment by liujiawei2333** [comment]
> @torhada[您需要将 '/home/name/llama3/finetune/output/output_minicpmv2' 中的模型代码更新为与 hf 上的openbmb/MiniCPM-Llama3-V-2_5](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5) 相同的最新版本 。

我也有同样的问题，并且按照您说的方案并不能解决，似乎是这次代码更新导致的，之前使用时没有这个问题

**Comment by liujiawei2333** [comment]
> @torhada You need to update the model code in '/home/name/llama3/finetune/output/output_minicpmv2' to the latest version same as [openbmb/MiniCPM-Llama3-V-2_5](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5) on hf.

貌似微调后保存的checkpoint中的代码没有更新为新的代码，还是老的，导致冲突

**Comment by zysNLP** [comment]
![image](https://github.com/user-attachments/assets/537b0350-dee9-42bc-9ecb-0dd42910071b)
@liujiawei2333 我这边跑完是这种文件，应该是拿一周前的版本跑的，不行你可以回滚代码试试

**Comment by zysNLP** [comment]
推理方式我没有用官网的chat.py，而是在我上一个回答中的：
lora_model = PeftModel.from_pretrained(
    model,
    path_to_adapter,
    device_map="auto",
    trust_remote_code=True
).eval().cuda()
后面加入huggingface model cards中的构造方式推理是没问题的
