### ISSUE TITLE
[Ollama] Ollama model does have significantly lower quality in answering than online demo

### ISSUE THREAD

**Issue by ChristianWeyer** [OpenBMB/MiniCPM-V#375]
Referring to https://github.com/OpenBMB/ollama/issues/3#issuecomment-2260209553

:-)

Thanks @tc-mb!

**Comment by hvico** [comment]
Hi! Same here, tried to reproduce the inference of the online demo using Llama.cpp fork, quality is much worse (using the same params). As Ollama is Llama.cpp based, I would think this two problems are the same. Thanks!

**Comment by tc-mb** [comment]
@ChristianWeyer @hvico

**Comment by ChristianWeyer** [comment]
Where can we find the updated stuff @tc-mb @Cuiunbo ?

**Comment by ChristianWeyer** [comment]
Where can we find the updated stuff @tc-mb @Cuiunbo ?

**Comment by tc-mb** [comment]
> Where can we find the updated stuff @tc-mb @Cuiunbo ?

I have modified it, and you should be able to get good enough results with minicpmv2.5. 
I am sorry that I did not inform you in time even though I made the modification.

**Comment by ChristianWeyer** [comment]
> > Where can we find the updated stuff @tc-mb @Cuiunbo ?
> 
> I have modified it, and you should be able to get good enough results with minicpmv2.5. I am sorry that I did not inform you in time even though I made the modification.

What has changed? How does the setup look like in the  meantime? 🙂
Which tools and which model file?

I still like to use Ollama.
