### ISSUE TITLE
💡 [REQUEST] - <后续有计划 Release Android 工程的代码吗>

### ISSUE THREAD

**Issue by cloudyuyuyu** [OpenBMB/MiniCPM-V#376]
### 起始日期 | Start Date

08/01/2024

### 实现PR | Implementation PR

无

### 相关Issues | Reference Issues

无

### 摘要 | Summary

无

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

### 未解决问题 | Unresolved questions

无

**Comment by tc-mb** [comment]
短期内没有。
