### ISSUE TITLE
How to improve the inference speed for MiniCPM-V 2.0?

### ISSUE THREAD

**Issue by gaolongxi** [OpenBMB/MiniCPM-V#377]
Hi,
I am currently working with the MiniCPM-V-2.0 model and would like to improve the inference speed by running it locally. Could you please provide information on where I can download the pre-trained model weights to run the model offline?
I found the hugging face repo but I am not sure whether there is model weight files to download and how to use it.
Thank you.

**Comment by LDLINGLINGLING** [comment]
hi，There is a tutorial on using vllm to infer MiniCPMV2.0 on our github. You can check it out.
