### ISSUE TITLE
8张32GB V100 带不动全量微调

### ISSUE THREAD

**Issue by SHIMURA0** [OpenBMB/MiniCPM-V#380]
8张32GB V100的服务器在miniCPM-V2.5全量微调的时候出现CUDA out of memory，但是理论上应该带的动吧？求教有解决方法吗

**Comment by LDLINGLINGLING** [comment]
使用zero3 加上offload应该可以吧。

**Comment by SHIMURA0** [comment]
在shell脚本中改用zero3并且修改offload 为cpu直接报错attribute error: "DeepSpeedCPUAdam" object has no attribute "ds_opt_adam"

**Comment by LDLINGLINGLING** [comment]
没记错的话这个是deepspeed版本的问题，去官方下载吧。

**Comment by SHIMURA0** [comment]
deepspeed 版本要求多少啊，在requirents.txt 里面没看到

**Comment by LDLINGLINGLING** [comment]
我的是0.14.2，去官方下载吧，我之前用pip install deepspeed也出现了这个问题
