### ISSUE TITLE
MiniCPM-V2.6是否可以用来做目标检测任务呢？

### ISSUE THREAD

**Issue by tgyy1995** [OpenBMB/MiniCPM-V#384]

**Comment by LDLINGLINGLING** [comment]
应该可以，我2.5版本做了一个教程https://modelbest.feishu.cn/wiki/HLRiwNgKEic6cckGyGucFvxQnJw?from=from_copylink，你可以先看，如果后续有时间我会补上2.6版本的

**Comment by PredyDaddy** [comment]
> 应该可以，我2.5版本做了一个教程[https://modelbest.feishu.cn/wiki/HLRiwNgKEic6cckGyGucFvxQnJw?from=from_copylink，你可以先看，如果后续有时间我会补上2.6版本的](https://modelbest.feishu.cn/wiki/HLRiwNgKEic6cckGyGucFvxQnJw?from=from_copylink%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E5%85%88%E7%9C%8B%EF%BC%8C%E5%A6%82%E6%9E%9C%E5%90%8E%E7%BB%AD%E6%9C%89%E6%97%B6%E9%97%B4%E6%88%91%E4%BC%9A%E8%A1%A5%E4%B8%8A2.6%E7%89%88%E6%9C%AC%E7%9A%84)

请问按照您这种方式微调之后是否会出现灾难性的遗忘呢？

**Comment by LDLINGLINGLING** [comment]
你好，只要是微调就一定存在遗忘，我并没有做实验对原来的影响有多大

**Comment by PredyDaddy** [comment]
> 你好，只要是微调就一定存在遗忘，我并没有做实验对原来的影响有多大

请问2.6是否可以按照同样的方式进行训练呢？

**Comment by LDLINGLINGLING** [comment]
可以，但是可能需要改代码

**Comment by yhpwsid** [comment]
> 可以，但是可能需要改代码

请问最近有计划补充这个吗
