### ISSUE TITLE
请问MiniCPM-V 2.6 是否支持多图的finetune？

### ISSUE THREAD

**Issue by Sisi0518** [OpenBMB/MiniCPM-V#386]
请问MiniCPM-V 2.6 是否支持多图的finetune？什么时候可以开放对多图训练的代码呢？

**Comment by LDLINGLINGLING** [comment]
应该以后会支持，请关注我们的github

**Comment by qyc-98** [comment]
这个近期会支持的

**Comment by Mihaiii** [comment]
@Cuiunbo could you please offer more info? How to lora finetune on multiple images per sample?

**Comment by Mihaiii** [comment]
We have info on how to lora finetune on V2.5, but in V2.5 we can't add multiple images per samples. In V2.6 we can (which is awesome!).
