### ISSUE TITLE
💡 [REQUEST] - <where is vllm infer demo for minicpmv 2_6?>

### ISSUE THREAD

**Issue by PancakeAwesome** [OpenBMB/MiniCPM-V#387]
### 摘要 | Summary

I need use vllm accelerate minicpm v2_6, please add some python sdk samples which used vllm of multi-gpu. Thank you, developers!

### 基本示例 | Basic Example

vllm multi-card infer python sdk

### 缺陷 | Drawbacks

no vllm multi-card infer python sdk demos

**Comment by seasoncool** [comment]
+1
