### ISSUE TITLE
Question about details on the training procedure and data

### ISSUE THREAD

**Issue by floschne** [OpenBMB/MiniCPM-V#39]
Hi, and thanks for this fantastic work!

I am using your models for a scientific project, which requires details about the training procedure and training data. I haven't found a paper or a technical report specifically for this work. Did I miss something? 

Is the training procedure and data the same as in https://arxiv.org/pdf/2308.12038.pdf ? 

Can you please share some details or a technical report?

Thanks :-)

**Comment by iceflame89** [comment]
We will release technical report in weeks.
