### ISSUE TITLE
💡 [REQUEST] - How to get internal embeddings for downstream retrieval tasks like ColPali

### ISSUE THREAD

**Issue by VoVAllen** [OpenBMB/MiniCPM-V#391]
### 摘要 | Summary

https://github.com/illuin-tech/colpali

Recently Colbert+PaliGemma showed big improvement on pdf file retrieval by using multimodal model instead of OCR+LLM. Would be nice if MiniCPM can support Colbert-like usage for downstream retrieval tasks. Or how can I finetune MiniCPM like ColPali?

### 基本示例 | Basic Example

NA

### 缺陷 | Drawbacks

NA

**Comment by VoVAllen** [comment]
@bokesyo Do you have any plan for the multi vector representations? In Colpali report, multi vector showed much better performance than single vector

**Comment by VoVAllen** [comment]
@bokesyo Also curious are you affiliated to OpenBMB? I saw the embedding model is under a different organization.

**Comment by bokesyo** [comment]
> @bokesyo Do you have any plan for the multi vector representations? In Colpali report, multi vector showed much better performance than single vector

Not yet, currently we only use one vector to represent the page and easier to implement. 😂

**Comment by bokesyo** [comment]
> @bokesyo Also curious are you affiliated to OpenBMB? I saw the embedding model is under a different organization.

Yes, but we think this is visual embedding technique is experimental and a preview version, so we did not put it on OpenBMB. When the quantitative evaluation result is ready and final model with all training data is ready, we will release on OpenBMB.

**Comment by lijiaoyang** [comment]
> our training framework github repo
This link is 404, can you tell me the correct link?
https://github.com/RhapsodyAILab/minicpm-visual-embedding-v0

**Comment by LDLINGLINGLING** [comment]
https://modelbest.feishu.cn/wiki/NdEjwo0hxilCIikN6RycOKp0nYf?from=from_copylink
@VoVAllen hi，In this tutorial, a multi-vector minicpm-v representation is written.

**Comment by bokesyo** [comment]
> > our training framework github repo
> > This link is 404, can you tell me the correct link?
> > https://github.com/RhapsodyAILab/minicpm-visual-embedding-v0

Yes, check our new repo: https://github.com/RhapsodyAILab/MiniCPM-V-Embedding-v0
