### ISSUE TITLE
💡 [REQUEST] - MiniCPM-V-2_6对视频的理解是否包含字幕OCR、音频信息的使用

### ISSUE THREAD

**Issue by cnsky2016** [OpenBMB/MiniCPM-V#397]
### 起始日期 | Start Date

08/07、2024

### 摘要 | Summary

模型较少使用字幕OCR、音频信息

### 基本示例 | Basic Example

##请结合提供的视频及语音文本信息，总结视频内容
##语音文本信息：女生：我不是这个意思，我的意思是我们还没办婚礼呢。男生 ：哦，你的意思是我还欠你一场婚礼？

视频内容展示了两个人在室内环境中进行对话的场景。视频开头，一个穿着灰色毛衣和黑色裙子的女生坐在沙发上，旁边有一个戴眼镜的男生。女生似乎在解释什么，而男生则表现出困惑的表情。

随后的画面中，文字叠加显示了他们的对话内容。女生解释说：“我不是这个意思，我的意思是我们还没办婚礼呢。”男生回应道：“哦，你的意思是我还欠你一场婚礼？”这表明他们在讨论关于婚礼的事情。

接下来的画面中，女生显得有些不开心，她交叉双臂，看起来像是在表达不满或失望的情绪。而男生则继续与她交谈，试图理解她的感受。

之后的镜头中，女生重新调整姿势，显得更加放松，但仍然保持着对话的状态。整个视频的背景是一个装饰精美的房间，有花瓶、沙发和一些现代家具，营造出一种温馨而舒适的氛围。

最后，画面切换到一个更大的房间视角，可以看到更多的细节，包括其他人在场以及房间的整体布局。这个房间布置得非常优雅，有吊灯和其他装饰品，显示出这是一个正式或半正式的场合。

总结来看，这段视频记录了一对情侣之间的对话，主要围绕着未举办婚礼的问题展开，反映了他们之间的情感交流和互动。

### 缺陷 | Drawbacks

通过测试，发现对视频的理解主要来自抽帧，较少使用到字幕、音频信息，导致视频内容描述很抽象。

**Comment by LDLINGLINGLING** [comment]
你好，模型暂未用到字幕和音频。
