### ISSUE TITLE
What is the correlation between image resolution and number of tokens?

### ISSUE THREAD

**Issue by univa-JASON** [OpenBMB/MiniCPM-V#398]
Thanks for your great work! 
same as title, Can you tell me what the correlation is between image resolution and number of tokens?

**Comment by LDLINGLINGLING** [comment]
This is more complicated and involves the segmentation of subgraphs. Each subgraph will be represented by 64 tokens. But for the specific number of sub-graphs, you can check the technical report of version 2.5.
