### ISSUE TITLE
💡 [REQUEST] - llama.cpp server support

### ISSUE THREAD

**Issue by rhjdvsgsgks** [OpenBMB/MiniCPM-V#401]
### 相关Issues | Reference Issues

mirror of https://github.com/OpenBMB/llama.cpp/issues/10

### 摘要 | Summary

Hi

I am trying to load this using Llama.CPP HTTP server. Is this supported please? And if yes, please could you give me an example of how to do this?

thanks

### 基本示例 | Basic Example

use minicpm from llama.cpp webui

### 缺陷 | Drawbacks

not sure

**Comment by tc-mb** [comment]
I haven't adapted llamam.cpp's http sever. 
Maybe it can run, or it may need some modifications.
And I will try to modify them this week.
