### ISSUE TITLE
How to use it on iPad Pro?

### ISSUE THREAD

**Issue by yifeichen2024** [OpenBMB/MiniCPM-V#406]
Thank you for this great update! I am really interested in use it on iPad Pro M4. Could you point a reference or doc that I can use it on iPad? I am not quite understand since the link you provide shows how to build in on MacOS, but not on iPadOS.

Links you provide for implementation on iPad:
https://github.com/OpenBMB/llama.cpp/blob/minicpmv-main/examples/llava/README-minicpmv2.6.md
https://github.com/OpenBMB/ollama/blob/minicpm-v2.6/examples/minicpm-v2.6/README.md

Thx

**Comment by tc-mb** [comment]
Hello, our iPad is only in demo status and has not yet been developed. There are still many engineering problems. It may be available to everyone in the future, but it will take some time. At this stage, we will open source the model for everyone to use first.
