### ISSUE TITLE
OCR识别支持不同角度的图片

### ISSUE THREAD

**Issue by xxlxms** [OpenBMB/MiniCPM-V#409]
你好，我测试2.6版本发现OCR识别对180度旋转的图片效果会比较差。这种是因为训练数据没有导致的吗？

**Comment by Cuiunbo** [comment]
您好，非常感谢您的关注， 您的反馈对我们的帮助很大。是的，我们并未刻意设计该类训练数据， 我们将持续改进我们的模型，如有更多发现，也欢迎和您继续讨论！

**Comment by xiaobaixue** [comment]
> 您好，非常感谢您的关注， 您的反馈对我们的帮助很大。是的，我们并未刻意设计该类训练数据， 我们将持续改进我们的模型，如有更多发现，也欢迎和您继续讨论！

如果自己微调旋转的图片效果会有提升吗？
