### ISSUE TITLE
[BUG] `pip install` fails for decord on Mac M1

### ISSUE THREAD

**Issue by thelazyoxymoron** [OpenBMB/MiniCPM-V#412]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

`pip install` fails on M1 Mac since there's no arm version for `decord` yet. See [this issue](https://github.com/dmlc/decord/issues/213).

```
ERROR: Could not find a version that satisfies the requirement decord (from versions: none)
ERROR: No matching distribution found for decord
```

### 期望行为 | Expected Behavior

Installation should proceed successfully.

### 复现方法 | Steps To Reproduce

1. Create a new conda environment on M1 Mac
2. Try to install dependencies using `pip install -r requirements.txt`
3. Get the error

### 运行环境 | Environment

```Markdown
- OS: MacOS Sonoma 14.5
- Python: 3.10
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

This can be resolved by using [eva-decord](https://pypi.org/project/eva-decord/) which was forked from the official `decord` project to specifically support arm macs. [See this comment for more context](https://github.com/dmlc/decord/issues/213#issuecomment-1583215166)

**Comment by iceflame89** [comment]
You can use `cv2` from opencv-python to decode video.
```
cv2.VideoCapture(video_path)
```

**Comment by lilac** [comment]
Thanks, save me a day.

**Comment by ilya-vassilenko** [comment]
Thanks, @thelazyoxymoron , saved my day as well.
