### ISSUE TITLE
[BUG] <title>./script/run_inference.sh MiniCPM-Llama3-V-2_6 MathVista_MINI all

### ISSUE THREAD

**Issue by luyao-cv** [OpenBMB/MiniCPM-V#413]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Did not detect the .env xxxxx/MiniCPM-V/eval_mm/vlmevalkit/.env, failed to load. 

### 期望行为 | Expected Behavior

Did not detect the .env xxxxx/MiniCPM-V/eval_mm/vlmevalkit/.env, failed to load. 

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

Did not detect the .env xxxxx/MiniCPM-V/eval_mm/vlmevalkit/.env, failed to load.

**Comment by Cuiunbo** [comment]
Hello, Thank you for your attention. This is a system warning, and will not affect the inference

**Comment by Cuiunbo** [comment]
And also you can try using the official vlmevalkit!
https://github.com/open-compass/VLMEvalKit
