### ISSUE TITLE
💡 [REQUEST] - <title> I need multigpu inference like device_map='auto' in minicpm 2.6

### ISSUE THREAD

**Issue by dahwin** [OpenBMB/MiniCPM-V#414]
### 起始日期 | Start Date

08/06/2024

### 实现PR | Implementation PR

no

### 摘要 | Summary

 I need multigpu inference like device_map='auto' in minicpm 2.6

### 基本示例 | Basic Example

`import torch
from PIL import Image
from transformers import AutoModel, AutoTokenizer, BitsAndBytesConfig
model_id = 'openbmb/MiniCPM-V-2_6'
# Load the model with the new configuration
model = AutoModel.from_pretrained(
    model_id, 
    trust_remote_code=True,
    attn_implementation='sdpa',
    torch_dtype=torch.float16,
    device_map="auto",
    low_cpu_mem_usage=True
)

model = model.eval()
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

# Rest of your code remains the same
image = Image.open('/kaggle/input/ddddddddddd/Picsart_24-03-16_16-25-10-385 (1) (1).jpg').convert('RGB')
question = 'What is in the image?'
msgs = [{'role': 'user', 'content': question}]

# Streaming example
res = model.chat(
    image=image,
    msgs=msgs,
    tokenizer=tokenizer,
    sampling=True,
    stream=True,
        temperature=0.01,
    max_new_tokens=300,
)

generated_text = ""
for new_text in res:
    generated_text += new_text
    print(new_text, flush=True, end='')`

### 缺陷 | Drawbacks

 I need multigpu inference like device_map='auto' in minicpm 2.6

**Comment by Cuiunbo** [comment]
2.6 hf supports multigpu inference, code:[MiniCPM-V/web_demo_2.6.py at main · OpenBMB/MiniCPM-V](https://github.com/OpenBMB/MiniCPM-V/blob/main/web_demo_2.6.py#L44-L67)

我们后面将把该问题更新到FAQ上
