### ISSUE TITLE
OCRBench 指标对不齐，指标才771，和你们结果852还差一点

### ISSUE THREAD

**Issue by daixiangzi** [OpenBMB/MiniCPM-V#415]
主要代码：
openbmb/MiniCPM-V-2_6
```
# transformers==4.41.0
response = self.model.chat(image=visuals[0],msgs=msgs,tokenizer=self.tokenizer)
```

结果日志:
######################### OCRBench #############################
Text Recognition(Total 300): 252
---------------- Details of Recognition Score ------------------
Regular Text Recognition(Total 50): 49
Irregular Text Recognition(Total 50): 45
Artistic Text Recognition(Total 50): 46
Handwriting Recognition(Total 50): 32
Digit String Recognition(Total 50): 35
Non-Semantic Text Recognition(Total 50): 45
----------------------------------------------------------------
Scene Text-centric VQA(Total 200): 174
----------------------------------------------------------------
Doc-oriented VQA(Total 200): 145
----------------------------------------------------------------
Key Information Extraction(Total 200): 154
Handwritten Mathematical Expression Recognition(Total 100): 46
--------------------- Final Score ------------------------------
Final Score(Total 1000): 771

**Comment by Cuiunbo** [comment]
您好，需要正确使用prompt才能得到该指标，目前正在合入vlmevalkit， 预计明天您可使用vlmevalkit来复现该结果。
另外， 可能需要注意您的torch版本需要更新至 2.2.0以上

**Comment by Cuiunbo** [comment]
https://github.com/open-compass/VLMEvalKit
您好呀， 现在已合入VLMEvalKit仓库～

**Comment by daixiangzi** [comment]
如果我想在自己的多选数据上评估，也要遵循你们的prompt 吗？

**Comment by daixiangzi** [comment]
> https://github.com/open-compass/VLMEvalKit 您好呀， 现在已合入VLMEvalKit仓库～

如果我想在自己的多选数据上评估，也要遵循你们的prompt 吗？

**Comment by Cuiunbo** [comment]
抱歉，才刚看到您的回复， 多选可能需要自己设置一个效果满意的prompt

**Comment by luyao-cv** [comment]
> 抱歉，才刚看到您的回复， 多选可能需要自己设置一个效果满意的prompt

你好，我用的这个工具跑出来的ocrbench分数只有839，离github指标852还差不少，这是什么原因呢？
