### ISSUE TITLE
[BUG] <title> llama.cpp编译2.6版本出错

### ISSUE THREAD

**Issue by dingtine** [OpenBMB/MiniCPM-V#416]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

下面这段makefile中的代码报错，我理解是不是ffmpeg安装后，那里没有配置对。
试了很多种方案都没解决，求教。（之前的2.5没有这个模块，一直正常）

报错：
[ 66%] Building CXX object examples/llava/CMakeFiles/llama-minicpmv-cli.dir/minicpmv-cli.cpp.o
/Users/tine/llama.cpp/examples/llava/minicpmv-cli.cpp:13:14: fatal error: 'libavcodec/avcodec.h' file not found
#include <libavcodec/avcodec.h>
^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [examples/llava/CMakeFiles/llama-minicpmv-cli.dir/minicpmv-cli.cpp.o] Error 1
make[1]: *** [examples/llava/CMakeFiles/llama-minicpmv-cli.dir/all] Error 2
make: *** [all] Error 2

原始makefile中的代码
FFMPEG_CFLAGS := $(shell pkg-config --cflags libavformat libavcodec libavutil)
FFMPEG_LIBS := $(shell pkg-config --libs libavformat libavcodec libavutil) -lswscale

llama-minicpmv-cli: examples/llava/minicpmv-cli.cpp examples/llava/clip.h examples/llava/clip.cpp examples/llava/llava.h examples/llava/llava.cpp ggml.o llama.o 
(OBJS)
(CXXFLAGS) 
&lt; -o 
&lt;)
(CXXFLAGS) 
(call GET_OBJ_FILE, examples/llava/clip.cpp) -Wno-cast-qual
(CXXFLAGS) 
(call GET_OBJ_FILE, examples/llava/llava.cpp)
(CXXFLAGS) 
(filter-out %.h 
^) 
&lt;) 
(call GET_OBJ_FILE, examples/llava/llava.cpp) -o 
(LDFLAGS) $(FFMPEG_LIBS)

### 运行环境 | Environment

```Markdown
- OS: mac os
- Python: python3.11
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by tc-mb** [comment]
https://github.com/OpenBMB/llama.cpp/tree/minicpmv-main-no-video-inference

**Comment by ppkliu** [comment]
I can build llama.cpp after install these packages.
apt install pkg-config
apt install libavformat-dev
apt install libavcodec-dev
apt install libswresample-dev
apt install libswscale-dev
apt install libavutil-dev

make clean
make -j 8

Reference:
https://github.com/OpenBMB/llama.cpp/issues/22

**Comment by guoQiNing** [comment]
我在win10的wsl2上解决过类似的问题，看看能不能作参考。
首先我下载ffmpeg-7.0.2.tar.xz并解压，并进行`make`以及`sudo make install`，这些不同系统上操作可能不同。
然后我修改了examples/llava/CMakeLists.txt中的部分内容，手动配置了ffmpeg库的路径：
```
set(FFMPEG_DIR "/path/ffmpeg_v7.0.2") # ffmpeg path
find_path(FFMPEG_INCLUDE_DIRS
    NAMES libavformat/avformat.h
    HINTS ${FFMPEG_DIR}/include
)
find_library(AVFORMAT_LIBRARY
    NAMES avformat
    HINTS ${FFMPEG_DIR}/lib
)
find_library(AVCODEC_LIBRARY
    NAMES avcodec
    HINTS ${FFMPEG_DIR}/lib
)
find_library(AVUTIL_LIBRARY
    NAMES avutil
    HINTS ${FFMPEG_DIR}/lib
)
find_library(SWSCALE_LIBRARY
    NAMES swscale
    HINTS ${FFMPEG_DIR}/lib
)
find_library(SWRESAMPLE_LIBRARY
    NAMES swresample
    HINTS ${FFMPEG_DIR}/lib
)
include_directories(${FFMPEG_INCLUDE_DIRS})
target_link_libraries(${TARGET} PRIVATE
    common
    llava
    ${CMAKE_THREAD_LIBS_INIT}
    ${AVFORMAT_LIBRARY}
    ${AVCODEC_LIBRARY}
    ${AVUTIL_LIBRARY}
    ${SWSCALE_LIBRARY}
    ${SWRESAMPLE_LIBRARY}
)
```
我认为这样可以解决ffmpeg库的问题。
