### ISSUE TITLE
💡 [REQUEST] - 请问可以提供一下minicpm-v2.6跑OCRBench的cot prompt吗，想复现一下实验结果，感谢

### ISSUE THREAD

**Issue by yjc11** [OpenBMB/MiniCPM-V#419]
### 起始日期 | Start Date

8/8/2024

### 摘要 | Summary

请问可以提供一下minicpm-v2.6跑OCRBench的cot prompt吗，想复现一下实验结果，感谢

### 基本示例 | Basic Example

。

### 缺陷 | Drawbacks

。

**Comment by Cuiunbo** [comment]
请参考
https://github.com/open-compass/VLMEvalKit
