### ISSUE TITLE
会支持VLLM推理吗

### ISSUE THREAD

**Issue by cat2353050774** [OpenBMB/MiniCPM-V#42]
会支持VLLM推理吗

**Comment by iceflame89** [comment]
We are working on it, coming in this week.

**Comment by zhengxingmao** [comment]
支持llama.cpp吗？

**Comment by iceflame89** [comment]
MiniCPM-V-2.0 support vLLM now， https://github.com/OpenBMB/MiniCPM-V#vllm

**Comment by ye7love7** [comment]
subprocess.CalledProcessError: Command '['cmake', '/home/tskj/project/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/tmpf3n8hwcm.build-lib/vllm', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=/tmp/tmpnhuiosjo.build-temp', '-DVLLM_TARGET_DEVICE=cuda', '-DVLLM_PYTHON_EXECUTABLE=/home/tskj/miniconda3/envs/py310/bin/python', '-DNVCC_THREADS=1', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=56']' returned non-zero exit status 1.
