### ISSUE TITLE
[ollama] - 希望可以支持 ollama，无需再自行编译，如其他流行模型一样，run 后直接可用。

### ISSUE THREAD

**Issue by calonye** [OpenBMB/MiniCPM-V#422]
### 摘要 | Summary

希望可以支持 ollama，无需再自行编译，如其他流行模型一样，run 后直接可用。

### 基本示例 | Basic Example

/

### 缺陷 | Drawbacks

/

**Comment by tc-mb** [comment]
这可能需要ollama官方团队一些支持，虽然我们尽可能提供可用版本，但团队更多的注意力会放在模型能力上面。

**Comment by calonye** [comment]
> 这可能需要ollama官方团队一些支持，虽然我们尽可能提供可用版本，但团队更多的注意力会放在模型能力上面。

了解，确实如此。
