### ISSUE TITLE
loss 曲线的问题

### ISSUE THREAD

**Issue by jyC23333** [OpenBMB/MiniCPM-V#426]
Hi，阅读 miniCPM2.5 的技术报告，发现经历的训练阶段是比较多的，故有以下两点问题希望咨询下：
1. 2.6 与 2.5 都是按照技术报告中的三阶段进行训练的吗？
2. 是否可以提供训练中各阶段的 loss 曲线作为参考？

**Comment by YuzaChongyi** [comment]
你好，第一个问题，2.5 是三阶段训练的，2.6 我们加入了多图和视频能力，所以会多一个图文交替/视频的 pretrain 阶段，第二个 loss曲线抱歉无法提供，因为整体有比较多中断和重启训练，loss 随着参数的放开和分辨率的提升，会有明显的下降

**Comment by jyC23333** [comment]
@YuzaChongyi 非常感谢，多图训练新增的是 pretrain 阶段，而不是在sft数据中新增多图数据吗？
这一点的设计是出于什么考虑呢？
