### ISSUE TITLE
[BUG] ollama 不能正常启动 minicpm-v2.6

### ISSUE THREAD

**Issue by chengzi0103** [OpenBMB/MiniCPM-V#432]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用ollama 启动 `aiden_lu/minicpm-v2.6:Q4_K_M` 的时候 出现下面的问题

～～～
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
Error: llama runner process has terminated: signal: aborted (core dumped)
～～～

### 复现方法 | Steps To Reproduce

ollama run aiden_lu/minicpm-v2.6:Q4_K_M

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 22.04
- Python: OLLAMA
- Transformers:
- PyTorch:
- CUDA : 12.2
```

**Comment by luixiao0** [comment]
related [https://github.com/OpenBMB/MiniCPM-V/issues/393](url)
