### ISSUE TITLE
model_path的路径问题

### ISSUE THREAD

**Issue by hjlxlp** [OpenBMB/MiniCPM-V#434]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

请问，为什么用model_path = 'openbmb/MiniCPM-V-2_6'就能运行成功（这个是用的本地模型文件，还是huggingface的，前面我执行启动的python web_demo_2.6.py --device cuda的时候，有下载了16g的文件），用下面的绝对路径不行呢，本地文件我看是有的。
![30b1681b9b3a1ebd4d962c7126b8178](https://github.com/user-attachments/assets/8b9f8931-3fa4-44de-883a-8580a36cbfda)
![b1a792152e2e2a5a880a645299bc631](https://github.com/user-attachments/assets/334a2027-4aea-4881-9903-b1c5eb92dc02)
![300f2ead58287245bbaf3d5947e87fb](https://github.com/user-attachments/assets/fb5a591a-3f63-490b-98cc-f9d16ee6c1fa)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Cuiunbo** [comment]
cache不用是正确的路径。应该使用这样下载指定的路径
huggingface-cli download --resume-download gpt2 --local-dir gpt2
