### ISSUE TITLE
[ollama] 请问有ollama的curl使用范例吗？ Do you have any ollama test command ?

### ISSUE THREAD

**Issue by ppkliu** [OpenBMB/MiniCPM-V#436]
### 起始日期 | Start Date

8/09/24

### 实现PR | Implementation PR

No

### 相关Issues | Reference Issues

No

### 摘要 | Summary

[ollama] 请问有minicpm-v 的ollama的curl使用范例吗
例如:用curl 上传图片到ollama的api, 让使用者可以测试他环境是否成功？

Do you have any ollama test command ?
ex: use curl tool to talk with ollama api and get the response of minicpm-v ?
Thanks!

### 基本示例 | Basic Example

A test command with talking with a image for ollama

### 缺陷 | Drawbacks

No

**Comment by tc-mb** [comment]
或许可以参考我提供的readme，不知道您是否有看过。
https://github.com/OpenBMB/ollama/blob/minicpm-v2.6/examples/minicpm-v2.6/README.md

**Comment by ppkliu** [comment]
I solve my issue by the following steps:
1. install vllm as LLM api server
2. Use python code and openai compatible API to send image data to remote server
3. Use restful api need to modify image format with base64

```
from openai import OpenAI  
openai_api_key = "None" # your api key set in launch server  
openai_api_base = "http://localhost:8000/v1" # http id  
client = OpenAI(  
    api_key=openai_api_key,  
    base_url=openai_api_base,  
)  

# 用于传本地图片
with open('your/local/pic/path','rb') as file:
   image = "data:image/jpeg;base64,"+ base64.b64encode(file.read()).decode('utf-8')

chat_response = client.chat.completions.create(  
    model="./MiniCPM-V-2_6/", # model_local_path or huggingface id  
    messages=[{  
        "role": "user",  
        "content": [  
            # NOTE: 使用图像令牌 <image> 的提示格式是不必要的，因为提示将由API服务器自动处理。  
            # 由于提示将由API服务器自动处理，因此不需要使用包含 <image> 图像令牌的提示格式。  
            {"type": "text", "text": "请描述这张图片"},  
            {  
                "type": "image_url",  
                "image_url": {  
                     #"url": "https://air-example-data-2.s3.us-west-2.amazonaws.com/vllm_opensource_llava/stop_sign.jpg",  
                     "url":  image,
                },  
            },  
        ],  
    }],  
    extra_body={  
        "stop_token_ids": [151645, 151643]  
    }  
)  
print("Chat response:", chat_response)  
print("Chat response content:", chat_response.choices[0].message.content)  

```
I refer this article.
版权声明：本文为博主原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接和本声明。                       
原文链接：https://blog.csdn.net/stephen147/article/details/140996146
