### ISSUE TITLE
你好，为啥这里的图像大小只能限制在448*16?

### ISSUE THREAD

**Issue by HongLouyemeng** [OpenBMB/MiniCPM-V#446]
https://github.com/OpenBMB/MiniCPM-V/blob/791c977ab2c74fe204bb25f1e6c44f4faf88bf06/web_demo_2.6.py#L160

**Comment by iceflame89** [comment]
这是长的边不超过448*16=7168，对过大的图做个限制，不会影响推理结果；这里本来是为了减少网络传输，本地demo不用考虑
