### ISSUE TITLE
[vllm] - <title>run error

### ISSUE THREAD

**Issue by lonngxiang** [OpenBMB/MiniCPM-V#448]
### 摘要 | Summary

RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
vllm 版本0.5.4
torch 2.4

### 基本示例 | Basic Example

CUDA_VISIBLE_DEVICES=1 vllm serve  /ai/minicpmv --host 192.168.2.238 --port 10868 --max-model-len 10000 --trust-remote-code --api-key token-abc123 --gpu_memory_utilization 1 --trust-remote-code 

### 缺陷 | Drawbacks

RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

**Comment by HwwwwwwwH** [comment]
First, you can try uninstall `flash_attn` and run it again.
If this doesn't work, you can try the solutions in this issue: https://github.com/vllm-project/vllm/issues/7151

**Comment by lonngxiang** [comment]
ok ,tks
另外这边部署后接口，用openai访问正常，但是用requests访问不行，其他模型是正常的

```
import requests
import json

with open(r"C:\Users\loong\Downloads\image_with_lora2.jpg", 'rb') as image_file:
    # 读取图像文件的二进制数据
    image_data = image_file.read()
                
encoded_string = base64.b64encode(image_data).decode('utf-8')

url = "http://1****:10868/v1/chat/completions"
headers = {
    "Content-Type": "application/json",
    "Authorization": "token-abc123"
}
data = {

    "model": "/ai/minicpmv",
    "messages": [{
        "role": "user",
        "content": [
            # NOTE: The prompt formatting with the image token `<image>` is not needed
            # since the prompt will be processed automatically by the API server.
            {"type": "text", "text": "图片里有什么?"},
            {
                "type": "image_url",
                "image_url": {
                    "url": f"data:image/jpeg;base64,{encoded_string}",
                },
            },
        ],
    }],
    "stop_token_ids":[151645, 151643],
    # "max_tokens":1000,
    "stream": True
}

response = requests.post(url, headers=headers, json=data, stream=True)


for line in response.iter_lines():
    original_string = line.decode("utf-8")
    if "content" in original_string:
        # print(re.findall(r'"content":"([^"]*)"', original_string))
        start_index = original_string.find('{')
        end_index = original_string.rfind('}')
        data_string = original_string[start_index:end_index+1]

        # # 将data字符串解析为字典
        data_dict = json.loads(data_string)
        print(data_dict["choices"][0]["delta"]["content"], end="")



```

**Comment by lonngxiang** [comment]
> ok ,tks 另外这边部署后接口，用openai访问正常，但是用requests访问不行，其他模型是正常的
> 
> ```
> import requests
> import json
> 
> with open(r"C:\Users\loong\Downloads\image_with_lora2.jpg", 'rb') as image_file:
>     # 读取图像文件的二进制数据
>     image_data = image_file.read()
>                 
> encoded_string = base64.b64encode(image_data).decode('utf-8')
> 
> url = "http://1****:10868/v1/chat/completions"
> headers = {
>     "Content-Type": "application/json",
>     "Authorization": "token-abc123"
> }
> data = {
> 
>     "model": "/ai/minicpmv",
>     "messages": [{
>         "role": "user",
>         "content": [
>             # NOTE: The prompt formatting with the image token `<image>` is not needed
>             # since the prompt will be processed automatically by the API server.
>             {"type": "text", "text": "图片里有什么?"},
>             {
>                 "type": "image_url",
>                 "image_url": {
>                     "url": f"data:image/jpeg;base64,{encoded_string}",
>                 },
>             },
>         ],
>     }],
>     "stop_token_ids":[151645, 151643],
>     # "max_tokens":1000,
>     "stream": True
> }
> 
> response = requests.post(url, headers=headers, json=data, stream=True)
> 
> 
> for line in response.iter_lines():
>     original_string = line.decode("utf-8")
>     if "content" in original_string:
>         # print(re.findall(r'"content":"([^"]*)"', original_string))
>         start_index = original_string.find('{')
>         end_index = original_string.rfind('}')
>         data_string = original_string[start_index:end_index+1]
> 
>         # # 将data字符串解析为字典
>         data_dict = json.loads(data_string)
>         print(data_dict["choices"][0]["delta"]["content"], end="")
> ```

POST /v1/chat/completions HTTP/1.1" 401 Unauthorized

**Comment by lonngxiang** [comment]
"Authorization": "token-abc123"  是因为有api key这个用不了requests，如果vllm部署没有api key设置，requests是可以正常请求的
