### ISSUE TITLE
安装包就报错

### ISSUE THREAD

**Issue by smilejk** [OpenBMB/MiniCPM-V#449]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

 Downloading spacy-3.7.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
ERROR: Cannot install -r requirements.txt (line 18) and gradio==4.41.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    spacy 3.7.2 depends on typer<0.10.0 and >=0.3.0
    gradio 4.41.0 depends on typer<1.0 and >=0.12; sys_platform != "emscripten"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### 复现方法 | Steps To Reproduce

pip install -r requirements.txt

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by smilejk** [comment]
替换这个版本


pip install packaging==23.2 addict==2.4.0 editdistance==0.6.2 einops==0.7.0 fairscale==0.4.0 jsonlines==4.0.0 markdown2==2.4.10 matplotlib==3.7.4 more_itertools==10.1.0 nltk==3.8.1 numpy==1.24.4 opencv_python_headless==4.5.5.64 openpyxl==3.1.2 Pillow==10.1.0 sacrebleu==2.3.2 seaborn==0.13.0 shortuuid==1.0.11 spacy==3.4.0 timm==0.9.10 torch==2.1.2 torchvision==0.16.2 tqdm==4.66.1 protobuf==4.25.0 transformers==4.40.0 typing_extensions==4.8.0 uvicorn==0.24.0.post1 sentencepiece==0.1.99 accelerate==0.30.1 socksio==1.0.0 gradio==3.40.0 gradio_client decord

**Comment by iceflame89** [comment]
Fixed now
