### ISSUE TITLE
[BUG] English UI but Chinese text?

### ISSUE THREAD

**Issue by SoftologyPro** [OpenBMB/MiniCPM-V#450]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

UI opens, shows descriptions/text in English.
I prompt with an image and a prompt.
Answer is Chinese?
How do I get it to answer in English.
![image](https://github.com/user-attachments/assets/0abc8d53-6668-47ee-b8be-be35dc9ee188)

### 期望行为 | Expected Behavior

Answer in English.

### 复现方法 | Steps To Reproduce

Start UI
Input image and text (in English).
Click Submit.

### 运行环境 | Environment

```Markdown
- OS: Windows 11
- Python: 3.10.x
- Transformers: 4.40.0
- PyTorch: 2.4.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.4
```

### 备注 | Anything else?

No.  Also link to FAQ-en above fails.

**Comment by SoftologyPro** [comment]
As soon as I restarted the UI it now works in English.

**Comment by iceflame89** [comment]
@SoftologyPro  The history message would influence the output, you can clear history and try again
