### ISSUE TITLE
[BUG] 使用官方vllm API方式运行找不到名字

### ISSUE THREAD

**Issue by SunYong0821** [OpenBMB/MiniCPM-V#451]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

vllm运行minicpm正常
` CUDA_VISIBLE_DEVICES=1 vllm serve /home/suny/.cache/modelscope/hub/OpenBMB/MiniCPM-V-2_6/ --host 0.0.0.0 --port 9998 --gpu-memory-utilization 0.3 --enforce-eager --max-model-len 2048 --trust-remote-code  --api-key minicpm`

`INFO 08-12 11:46:11 launcher.py:14] Available routes are:
INFO 08-12 11:46:11 launcher.py:22] Route: /openapi.json, Methods: HEAD, GET
INFO 08-12 11:46:11 launcher.py:22] Route: /docs, Methods: HEAD, GET
INFO 08-12 11:46:11 launcher.py:22] Route: /docs/oauth2-redirect, Methods: HEAD, GET
INFO 08-12 11:46:11 launcher.py:22] Route: /redoc, Methods: HEAD, GET
INFO 08-12 11:46:11 launcher.py:22] Route: /health, Methods: GET
INFO 08-12 11:46:11 launcher.py:22] Route: /tokenize, Methods: POST
INFO 08-12 11:46:11 launcher.py:22] Route: /detokenize, Methods: POST
INFO 08-12 11:46:11 launcher.py:22] Route: /v1/models, Methods: GET
INFO 08-12 11:46:11 launcher.py:22] Route: /version, Methods: GET
INFO 08-12 11:46:11 launcher.py:22] Route: /v1/chat/completions, Methods: POST
INFO 08-12 11:46:11 launcher.py:22] Route: /v1/completions, Methods: POST
INFO 08-12 11:46:11 launcher.py:22] Route: /v1/embeddings, Methods: POST
INFO:     Started server process [377903]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9998 (Press CTRL+C to quit)
`

### 期望行为 | Expected Behavior

使用api方式调用
`from openai import OpenAI
openai_api_key = 'minicpm'
openai_api_base = "http://0.0.0.0:9998/v1"
client = OpenAI(api_key=openai_api_key,base_url=openai_api_base)
import base64
with open('4206985.jpg','rb') as file:
    image = "data:image/jpeg;base64,"+ base64.b64encode(file.read()).decode('utf-8')

chat_response = client.chat.completions.create(
    model="/home/suny/.cache/modelscope/hub/OpenBMB/MiniCPM-V-2_6",
    messages=[{
        "role": "user",
        "content": [
            {"type": "text", "text": "请描述这张图片"},
            {"type": "image_url","image_url": {"url": image}}
        ]
    }],
    extra_body={
        "stop_token_ids": [151645, 151643]
    }
)
`

报错

`INFO:     127.0.0.1:54302 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:54518 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found

Traceback (most recent call last):
  File "/home/suny/x/test/t1.py", line 9, in <module>
    chat_response = client.chat.completions.create(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suny/anaconda3/envs/x/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/suny/anaconda3/envs/x/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 579, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/suny/anaconda3/envs/x/lib/python3.11/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/suny/anaconda3/envs/x/lib/python3.11/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/suny/anaconda3/envs/x/lib/python3.11/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'object': 'error', 'message': 'The model `/home/suny/.cache/modelscope/hub/OpenBMB/MiniCPM-V-2_6` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}
`

### 复现方法 | Steps To Reproduce

1. pip3 install vllm
2. download minicpmv2.6
3. vllm serve
4. python

### 运行环境 | Environment

```Markdown
- OS: ubuntu 20.24
- Python:3.11
- Transformers:4.44.0
- PyTorch:2.4.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.4

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

**Comment by LDLINGLINGLING** [comment]
是否修改过你的地址，因为您的地址中存在‘.’不知道是否有这个原因

**Comment by SunYong0821** [comment]
> 是否修改过你的地址，因为您的地址中存在‘.’不知道是否有这个原因

我用你今天的awq模型就可以，代码完全没有改，但是完整版的就是不行

**Comment by randydl** [comment]
```bash
NAME="MiniCPM-V-2_6" && \
vllm serve /mnt/models/$NAME \
    --served-model-name $NAME \
    --host 0.0.0.0 \
    --port 8001 \
    --tensor-parallel-size 4 \
    --max-model-len 4096 \
    --trust-remote-code
```
```python
client = OpenAI(
    api_key='EMPTY_API_KEY',
    base_url='http://localhost:8001/v1'
)

def generate_response(client, prompt, image):
    response = client.chat.completions.create(
        model='MiniCPM-V-2_6',
        messages=[{
            'role': 'user',
            'content': [
                {'type': 'text', 'text': prompt},
                {'type': 'image_url', 'image_url': {'url': image}}
            ]
        }],
        extra_body={'stop_token_ids': [151645, 151643]}
    )
    return response
```

这样写才是对的，你需要定义一个--served-model-name='XXX'参数，并且api调用的时候model='XXX'

**Comment by randydl** [comment]
> 是否修改过你的地址，因为您的地址中存在‘.’不知道是否有这个原因

我想问一下，在vllm api调用方式中怎么传入视频或者多张图片？

**Comment by HwwwwwwwH** [comment]
> > 是否修改过你的地址，因为您的地址中存在‘.’不知道是否有这个原因
> 
> 我想问一下，在vllm api调用方式中怎么传入视频或者多张图片？

vllm 官方暂时不支持，我们后续会持续跟进这个事情。

**Comment by SunYong0821** [comment]
> ```shell
> NAME="MiniCPM-V-2_6" && \
> vllm serve /mnt/models/$NAME \
>     --served-model-name $NAME \
>     --host 0.0.0.0 \
>     --port 8001 \
>     --tensor-parallel-size 4 \
>     --max-model-len 4096 \
>     --trust-remote-code
> ```
> 
> ```python
> client = OpenAI(
>     api_key='EMPTY_API_KEY',
>     base_url='http://localhost:8001/v1'
> )
> 
> def generate_response(client, prompt, image):
>     response = client.chat.completions.create(
>         model='MiniCPM-V-2_6',
>         messages=[{
>             'role': 'user',
>             'content': [
>                 {'type': 'text', 'text': prompt},
>                 {'type': 'image_url', 'image_url': {'url': image}}
>             ]
>         }],
>         extra_body={'stop_token_ids': [151645, 151643]}
>     )
>     return response
> ```
> 
> 这样写才是对的，你需要定义一个--served-model-name='XXX'参数，并且api调用的时候model='XXX'

好的，我去测试一下
