### ISSUE TITLE
[BUG] 分析视频内容，提示词完全没有作用。

### ISSUE THREAD

**Issue by fastfading** [OpenBMB/MiniCPM-V#452]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

分析视频内容，提示词完全没有作用。
无论说什么，他都在总结视频。  

比如一个视频会议录制mp4 我要
1. ocr提取视频中 ppt 内容
2. 给出每张ppt 起始结束时间
都忽视我请求。  还是在总结视频。

### 期望行为 | Expected Behavior

分析视频内容，回复提示词内容

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by iceflame89** [comment]
1.ocr提取视频中 ppt 内容；2.给出每张ppt 起始结束时间 。目前模型暂不具备这两项能力，请关注后续技术更新
