### ISSUE TITLE
💡 [REQUEST] - <暂不支持多图对话的微调>

### ISSUE THREAD

**Issue by Dshijie** [OpenBMB/MiniCPM-V#455]
### 摘要 | Summary

目前微调，默认的是单张图片，但是V2.6已经支持多图的问答了，finetune/dataset.py里还是只支持单张图片的加载，请问可不可以实现多图的微调？

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

1

**Comment by Cuiunbo** [comment]
已支持
