### ISSUE TITLE
大家有尝试使用MiniCPM-V-2_5做图像分类任务吗？效果如何？

### ISSUE THREAD

**Issue by zhanghl0** [OpenBMB/MiniCPM-V#464]
### 摘要 | Summary

大家有尝试使用MiniCPM-V-2_5做图像分类任务吗？效果如何？

### 基本示例 | Basic Example

大家有尝试使用MiniCPM-V-2_5做图像分类任务吗？效果如何？

### 缺陷 | Drawbacks

大家有尝试使用MiniCPM-V-2_5做图像分类任务吗？效果如何？

**Comment by DAAworld** [comment]
可能要训练吧，感觉直接开始用的效果不是很好。
