### ISSUE TITLE
💡 [REQUEST] - <title>终端部署的过程

### ISSUE THREAD

**Issue by lcystudy** [OpenBMB/MiniCPM-V#468]
### 摘要 | Summary

请问下你们在把模型部署到ipad或者手机这种终端上，是用的什么框架进行部署集成的啊，具体的开发过程是怎么样的，我目前了解的一种是用mlc-llm把模型参数进行转化然后跟ndk，rust，Android studio这些工具一起，把模型做成一个可以安装的apk，但是这个方法好像是只能部署纯文本模型，对于多模态的模型能用一样的办法吗；另一种就是你们v2.5版本的在手机上termux去做，用llamacpp的框架压缩，但是这个交互性不是很好，所以想请教一下你们多模态模型在手机上的demo的开发流程，非常感谢！

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by iceflame89** [comment]
手机部署模型推理用llama.cpp，UI调用llama.cpp即可
