### ISSUE TITLE
请问下2.0版本的webui有没有demo

### ISSUE THREAD

**Issue by lichtud** [OpenBMB/MiniCPM-V#47]
http://120.92.209.146/ 这个demo地址的webui我想测试下。

**Comment by iceflame89** [comment]
近期会公开本地调用模型的webui代码

**Comment by lichtud** [comment]
> 近期会公开本地调用模型的webui代码
好的，期待种，谢谢。

**Comment by iceflame89** [comment]
webui demo代码已公开，请看[说明](https://github.com/OpenBMB/MiniCPM-V?tab=readme-ov-file#%E6%9C%AC%E5%9C%B0webui-demo%E9%83%A8%E7%BD%B2)

**Comment by lichtud** [comment]
> webui demo代码已公开，请看[说明](https://github.com/OpenBMB/MiniCPM-V?tab=readme-ov-file#%E6%9C%AC%E5%9C%B0webui-demo%E9%83%A8%E7%BD%B2)

非常感谢。
