### ISSUE TITLE
[BUG] <title>Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

### ISSUE THREAD

**Issue by DAAworld** [OpenBMB/MiniCPM-V#470]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行2.6时候提示，Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.然后输出00000000000000000000000000000000........或者很多数字。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by DAAworld** [comment]
chat_model = MiniCPMVChat('/mnt/models/OpenBMB/MiniCPM-V-2_6')
msgs = [{"role": "user", "content": args["query"]}]
inputs = {"image": im_64, "question": json.dumps(msgs)}
answer = chat_model.chat(inputs)
我的代码是这么写的。

- OS:ubuntu 22.04
- Python:3.10
transformers              4.40.0
torch                     2.1.2
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
- CUDA 12.1

**Comment by DAAworld** [comment]
![image](https://github.com/user-attachments/assets/55168b8b-9bf0-47c6-a8d8-1d3b426eb6c2)
![image](https://github.com/user-attachments/assets/aa6bc661-b9a1-4562-b6ab-f76880957ab8)

**Comment by LDLINGLINGLING** [comment]
hello，have you trained the model or modified the vocabulary?

**Comment by DAAworld** [comment]
I haven’t trained, and I haven't modified Vocabular

**Comment by iceflame89** [comment]
`Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained` Just  ignore this warning, it does't matter. 
MiniCPM-V 2.6 do not support output coordinates right now； You can try prompt “输出图中文字”.

**Comment by nw-wf** [comment]
> `Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained` Just ignore this warning, it does't matter. MiniCPM-V 2.6 do not support output coordinates right now； You can try prompt “输出图中文字”.

I also met this problem, I modified with your method, but it didn't work!
