### ISSUE TITLE
[BUG] <title> CPU memory usage keeps increasing

### ISSUE THREAD

**Issue by garvit4512** [OpenBMB/MiniCPM-V#471]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I have a flask app wrapped around the minicpm-2.5 model. The app is being run using pm2. The cpu memory footprint of the process keeps increasing by 50-100 Mb on every request until it eventually crashes.
Below is the code -
    
    app = Flask("loggable")

    model_id = "openbmb/MiniCPM-Llama3-V-2_5"
    model = AutoModel.from_pretrained(model_id, trust_remote_code=True, torch_dtype=torch.float16)
    model = model.to(device='cuda')
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

    def generate_response(image_url, messages):
        try:
            image = Image.open(requests.get(image_url, stream=True).raw)

            with torch.no_grad():
                res = model.chat(
                    image=image,
                    msgs=messages,
                    tokenizer=tokenizer,
                    sampling=True, # if sampling=False, beam_search will be used by default
                    temperature=0.7,
                    max_tokens=150,
                    max_new_tokens=150,
                    max_length=150,
                    # system_prompt='' # pass system_prompt if needed
                )
            image.close()
            torch.cuda.empty_cache()
            return res
        except Exception as e:
            print(f"Error in generate_response: {e}")

    @app.route("/answer", methods=['POST'])
    def answer():
        image_url = data.get('image_url')
        messages = data.get('messages')
        response = generate_response(image_url, messages)
        return jsonify({'response': response}), 200

    if __name__ == "__main__":
        app.run(host='0.0.0.0', port=5000)

### 期望行为 | Expected Behavior

CPU memory should not increase on every request

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by iceflame89** [comment]
Please test  running model in loop other than in flask，to see whether the CPU memory usage keeps increasing
