### ISSUE TITLE
💡 [REQUEST] - Json format output

### ISSUE THREAD

**Issue by WoutDeRijck** [OpenBMB/MiniCPM-V#472]
### 起始日期 | Start Date

8/14/2024

### 摘要 | Summary

Making it possible to force the output to a given JSON scheme.

### 基本示例 | Basic Example

In other cases you can use a package like lm-format-enforcer but they expect only text as input whereas you also want to input images. When extracting entities from an image, i want to get those back in a JSON string.

### 缺陷 | Drawbacks

There would be no drawbacks as this is optionally

**Comment by Cuiunbo** [comment]
We will support it in future

**Comment by WoutDeRijck** [comment]
Lets leave this issue open then :)
