### ISSUE TITLE
[vllm] - <title>使用vllm api server 进行视频推理

### ISSUE THREAD

**Issue by justfuwei** [OpenBMB/MiniCPM-V#479]
### 摘要 | Summary

目前能使用vllm api server 进行视频推理吗，只看到了使用vllm api server进行图片推理的示例

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by HwwwwwwwH** [comment]
暂时还不能，这个要等 vllm 官方也做一些支持才行...

**Comment by HaishengLiang** [comment]
mark
