### ISSUE TITLE
[BUG] 训练速度问题

### ISSUE THREAD

**Issue by JianbangZ** [OpenBMB/MiniCPM-V#481]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我基于V2.5进行全量微调，只微调connector部分，冻结vision & LLM, 一百万张图文数据一个epoch训练时间为5-6小时，这个正常吗？我的机器是8XH100, 已经用了zero1 & flasth attention 2

### 复现方法 | Steps To Reproduce

fintune_ds.sh

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
你好，我感觉这个速度应该是正常的，比我zero2和zero3的速度已经快太多了
