### ISSUE TITLE
[BUG] 请问有在 TextVQA, VizWiz, VQAv2, OK-VQA 上的 few shots 的评估脚本吗？

### ISSUE THREAD

**Issue by davidlight2018** [OpenBMB/MiniCPM-V#492]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

**Comment by YuzaChongyi** [comment]
你好，由于 minicpm2.6 的 pretrain ckpt 没有开源，所以这部分评测代码也没有提供，我们的 few-shot 推理方式可以参考 readme 部分的 icl 推理方式。
