### ISSUE TITLE
请问可以做到输入一段视频，然后找出视频字幕中关键字出现的时间点吗？

### ISSUE THREAD

**Issue by Yhc-777** [OpenBMB/MiniCPM-V#497]
你好打扰啦！想问下目前的模型可以做到传入一段video，然后prompt输入想要搜寻的keywords，最后output出这些keywords出现的时间点么？我这里测试的时候，输出的信息和实际出现的时间是不相关的。辛苦查看下！!

**Comment by o-cyy** [comment]
clip不是能效果很好的完成吗，github有人做好了有现成的

**Comment by wuhongsheng** [comment]
> clip不是能效果很好的完成吗，github有人做好了有现成的
你好，有链接吗

**Comment by o-cyy** [comment]
b站搜clip应用，我记得不了



---Original---
From: ***@***.***&gt;
Sent at: 2024年8月23日(Fri) PM3:26
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OpenBMB/MiniCPM-V] 请问可以做到输入一段视频，然后找出视频字幕中关键字出现的时间点吗？ (Issue #497)




  
clip不是能效果很好的完成吗，github有人做好了有现成的
 你好，有链接吗
