### ISSUE TITLE
无法复现demo里面的结果

### ISSUE THREAD

**Issue by zhudongwork** [OpenBMB/MiniCPM-V#498]
按照README中的demo运行
<img width="655" alt="8734b16ffce7a288c1d0cbc4fb729ae" src="https://github.com/user-attachments/assets/6a33f27d-b2da-4271-a7e8-c3b3588d20f0">

但是得到了不一样的结果，重复跑几次结果还是一样的：
<img width="713" alt="0650be6d2a75a3429b9fb83d2103701" src="https://github.com/user-attachments/assets/ec218230-12ad-40d1-890a-b18644bb624e">

这是我的代码：
<img width="644" alt="f6c3e0fbad102294594bcc846007f6e" src="https://github.com/user-attachments/assets/01b9cc5a-7278-401e-ae81-70326899ff5a">

**Comment by david9ml** [comment]
我尝试问一个问题，第二天也是不一样的， 每次同一个问题答案是不一样的。

**Comment by zhudongwork** [comment]
> Question not the same

问题都是一样的啊

**Comment by Cuiunbo** [comment]
哦哦， 抱歉， 看成了第二轮的问题无法复现。您可讲您的 环境发出， 方便我们复现其中可能的问题

**Comment by zhudongwork** [comment]
> 哦哦， 抱歉， 看成了第二轮的问题无法复现。您可将您的 环境发出， 方便我们复现其中可能的问题

环境就是按照安装步骤搭的，同时我也在你们提供的hf space上也测了同样的question，依然得不到正确的答案
