### ISSUE TITLE
https://openbmb.vercel.app/minicpm-v-2 挂掉了吗？打不开了。

### ISSUE THREAD

**Issue by ljch2018** [OpenBMB/MiniCPM-V#50]
<img width="1100" alt="image" src="https://github.com/OpenBMB/MiniCPM-V/assets/22562546/32514f40-340a-49f2-be7e-182ae425b806">

**Comment by yiranyyu** [comment]
已恢复

**Comment by ljch2018** [comment]
@yiranyyu 还是挂的。

**Comment by LyonWang95** [comment]
可以访问github，但是不能访问博客

**Comment by ljch2018** [comment]
@yiranyyu 深圳地区可访问，北京地区访问不了。

**Comment by yiranyyu** [comment]
排查到可能是服务器的可达性问题，我们正在积极解决中。更加完整的技术报告近期也会在 Arxiv 等平台公开，希望能对大家有所帮助！

**Comment by cloudyuyuyu** [comment]
成都地区也无法访问，

![image](https://github.com/OpenBMB/MiniCPM-V/assets/16486492/3ceaa7ae-5279-472d-8899-d9f6d5f84454)

**Comment by IcebergKnight** [comment]
vercel.app 被DNS 污染，改下hosts
