### ISSUE TITLE
为了方便技术交流，拉了一个多模态大模型技术交流群，有需要的大家可以加入

### ISSUE THREAD

**Issue by feihuamantian** [OpenBMB/MiniCPM-V#501]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

你可以微信扫码加入，也可以加我微信拉您入群：yx116169
![20240822-142406](https://github.com/user-attachments/assets/7458ec62-c6c8-40af-a25a-c2179be95b29)

### 期望行为 | Expected Behavior

1

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

1

**Comment by wangyuc** [comment]
能否更新一下二维码
