### ISSUE TITLE
base model + lora vs merged

### ISSUE THREAD

**Issue by chongkuiqi** [OpenBMB/MiniCPM-V#502]
Thanks for your great work ! 
    After LoRA fine-tune, I tried the following two ways for Inference:
(1) base model + lora: Load the base model and LoRA adapters respectively,  then for inference;
(2)merge : Merge the base model and LoRA adapters into a standalone model, use the standalone model for inference

However, the two methods produce different results, did anyone ever encountered such problem ?

**Comment by LDLINGLINGLING** [comment]
Hello, have you set the sampling parameters? If you want to compare the model of merge lora with the model of mounted lora, you should set do_sample=false, so as to remove the randomness caused by the sampling parameters.

**Comment by chongkuiqi** [comment]
> Hello, have you set the sampling parameters? If you want to compare the model of merge lora with the model of mounted lora, you should set do_sample=false, so as to remove the randomness caused by the sampling parameters.

Thanks for your reply. Problem solved, and it is the data type used in model of merge lora. 
(1) model of mounted lora: both bf16 and fp16 for inference can produce right results.
(2) model of merge lora: if using bf16 to save merged model,  either bf6 or fp16 for inference will produce wrong results. Using fp16 for saving merged model and bf16 for inference also be wrong. However, using fp16 for saving and fp16 for inference, the result is the same as the model of mounted lora.

I don't know what cause this, maybe my LoRA adapters are more sensitive to bf16 and fp16.

**Comment by LDLINGLINGLING** [comment]
ok，Thank you for your feedback
