### ISSUE TITLE
[BUG] <title>The bug of VLLM for minicpmv

### ISSUE THREAD

**Issue by Mysnake** [OpenBMB/MiniCPM-V#504]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I run the demo of vllm for minicpmv with GPU 0,but this error occured.
[rank0]:     ret = input.softmax(dim, dtype=dtype)
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB. GPU 0 has a total capacity of 23.55 GiB of which 1.87 GiB is free. Process 1809110 has 4.37 GiB memory in use. Including non-PyTorch memory, this process has 17.29 GiB memory in use. Of the allocated memory 16.75 GiB is allocated by PyTorch, and 95.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W822 09:49:35.946254597 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())

### 期望行为 | Expected Behavior

I want to modify the device as others.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

How can I modified the device.

**Comment by HwwwwwwwH** [comment]
You can decrease `max_model_len` to `2048` when initializing `vllm.LLM`.
