### ISSUE TITLE
I want to set up system prompt during training.

### ISSUE THREAD

**Issue by orderer0001** [OpenBMB/MiniCPM-V#508]
The role cannot be set to system during training, but system must be set during inference. How can this be unified? What should I do if I also set system during training? Now training is to put the content of the system into the content of the user, so for inference How should I set the content of the system?

**Comment by LDLINGLINGLING** [comment]
hello，During the training process, if you want to modify systerm, you can modify the following functions in the dataset.py file.
![image](https://github.com/user-attachments/assets/28a36526-3407-45b7-9c71-10f1ac40a8ef)
