### ISSUE TITLE
V2.6的视觉token密度

### ISSUE THREAD

**Issue by dingtine** [OpenBMB/MiniCPM-V#511]
没有看到如何提升了密度，还是通过perceiver resampler方法吗？

**Comment by Cuiunbo** [comment]
是的

**Comment by dingtine** [comment]
想请教下，这种方法跟其他压缩方法，比如mobilevlm的attention方法有做对比吗，有消融实验吗。
想请教你们，做个选型。

**Comment by dingtine** [comment]
> 是的

想请教下，这种方法跟其他压缩方法，比如mobilevlm的attention方法有做对比吗，有消融实验吗。
想请教你们，做个选型。

**Comment by Cuiunbo** [comment]
未与mobilevlm方法进行过严格消融
