### ISSUE TITLE
lora方式微調後的模型在使用的時候出現的警告

### ISSUE THREAD

**Issue by sam880717** [OpenBMB/MiniCPM-V#512]
請問微調過後的模型搭配以下程式碼在inference的時候會出現"Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained."是正常的嗎? 會不會對生成結果造成影響?

```
from peft import PeftModel
from transformers import AutoModel
model_type=  "openbmb/MiniCPM-V-2_6"   # or openbmb/MiniCPM-Llama3-V-2_5 , openbmb/MiniCPM-V-2
path_to_adapter="path_to_your_fine_tuned_checkpoint"

model =  AutoModel.from_pretrained(
        model_type,
        trust_remote_code=True
        )

lora_model = PeftModel.from_pretrained(
    model,
    path_to_adapter,
    device_map="auto",
    trust_remote_code=True
).eval().cuda()
```

**Comment by LDLINGLINGLING** [comment]
这个你可以尝试使用web_demo.py进行推理，如果输出没有问题就可以。如果输出有问题，就将原有的模型路径下的
![image](https://github.com/user-attachments/assets/c894176b-d77d-4dcc-8f51-12e8c9567bb5)
这几个文件替换到新模型路径下。
