### ISSUE TITLE
💡 [REQUEST] - 请教如何基于这个模型来微调训练古籍文字或手写字识别？

### ISSUE THREAD

**Issue by fishfree** [OpenBMB/MiniCPM-V#514]
这个大模型OCR能力超强！我该怎么组织语料和如何训练呢？只需要专注提升OCR能力。先谢过各位大佬了！

**Comment by LDLINGLINGLING** [comment]
你可以看一下我这个教程，方法是类似的，如果你不需要文字定位，就不要文字定位框的数据https://modelbest.feishu.cn/wiki/HLRiwNgKEic6cckGyGucFvxQnJw?from=from_copylink

**Comment by Aues6uen11Z** [comment]
@LDLINGLINGLING 您好，请问MiniCPM-V2.6也采用和2.5相同的文本定位格式吗？现在公布的模型有进行文本定位的训练吗？若有如何让它输出文本坐标？
