### ISSUE TITLE
💡 [REQUEST] - <title>minicpm vlm with small llm for fast inference on mobile device

### ISSUE THREAD

**Issue by perp** [OpenBMB/MiniCPM-V#517]
### 起始日期 | Start Date

08/26/2024

### 摘要 | Summary

how to add a small large language model like qwen 0.5b or mobilellm in minicpm?
1、add a trained model like qwen 0.5b or mobilellm 
2、disill a large llama 7b to small one

### 基本示例 | Basic Example

1、add a trained model like qwen 0.5b or mobilellm 
2、disill a large llama 7b to small one

### 缺陷 | Drawbacks

no

**Comment by iceflame89** [comment]
Please read our technical report [MiniCPM-V: A GPT-4V Level MLLM on Your Phone
](https://arxiv.org/abs/2408.01800) for the detail of how to training.
