### ISSUE TITLE
[BUG] <title>minicpm-v2.6无法输出准确坐标

### ISSUE THREAD

**Issue by heart-du** [OpenBMB/MiniCPM-V#518]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

根据提供的图片，第四张照片展示了最清晰、细节最丰富的画面。这张图片展现了树木和建筑物的纹理和颜色，具有高分辨率，没有模糊或扭曲。叶子、树皮和建筑表面的细节都清晰可见，表明该图片是用质量较高的相机拍摄的，可能是使用了较慢的快门速度以捕捉更多的光线和细节。
要裁剪这张图片以突出树干和树叶，同时最小化背景中建筑物的干扰，可以选择的矩形框应该将焦点放在自然元素上。考虑到这一点，适合的矩形框的坐标将是：
- 左下角：大约在 (10,640, 389
- 右上角：大约在527,580
这些坐标将框住主要的树干和周围的树叶，同时仍然包括一些背景，以保持构图的深度。

### 运行环境 | Environment

```Markdown
- OS:ubuntu
- Python:3.9
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by heart-du** [comment]
回答的格式不是准确的坐标格式。

**Comment by laoShuaiGe** [comment]
你训练数据的坐标归一化了吗？
