### ISSUE TITLE
MiniCPM-V 2.6 int4 24G显存不够用，model.cuda()会OOM

### ISSUE THREAD

**Issue by MaxKinny** [OpenBMB/MiniCPM-V#525]
文档说推理MiniCPM-V 2.6 int4只需要7GB，但我24G的OOM

**Comment by LDLINGLINGLING** [comment]
仅加载模型大概确实只要7G，但是推理过程存在上下文的kvcach，可能会有很大的增长

**Comment by dfrrk** [comment]
估计视频文件时间太长了，我33秒的视频处理最高峰的时候就占用了15G显存

**Comment by tc-mb** [comment]
> 文档说推理MiniCPM-V 2.6 int4只需要7GB，但我24G的OOM

hi，你可以测试一下，使用过程中的实时显存占用，观察一下是一开始就不足的，还是使用过程中逐渐增加变的不够用的。

如果是使用过程中不断增加的显存消耗，可以看下是很快就升高了显存还是经过一段时间才不够用的。

如果很快显存就变的不够用了，我们会检查是否代码可以进行实时释放显存的方法。
