### ISSUE TITLE
请问是否可以将vpm和resampler 这2个模型转为tensorrt来加速推理呢?

### ISSUE THREAD

**Issue by wu1143100799** [OpenBMB/MiniCPM-V#526]
请问是否可以将vpm和resampler 这2个模型转为tensorrt来加速推理呢?

**Comment by tc-mb** [comment]
可以的，我们是开源模型和代码，你可以按你的需要修改代码来适配你需要的环境。

**Comment by Single430** [comment]
> 请问是否可以将vpm和resampler 这2个模型转为tensorrt来加速推理呢?

这两个模块的耗时貌似并不是大头
