### ISSUE TITLE
我在做垂直领域应用，想先让模型通过预训练学一些文档材料，再进行图文对话微调，这个怎么操作？

### ISSUE THREAD

**Issue by zpge** [OpenBMB/MiniCPM-V#528]
RT

**Comment by LDLINGLINGLING** [comment]
那你可以考虑先对qwen做纯文本训练，然后进行图文对训练

**Comment by SirLPS** [comment]
> 考虑先对qwen做纯文本训练，然后进行图文对训练
图文预训练可行吗？例如图文对直接在vlm上做预训练，然后再用图文对在vlm上做instruct sft
