### ISSUE TITLE
[BUG] <title>MiniCPM-V-2_6 评估指标没有对齐

### ISSUE THREAD

**Issue by luyao-cv** [OpenBMB/MiniCPM-V#529]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我用VLMEvalKit去评测MiniCPM-V-2_6 8B的模型，textvqa的结果是78.372，OCRbench的结果是839分，与你github上的textvqa80.1和OCRbench852有出处。请问是哪里不对吗？

**Comment by lihytotoro** [comment]
您好，感谢您的提问！
我们的模型在 TextVQA val 上的分数是采用 eval_mm 目录中的 vqaeval 进行评测，请参考 [https://github.com/OpenBMB/MiniCPM-V/blob/main/eval_mm/README_zh.md#vqadataset](url) 进行评测。
OCRBench 上的分数是采用 eval_mm 目录中的 vlmevalkit 进行评测的，请参考 https://github.com/OpenBMB/MiniCPM-V/blob/main/eval_mm/README_zh.md#opencompass 进行评测。我们可以确保在 8 卡情况下复现出同样的结果。
