### ISSUE TITLE
minicpm-v-2.6在OpenCompass评测结果65.2是怎么得到的？

### ISSUE THREAD

**Issue by ninth99** [OpenBMB/MiniCPM-V#531]

**Comment by lihytotoro** [comment]
您好，感谢您的提问！
我们的模型在 opencompass 各项 benchmark 上的分数都是基于 eval_mm/vlmevalkit 目录进行评测的，具体评测方法请参考 [https://github.com/OpenBMB/MiniCPM-V/blob/main/eval_mm/README_zh.md#opencompass](url)。我们可以确保在 8 卡情况下复现出同样的结果。
以下是我们在评测时使用的环境：
- A100 × 8
- torch==2.2.0
- transformers==4.43.3
- flash-attn==2.5.9.post1
