### ISSUE TITLE
可以只微调llama layers吗?

### ISSUE THREAD

**Issue by wwwwar3com** [OpenBMB/MiniCPM-V#532]
我试了一下,报错说image 为空

**Comment by LDLINGLINGLING** [comment]
你说的llama layers时说只微调llm模型么？

**Comment by wwwwar3com** [comment]
就是一些没有图片的问答
finetune script  好像是默认有图片的, 或者是我没找到

我之前看paligama的finetune可以freeze vision layers,
然后只微调gemma-2b layer

不知道minicpm 可不可以

**Comment by LDLINGLINGLING** [comment]
可以的，在finetune_ds和finetune_lora的脚本中都有vision_tune的参数，设置为false就行了
