### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by 2013358072** [OpenBMB/MiniCPM-V#534]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [ ] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我上传了一个15min 大约200m的视频，他出现了一个错误
Sizes of tensors must match except in dimension 1.  Expected size 123 but got size 122 for tensor number 1 in the list.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ecoli-hit** [comment]
请问您找到解决方法了吗，我也遇到了相同的问题。
