### ISSUE TITLE
[BUG] <title>minicpm-v-2.6和LLaVA-OneVision的区别是什么？

### ISSUE THREAD

**Issue by AbbottKilig** [OpenBMB/MiniCPM-V#536]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我发现minicpm-v-2.6和LLaVA-OneVision的实现非常相似，有理由认为minicpm-v-2.6就是LLaVA-OneVision，或者只在其上面做了conitnue training，麻烦可以介绍一下两者的差异吗

### 期望行为 | Expected Behavior

我发现minicpm-v-2.6和LLaVA-OneVision的实现非常相似，有理由认为minicpm-v-2.6就是LLaVA-OneVision，或者只在其上面做了conitnue training，麻烦可以介绍一下两者的差异吗

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
你好，minicpm-v-2.6和LLaVA-OneVision存在很多差异，其中包括并不仅限于：
