### ISSUE TITLE
有关lora finetune显存问题

### ISSUE THREAD

**Issue by zhaoyangwei123** [OpenBMB/MiniCPM-V#537]
在该文档中https://github.com/OpenBMB/MiniCPM-V/tree/main/finetune，
Fine-tuning Method	GPUs: 2	GPUs: 4	GPUs: 8
LoRA Fine-tuning	14.4 GiB	13.6 GiB	13.1 GiB
Full Parameters Fine-tuning	16.0 GiB	15.8 GiB	15.63GiB
里面讲述了利用lora finetune在8卡情况下显存使用只有13个G左右，但是真实情况下我在8张3090上面训练如果使用deepspeed zero2的话会超显存，使用zero3的情况下显存占用也在17个G左右，我的图片大小是640*640，请问这是什么原因呢？

**Comment by LDLINGLINGLING** [comment]
你好，因为图片数量、分辨率、文本长度都对显存需求有巨大影响，未方便用户，该文档中注明的主要是最低显存要求
