### ISSUE TITLE
[BUG] <title>RuntimeError: Expected index [1728, 4096] to be smaller than self [2048, 4096] apart from dimension 0 and to be smal ler size than src [864, 4096]

### ISSUE THREAD

**Issue by laoShuaiGe** [OpenBMB/MiniCPM-V#538]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Previous issue: #345 by [aoji0606](https://github.com/OpenBMB/MiniCPM-V/issues?q=is%3Aissue+author%3Aaoji0606)
I saw the same issue remain unresolved, but was closed for some reason. So reopen it for help. Thank you in advance for any suggestions.

### 期望行为 | Expected Behavior

Training pipeline crashes due to the issue mentioned above.

### 运行环境 | Environment

```Markdown
- OS: 20.04
- Python: 3.10
- Transformers: 4.40
- PyTorch: 2.3
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
hello，check if there is a problem with your max_model_length and data construction
