### ISSUE TITLE
MiniCPM-V 2.6在多语种文字问答基准MTVQA上的表现

### ISSUE THREAD

**Issue by JohnTang93** [OpenBMB/MiniCPM-V#539]
可以测评一下MiniCPM-V 2.6在MTVQA上的表现嘛，MiniCPM-V 2.5之前是开源模型中最优的，不知道MiniCPM-V 2.6在多语种文字理解上表现如何

**Comment by Cuiunbo** [comment]
您好， 并未评测， 欢迎尝试
