### ISSUE TITLE
Android端部署

### ISSUE THREAD

**Issue by xiahc** [OpenBMB/MiniCPM-V#542]
我参考https://github.com/OpenBMB/mlc-MiniCPM进行Android端部署。

执行cmake ..时，一直显示如下信息，持续几个小时：
-- Hide private symbols
-- TVM_HOME: /mnt/mlc/mlc-MiniCPM-main/3rdparty/tvm

请帮忙确认这是否是正常情况，如有问题如何改进。
谢谢！

**Comment by LDLINGLINGLING** [comment]
你好，mlc方案我们已经不维护

**Comment by xiahc** [comment]
目前支持的可以在Android端部署的方案是什么？谢谢。
