### ISSUE TITLE
MiniCPM-Llama3-V 2.5 vs 2.6

### ISSUE THREAD

**Issue by kotaxyz** [OpenBMB/MiniCPM-V#544]
i have tested both models on huggingface official space i get surprising results that the 2.5 version always get better results have anyone got similar results and why , all benchmarks show that 2.6 is better but real test show something else

![Screenshot (267)](https://github.com/user-attachments/assets/2c21fea5-aa73-48a2-b401-d175840b5f20)
![Screenshot (268)](https://github.com/user-attachments/assets/81668d90-615b-4a0d-b7d9-76efa350e45a)

**Comment by Cwoner** [comment]
我也有同样的感觉，可能是不同的语言模型的原因吧

**Comment by Cuiunbo** [comment]
I've found that the model doesn't seem to be robust enough, 
and the input is better capitalized to achieve a more optimal level
@kotaxyz
