### ISSUE TITLE
微调MiniCPM-v2.6以获得更好的单图片日文OCR和推理能力

### ISSUE THREAD

**Issue by ZijianCHEN-infodeliver** [OpenBMB/MiniCPM-V#546]
我最近正在尝试微调MiniCPM-v2.6以获得更好的单图片日文OCR和推理能力，我想了解MiniCPM-v2.6在训练时使用了哪些日文数据集，或者对于微调提升日语能力，有什么推荐的数据集吗？

另外，我想了解您是否有关于MiniCPM-v2.6多语言或者日语能力的测试基准（如何评价MiniCPM-v2.6的多语言OCR和理解能力）

**Comment by Cuiunbo** [comment]
您好， 2.6 未进行 多语言能力ocr 测试
