### ISSUE TITLE
[BUG] <title>自己准备的数据集，在加载的时候，出错：image start token != image end tokens，data fetch error

### ISSUE THREAD

**Issue by XHB-ZMM** [OpenBMB/MiniCPM-V#548]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1

### 期望行为 | Expected Behavior

1

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

数据集的格式跟官方提供的相同
![image](https://github.com/user-attachments/assets/cc3091e5-ab4a-4ad2-b049-d8ad336cf6ae)

**Comment by XHB-ZMM** [comment]
出问题的代码就在这：
![Uploading image.png…]()

**Comment by XHB-ZMM** [comment]
![image](https://github.com/user-attachments/assets/1e15660f-fd27-4cb8-9367-8ce6de0f2dc8)

**Comment by XHB-ZMM** [comment]
用的模型是MiniCPM-Llama3-V-2_5，LLM_TYPE="llama3" ，2张卡一起跑，lora微调，MODEL_MAX_Length=4096，

**Comment by LDLINGLINGLING** [comment]
请问你是什么卡，a100么？

**Comment by XHB-ZMM** [comment]
> 请问你是什么卡，a100么？
A800 80G

**Comment by LDLINGLINGLING** [comment]
![image](https://github.com/user-attachments/assets/fa8be732-50b5-4102-901b-129d823e7862)
根据我和另外一位用户的测试，增加这个代码后，就不会出现这个问题，希望能够帮到你

**Comment by XHB-ZMM** [comment]
> ![image](https://private-user-images.githubusercontent.com/47373076/363548165-7bc90ee4-037b-45d0-bee1-e027bc1ad12b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDY1MzEsIm5iZiI6MTcyNTI0NjIzMSwicGF0aCI6Ii80NzM3MzA3Ni8zNjM1NDgxNjUtN2JjOTBlZTQtMDM3Yi00NWQwLWJlZTEtZTAyN2JjMWFkMTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAzMDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNTJmNGNiOGUxMDkyYjliZDM4OTZmMDEwMjUzY2ZhZjRlZDc4NWNmZmE0MjNiNDQ0ZTJlNzUyZTU5ZDUzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aORBX96thVd2Cw4M8UuRb5NZ1eOSjUjZDZgU3jePaC0)
> 
> 根据我和另外一位用户的测试，增加这个代码后，就不会出现这个问题，希望能够帮到你

好的，感谢感谢
