### ISSUE TITLE
💡 [REQUEST] - 为什么没有模型的定义代码？

### ISSUE THREAD

**Issue by jiaowei-it** [OpenBMB/MiniCPM-V#551]
### 实现PR | Implementation PR

只有fineture.py （下面代码）里能看到包含一个vpm和llm。 
没有https://huggingface.co/openbmb/MiniCPM-V-2_6/blob/main/modeling_minicpmv.py

    if not training_args.tune_vision:
        model.vpm.requires_grad_(False)
    if not training_args.tune_llm:
        model.llm.requires_grad_(False)

### 相关Issues | Reference Issues

无

### 摘要 | Summary

包含模型的代码

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

不方便

### 未解决问题 | Unresolved questions

无

**Comment by LDLINGLINGLING** [comment]
模型定义的代码在huggingface上，https://huggingface.co/openbmb/MiniCPM-V-2_6/tree/main
