### ISSUE TITLE
[BUG] <title>是否考虑支持华为910B 300I这种部署  ？ 支持NPM推理及训练

### ISSUE THREAD

**Issue by ipv6ok** [OpenBMB/MiniCPM-V#554]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

没发现有NPM部署说明

### 期望行为 | Expected Behavior

期望支持国产显卡

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by nakairika** [comment]
你好，我是华为适配这个模型的开发，正巧看到你的issue。300I已支持mincpmv的推理，详情可以联系和你对接的华为工程师:）

**Comment by nakairika** [comment]
你好，我是华为的开发，正巧看到你的issue，300I已支持minivpmv2和minicpmllama3v2.5的加速推理，详情可以询问对接你的华为工程师:)

**Comment by Cuiunbo** [comment]
您好， 由于缺乏人力， 我们暂时并未扩展支持。
