### ISSUE TITLE
Inference after lora finetuning

### ISSUE THREAD

**Issue by tristan279** [OpenBMB/MiniCPM-V#557]
i finetuned miniCPM-v-2_6 with this dataset format:

`"id":str(i),
      "image":{"<image_upper>":f"path_upper","<image_lower>":f"path_lower"},
      "conversations":  [{"role": "user", "content": f"<image_upper><image_lower>{prompt}"},{"role":"assistant","content":text}]`

how do i invoke the model with the exact same prompt, using transformers library? prompt format was not given in the finetuning example

**Comment by LDLINGLINGLING** [comment]
https://modelbest.feishu.cn/wiki/HvfLwYzlIihqzXkmeCdczs6onmd?from=from_copylink，please check this blog
