### ISSUE TITLE
模型不支持中文？还有批量跑多个图片预测时会缓存前面的结果？

### ISSUE THREAD

**Issue by chuangzhidan** [OpenBMB/MiniCPM-V#56]
遍历图片时总是复制前面的输出，是因为跑多个图片预测时会缓存前面的输出结果？
而单独对每个图片进行推断，中文ocr效果又很差。是不支持中文ocr识别吗

**Comment by iceflame89** [comment]
请问提供使用的模型名称，图像，以及promot
MiniCPM-V 2.0具备较好的中英文OCR能力，MiniCPM-V 1.0及OmniLMM-12B OCR能力较弱

**Comment by chuangzhidan** [comment]
模型：MiniCPM-V 2.0

**Comment by iceflame89** [comment]
抱歉，模型代码中有个bug导致调用chat后input msgs会被修改，现已修复，请拉取最新文件[modeling_minicpmv.py](https://huggingface.co/openbmb/MiniCPM-V-2/blob/main/modeling_minicpmv.py)。

关于中文OCR，目前全文输出能力确实有所不足，提取局部信息能力还不错，文字信息提取任务推荐使用beam search解码(sampling=False)
```python
res, context, _ = model.chat(
    image=image,
    msgs=msgs,
    context=None,
    tokenizer=tokenizer,
    sampling=False
)
print(res)
```
<img width="628" alt="Screenshot 2024-04-19 at 15 03 46" src="https://github.com/OpenBMB/MiniCPM-V/assets/5380770/291b4b74-49b1-4fd2-9d89-9072ef649686">

**Comment by chuangzhidan** [comment]
beam search解码的原理或原因是什么， sampling=False后是用的什么解码策略。按照你的建议的确变好了：）

**Comment by iceflame89** [comment]
sampling=False具体实现见https://huggingface.co/openbmb/MiniCPM-V-2/blob/main/modeling_minicpmv.py#L336-L352

微调代码已经放出，请关注本repo首页更新日志～

**Comment by mobguang** [comment]
@iceflame89 

你好，请教一下，我在Mac M2的机器上运行PYTORCH_ENABLE_MPS_FALLBACK=1 python3.11 web_demo_2.5.py --device mps（模型是MiniCPM-Llama3-V-2_5），Decode Type选择Sampling和Beam Search会有不同的结果。如果是Sampling返回的结果不可用，请见截图。

所以对于Decode Type的选择，何时用Sampling，何时用Beam Search，谢谢。

![image](https://github.com/OpenBMB/MiniCPM-V/assets/519028/daacc31e-3706-4c90-9c4d-45c29d193e6f)
