### ISSUE TITLE
💡 [REQUEST] - <title>minicpmv2.5的量化支持，autoGPTQ，autoAWQ

### ISSUE THREAD

**Issue by ZHANG-SH97** [OpenBMB/MiniCPM-V#560]
### 摘要 | Summary

有考虑支持minicpmv2.5模型的量化吗？autoGPTQ,autoAWQ模型

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

### 未解决问题 | Unresolved questions

minicpmv2.5考虑支持autoGPTQ和autoAWQ  量化吗？

**Comment by LDLINGLINGLING** [comment]
你好，已经适配了awq，https://modelbest.feishu.cn/wiki/PAsHw6N6xiEy0DkJWpJcIocRnz9?from=from_copylink，请看这个地址
