### ISSUE TITLE
[QUESTION] <smaller language model>

### ISSUE THREAD

**Issue by ztianlin** [OpenBMB/MiniCPM-V#562]
请问如果需要极致的端上性能，是否可以使用参数量更小的语言模型呢？以及siglip是否可以换更轻量的图像编码器呢？如果要切换的话，该如何训练和部署呢，谢谢！

**Comment by LDLINGLINGLING** [comment]
你好，从头训练代价昂贵，可以基于我们的minicpm2.0进行进一步训练，模型参数量下降很多
