### ISSUE TITLE
[BUG] <title>whether it is possible to deploy minicpmv2.5 on Android based on llama.cpp (using Qualcomm GPU for inference)?

### ISSUE THREAD

**Issue by My-captain** [OpenBMB/MiniCPM-V#565]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 期望行为 | Expected Behavior

May I ask whether it is possible to deploy minicpmv2.5 on Android based on llama.cpp (using Qualcomm GPU for inference)?

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by theoctopusride** [comment]
I would like to know about the Qualcomm NPU for inference. +1

**Comment by tc-mb** [comment]
First of all, I'm sorry that I was busy with other projects before and I responded a little late.
Due to the manpower of our team, we cannot support Qualcomm NPU yet.

**Comment by My-captain** [comment]
Got it, thanks for your response.
