### ISSUE TITLE
symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by ZhonghaoLu** [OpenBMB/MiniCPM-V#571]
I try to build on Mac, and follow the instructions and get a similar error.

'''
# github.com/ollama/ollama
/opt/homebrew/Cellar/go/1.22.6/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
Undefined symbols for architecture arm64:
  "_cblas_sgemm", referenced from:
      ggml_backend_blas_graph_compute(ggml_backend*, ggml_cgraph*) in libllama.a[9](ggml-blas.cpp.o)
      ggml_backend_blas_graph_compute(ggml_backend*, ggml_cgraph*) in libllama.a[9](ggml-blas.cpp.o)
  "_openblas_set_num_threads", referenced from:
      ggml_backend_blas_graph_compute(ggml_backend*, ggml_cgraph*) in libllama.a[9](ggml-blas.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
'''

_Originally posted by @WangchenhaoHZ in https://github.com/OpenBMB/MiniCPM-V/issues/411#issuecomment-2274796938_

**Comment by LDLINGLINGLING** [comment]
hello，I think you should use model by ollama
