### ISSUE TITLE
是否可以透漏in-context learning是怎么训练的吗

### ISSUE THREAD

**Issue by xushilin1** [OpenBMB/MiniCPM-V#574]
你好，我看到minicpm-v2.6有非常强的in-context learning的能力，你们能否提供一份技术报告，透露一下具体是怎么训练的呢。

**Comment by luxinglong** [comment]
感觉上保留足够的图文交织数据就可以具备ICL能力，在SFT阶段加入一些ICL的指令数据应该会更好一些
