### ISSUE TITLE
[BUG] <title> problem when awq self-quantization

### ISSUE THREAD

**Issue by chongkuiqi** [OpenBMB/MiniCPM-V#576]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Thanks for your amazing work !!!
I am applying awq quantization to my fine-tuned MiniCPM-V-2_6 model according to [MiniCPM-V 2.6 Quantization Tutorial](https://modelbest.feishu.cn/wiki/YvsPwnPwWiqUjlkmW0scQ76TnBb), however, the loaded alpaca dataset structure seems to be something wrong, it should be dict not list,  the error as follows:
```
raceback (most recent call last):
  File "/home/haige/ckq/MiniCPM_Series_Tutorial/MiniCPMV2_6_awq/quantize.py", line 64, in <module>
    model.quantize(tokenizer, quant_config=quant_config, calib_data=load_alpaca())
  File "/home/haige/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/haige/miniconda3/envs/vllm/lib/python3.10/site-packages/awq/models/minicpmv.py", line 318, in quantize
    self.quantizer = CPMVAwqQuantizer(
  File "/home/haige/miniconda3/envs/vllm/lib/python3.10/site-packages/awq/quantize/quantizer.py", line 69, in __init__
    self.modules, self.module_kwargs, self.inps = self.init_quant(
  File "/home/haige/miniconda3/envs/vllm/lib/python3.10/site-packages/awq/models/minicpmv.py", line 83, in init_quant
    for k, v in samples.items():
AttributeError: 'list' object has no attribute 'items'
```

The code of  loading alpaca dataset is [MiniCPM_Series_Tutorial/MiniCPMV2_6_awq/quantize.py](https://github.com/LDLINGLINGLING/MiniCPM_Series_Tutorial/blob/main/MiniCPMV2_6_awq/quantize.py), line 56
```def load_alpaca():
    data = load_dataset('/home/haige/ckq/AutoAWQ/alpaca', split="train")

    # concatenate data
    def concatenate_data(x):
        msgs=[{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": x['input']},{"role": "system", "content": x['output']}]
        data=tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
        return {"text": data}
    
    concatenated = data.map(concatenate_data)
    return [text for text in concatenated["text"]][:1000]
```

The code of throwing error is [awq/models/minicpmv.py](https://github.com/LDLINGLINGLING/AutoAWQ/blob/main/awq/models/minicpmv.py), line 83
```
    modules[0] = Catcher(modules[0])
    for k, v in samples.items():
        if isinstance(v, (torch.Tensor, nn.Module)):
            samples[k] = move_to_device(v, best_device)
    try:
        self.model(**samples)
    except ValueError:  # work with early exit
        pass
    finally:
        for k, v in samples.items():
            if isinstance(v, (torch.Tensor, nn.Module)):
                samples[k] = move_to_device(v, "cpu")
    modules[0] = modules[0].module  # restore
```

Could you please provide some helps ? 

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
hello，if you have not train our model，I think you can use the awq model https://www.modelscope.cn/models/linglingdan/MiniCPM-V_2_6_awq_int4

**Comment by chongkuiqi** [comment]
> hello，if you have not train our model，I think you can use the awq model https://www.modelscope.cn/models/linglingdan/MiniCPM-V_2_6_awq_int4

Thanks for your reply, but the model has been trained on my dataset.

**Comment by LDLINGLINGLING** [comment]
hello，Please watch the tutorial again https://modelbest.feishu.cn/wiki/YvsPwnPwWiqUjlkmW0scQ76TnBb?from=from_copylink

**Comment by chongkuiqi** [comment]
> hello，Please watch the tutorial again https://modelbest.feishu.cn/wiki/YvsPwnPwWiqUjlkmW0scQ76TnBb?from=from_copylink

Thanks very much! It works ! 
And I still have a question, the MiniCPM-V-2_6 is a vision-language model, but the calib dataset alpaca is text-only without images, is that ok ?

**Comment by LDLINGLINGLING** [comment]
Theoretically it's ok, because the language model in minicpmv is not specifically designed to accept the position of the image. In addition, I did a loose test and the effect was good. There is also an awq method for quantifying image and text pairs on my github, but it cannot quantify a large amount of data, so I still recommend this method that only quantifies language.

**Comment by chongkuiqi** [comment]
> Theoretically it's ok, because the language model in minicpmv is not specifically designed to accept the position of the image. In addition, I did a loose test and the effect was good. There is also an awq method for quantifying image and text pairs on my github, but it cannot quantify a large amount of data, so I still recommend this method that only quantifies language.

Get it. Thanks again.
