### ISSUE TITLE
Finetuning issue

### ISSUE THREAD

**Issue by ragesh2000** [OpenBMB/MiniCPM-V#577]
I have a doubt regarding finetuning. My dataset contains images and text which are not familiar to model. So while finetuning should i keep the parameters tune_llm, tune_vision as true or false? By keeping it false the performance of my finetuned model was just as the base model. Any help is appreciated.

**Comment by 2U1** [comment]
It would be better for tuning the full-model if you need to fit your model to specific domain.

**Comment by ragesh2000** [comment]
What i actually meant is, when do we need to keep those parameters to True? Only when we needed full-model tuning? If iam doing lora finetuning with some custom images do i need to keep it as true?

**Comment by 2U1** [comment]
When using LoRA, the you should make the `tune_llm` to False. Otherwise It would not work.
`tuen_vision` is an option, but it would show a better performance in many cases when you set to True.
