### ISSUE TITLE
[BUG] finetune minicpm error

### ISSUE THREAD

**Issue by jackyjinjing** [OpenBMB/MiniCPM-V#578]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![img_v3_02en_d3458080-6779-4388-b180-c4e60e4f757g](https://github.com/user-attachments/assets/e0773c2b-8ba2-41fb-9a40-abaf962663c0)

I encountered an error while fine-tuning MinicPM.
I found that issue #553 is similar to this one, but it was closed without any fixes, resulting in me encountering this problem as well.

### 期望行为 | Expected Behavior

no error
_No response_

### 复现方法 | Steps To Reproduce
run fine-tuning sciprt: sh sh finetune_ds.sh
_No response_

### 运行环境 | Environment

```Markdown
- OS: 
- Python:3.10.14
- Transformers:4.36.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by LDLINGLINGLING** [comment]
hello ，please show me your dataset json。

**Comment by qyc-98** [comment]
We fix the code, please try again. Thanks

**Comment by natsoe7** [comment]
***@***.***
