### ISSUE TITLE
想学习【MLLM多模态】快加学习交流群

### ISSUE THREAD

**Issue by km1994** [OpenBMB/MiniCPM-V#583]
### 摘要 | Summary

![多模态](https://github.com/user-attachments/assets/d39f54f3-7eda-4fc7-b63f-48dbb513f49c)
加wx: yzyykm666，备注：MLLM ，邀请你加群哈！！！

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by LDLINGLINGLING** [comment]
非常感谢
