### ISSUE TITLE
[BUG] <在funetune/dataset.py中报告image start token != image end tokens的错误>

### ISSUE THREAD

**Issue by KeepFaithMe** [OpenBMB/MiniCPM-V#587]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在执行funetune_lora.py时，出现image start token != image end tokens的错误，我将与报错相关的变量打印出来，其结果如下：image_start_tokens:  tensor([], dtype=torch.int64)
image_end_tokens:  tensor([66])
image_start_tokens是空，它的结果来源于这一段代码：“image_start_tokens = torch.where(ids == tokenizer.im_start_id)[0]”，也就是说ids中不存在与tokenizer.im_start_id相等的值。
ids，image_start_tokens ，image_end_tokens三个变量的结果如下图：
![1726658289123](https://github.com/user-attachments/assets/0d2439b6-b109-47be-875a-816d8c5e2ad9)
数据的组织方式如下：
![1726658383833](https://github.com/user-attachments/assets/31f5a003-ab91-42b4-bf39-c555b519e9e5)

### 期望行为 | Expected Behavior

解决上述bug

### 复现方法 | Steps To Reproduce

配置好基本环境，按照图2的数据组织方式即可复现，注意，测试数据确实只包含了一张图片，但我也测试过多张图片，也不对。

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04
- Python:3.10
- Transformers: 4.40.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by KeepFaithMe** [comment]
补充一下，微调使用的模型是MiniCPM-V-int4

**Comment by XHB-ZMM** [comment]
如果你的对话中，除了第一个user有<image>\n，同一个对话的某些user也有<image>\n占位符，就会出现这个错误

**Comment by natsoe7** [comment]
lapyae
