### ISSUE TITLE
💡 [REQUEST] - MiniCPM-V支持OCR 识别返回文字坐标

### ISSUE THREAD

**Issue by FreemanFeng** [OpenBMB/MiniCPM-V#594]
### 摘要 | Summary

目前只能通过 OCR 识别到文字，但并不能准确返回文字坐标

### 基本示例 | Basic Example

识别图中文字并返回相应坐标，用以下json 格式返回：{"text":<识别到的文字>, "box": <[xmin, ymin, width, height]>}

### 缺陷 | Drawbacks

不确定

**Comment by LDLINGLINGLING** [comment]
https://modelbest.feishu.cn/wiki/HLRiwNgKEic6cckGyGucFvxQnJw?from=from_copylink请查看这篇教程
