### ISSUE TITLE
💡 [REQUEST] - <title> Embedding for text and images: is it teoretically possible?

### ISSUE THREAD

**Issue by vlavorini** [OpenBMB/MiniCPM-V#597]
### 起始日期 | Start Date

any

### 实现PR | Implementation PR

any

### 相关Issues | Reference Issues

#506

### 摘要 | Summary

Is it possible to extract the embeddings for images and text?
And if yes, will those embeddings lie in the same vectorial space, i.e., the embeddig of a dog's picture will be near the text "a dog"

### 基本示例 | Basic Example

none needed

### 缺陷 | Drawbacks

na

### 未解决问题 | Unresolved questions

na

**Comment by LDLINGLINGLING** [comment]
Hello, it may need retraining at present, and the effect of direct alignment has not been tested. maybe you should look follow blog
https://modelbest.feishu.cn/wiki/NdEjwo0hxilCIikN6RycOKp0nYf?from=from_copylink
