### ISSUE TITLE
💡多图推理（multi-images inference），是否支持多图推理呢？

### ISSUE THREAD

**Issue by XHB-ZMM** [OpenBMB/MiniCPM-V#599]
### 实现PR | Implementation PR

1

### 相关Issues | Reference Issues

1

### 摘要 | Summary

1

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

1

**Comment by LDLINGLINGLING** [comment]
https://modelbest.feishu.cn/wiki/LZxLwp4Lzi29vXklYLFchwN5nCf?from=from_copylink，你好，这里面有多图推理的示例

**Comment by XHB-ZMM** [comment]
> [https://modelbest.feishu.cn/wiki/LZxLwp4Lzi29vXklYLFchwN5nCf?from=from_copylink，你好，这里面有多图推理的示例](https://modelbest.feishu.cn/wiki/LZxLwp4Lzi29vXklYLFchwN5nCf?from=from_copylink%EF%BC%8C%E4%BD%A0%E5%A5%BD%EF%BC%8C%E8%BF%99%E9%87%8C%E9%9D%A2%E6%9C%89%E5%A4%9A%E5%9B%BE%E6%8E%A8%E7%90%86%E7%9A%84%E7%A4%BA%E4%BE%8B)

非常非常感谢！！！！！！
