### ISSUE TITLE
[BUG] <title> 内存增加/泄漏

### ISSUE THREAD

**Issue by JianbangZ** [OpenBMB/MiniCPM-V#603]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我有个比较大的数据集，10个json加起来16M images, 训练过程中随着时间的推移物理内存（CPU内存）一直缓慢增加，从刚开始的300GB增加到后来的1TB导致程序崩溃退出。 什么原因呢？
其实内存使用增加的情况在小数据集也一样，但没那么明显。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JianbangZ** [comment]
switching to parquet file solved the problem

**Comment by zjykzj** [comment]
> switching to parquet file solved the problem

@JianbangZ May I ask how it was implemented, please.

Related issues #705
