### ISSUE TITLE
object detection能力

### ISSUE THREAD

**Issue by hardlipay** [OpenBMB/MiniCPM-V#62]
请问，支持detection返回bbox吗？很多多模态模型已经支持了，且性能也很优秀，为什么cpmv我测了感觉不支持。
但是cpmv对空间位置关系的感知能力也很强，是什么原因导致放弃了训练这一功能呢？
如果加上detect的预训练，做finetune时有bbox输入对应文本，是否能让模型更容易获取新知识？

**Comment by YuzaChongyi** [comment]
你好，感谢建议，minicpm-v-2 在训练的时候 general grounding 的数据比较少，并且 sft 阶段也没有专门加入 grounding 数据来增强模型的定位能力，所以当前开源模型不太能支持输入指令让模型返回目标 bbox，我们会考虑在后续的迭代中加上这个能力。

**Comment by songofhawk** [comment]
强烈需要啊，如果 MiniCPM 支持返回 bbox 就完美了

**Comment by songofhawk** [comment]
> 请问，支持detection返回bbox吗？很多多模态模型已经支持了，且性能也很优秀，为什么cpmv我测了感觉不支持。 但是cpmv对空间位置关系的感知能力也很强，是什么原因导致放弃了训练这一功能呢？ 如果加上detect的预训练，做finetune时有bbox输入对应文本，是否能让模型更容易获取新知识？

现在哪些模型支持返回 bbox 了？

**Comment by hardlipay** [comment]
> > 请问，支持detection返回bbox吗？很多多模态模型已经支持了，且性能也很优秀，为什么cpmv我测了感觉不支持。 但是cpmv对空间位置关系的感知能力也很强，是什么原因导致放弃了训练这一功能呢？ 如果加上detect的预训练，做finetune时有bbox输入对应文本，是否能让模型更容易获取新知识？
> 
> 现在哪些模型支持返回 bbox 了？

很多吧。
最早的工作应该是这个吧 [https://github.com/shikras/shikra](https://github.com/shikras/shikra)

**Comment by songofhawk** [comment]
谢谢，我也找到 shikra 了，后来还试了 Qwen-VL，不过它们的 bbox 也不是很准，期待新的模型出现
