### ISSUE TITLE
[BUG] <title>data fetch error

### ISSUE THREAD

**Issue by ydaiwxl** [OpenBMB/MiniCPM-V#645]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在dataset.py的383行有点问题，conversation[0]["content"]应该改成conversations[0]["content"]

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
您好，感谢您的反馈，我们正在看这个问题

**Comment by LDLINGLINGLING** [comment]
已经修改代码，谢谢您的反馈
