### ISSUE TITLE
💡 [REQUEST] - 使用OCR识别场景中，若图片有手写删除的痕迹，是否可以准确理解并屏蔽不需的信息？

### ISSUE THREAD

**Issue by evanlin88** [OpenBMB/MiniCPM-V#678]
### 摘要 | Summary

使用OCR识别场景中，若图片有手写删除的痕迹，是否可以准确理解并屏蔽不需的信息？

### 基本示例 | Basic Example

![32](https://github.com/user-attachments/assets/d5839172-2302-4485-9dbe-5bbdd2573ddb)
![44](https://github.com/user-attachments/assets/94f17459-a8ae-434c-8fc1-01f425b15a62)
![20241106--440](https://github.com/user-attachments/assets/569e4069-377e-44de-a88d-492519bebd99)
![20241106--1090](https://github.com/user-attachments/assets/64e3cfc3-15ba-41a2-951a-876a72097e2b)
![20241106--1553](https://github.com/user-attachments/assets/034c3d1e-2ef3-46bb-8072-be529eb3ecef)
![20241106--1554](https://github.com/user-attachments/assets/3b1ff694-8998-468d-9266-7a2d3299832c)

### 缺陷 | Drawbacks

在手工OCR识别的情况，针对手工“涂改”的位置，目前没更好的方式，能准确识别出真正的意图结果

**Comment by LDLINGLINGLING** [comment]
你好，这种场景可能需要微调，你构造数据输出的时候忽略这些被删掉的图片，应该就可以

**Comment by evanlin88** [comment]
> 你好，这种场景可能需要微调，你构造数据输出的时候忽略这些被删掉的图片，应该就可以

ok，我试试
