### ISSUE TITLE
[BUG] why is the vocab_size of MiniCPM-V-2_6 not the same as Qwen2-7B?

### ISSUE THREAD

**Issue by LSC527** [OpenBMB/MiniCPM-V#699]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

vocab_size of MiniCPM-V-2_6: 151666
vocab_size of Qwen2-7B: 152064

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by LDLINGLINGLING** [comment]
hello，the language model of MinicpmV2.6 is qwen2-7b

**Comment by LSC527** [comment]
Vocab_size of Qwen2-7B in its config.json is wrong. Actual vocab_size of Qwen2-7B is 151646. MiniCPM-V-2_6 has 20 larger vocab_size 151666 which makes sense.
