### ISSUE TITLE
OmniLMM-12B下载到本地无法运行 #67

### ISSUE THREAD

**Issue by rogermayo182** [OpenBMB/MiniCPM-V#70]
![1713856321333](https://github.com/OpenBMB/MiniCPM-V/assets/26639421/64c9b538-1d49-4c94-bc77-6c81b53a611e)
![1713856452853](https://github.com/OpenBMB/MiniCPM-V/assets/26639421/b6bb0525-5d78-4960-8050-f1a81791c3de)

pytorch version:2.1.2+cu121
报问题的代码：
![image](https://github.com/OpenBMB/MiniCPM-V/assets/26639421/474ebef2-2532-47ee-a3be-d70d3bc00f5a)

**Comment by rogermayo182** [comment]
1，python chat.py文件已经可以运行，愿意是下载的模型文件夹更改了名字，没有含12B字样，而代码硬编码检查12B字样来选择路径；
2，web_demo.py还不能运行，报相同的问题，KeyError:'omnilmm'

**Comment by iceflame89** [comment]
web_demo.py 只实现了调用MiniCPM-V 1.0/2.0模型,  OmniLMM-12B可参考chat.py 中调用方式自行修改～

**Comment by rogermayo182** [comment]
OK，已经讲chat.py引用过来了。
