### ISSUE TITLE
MiniCPM Demo not usable /MiniCPM Demo不可用

### ISSUE THREAD

**Issue by fanatic-revolver** [OpenBMB/MiniCPM-V#75]
<img width="411" alt="微信图片_20240424153933" src="https://github.com/OpenBMB/MiniCPM-V/assets/40350547/10c7a4c2-31cf-44f0-a1f8-68d39b1e0829">
如题

**Comment by iceflame89** [comment]
Please use huggingface space demo https://huggingface.co/spaces/openbmb/MiniCPM-V-2
