### ISSUE TITLE
MiniCPM-v2的对话能力

### ISSUE THREAD

**Issue by yayafengzi** [OpenBMB/MiniCPM-V#79]
你好！MiniCPM-v2已被证实在提取高分辨率图片中的文本信息时拥有令人惊叹的准确度，并且远强于ominillm-12b，是非常优秀的模型。然而，可能是llm参数量太小的原因，MiniCPM-v2遵循人类指令和生成较长文本的能力比较弱。非常期待更大参数规模版本的MiniCPM-v2。

**Comment by zRzRzRzRzRzRzR** [comment]
应该只能做基础一点的多模态内容，我测的时候是这样的，但是提取等相关内容确实不错

**Comment by iceflame89** [comment]
感谢关注！近期我们将会有新的版本发布，敬请期待～

**Comment by ye7love7** [comment]
> 感谢关注！近期我们将会有新的版本发布，敬请期待～

请问VLLM 0.4.2报Model architectures ['MiniCPMV'] are not supported for now
应该怎么解决，VLLM版本降级吗？

**Comment by iceflame89** [comment]
> 
> 请问VLLM 0.4.2报Model architectures ['MiniCPMV'] are not supported for now 应该怎么解决，VLLM版本降级吗？

目前MiniCPM-V 2.0暂未合入官方vllm，请从https://github.com/OpenBMB/vllm 编译使用

**Comment by iceflame89** [comment]
@yayafengzi @zRzRzRzRzRzRzR  更大参数版本MiniCPM-Llama3-V 2.5现已发布，更大更强，欢迎关注
