### ISSUE TITLE
请问minicpm-v 能微调做图像分类任务吗？

### ISSUE THREAD

**Issue by jayslife0** [OpenBMB/MiniCPM-V#83]
minicpm-v 能微调做图像分类任务吗？怎样实现？

**Comment by YuzaChongyi** [comment]
你好，理论上可以支持分类任务，你可以把分类任务转换成选择题形式，或者开放标签生成形式，并把数据转换成 QA-pair，具体样例可以参考 [finetune](https://github.com/OpenBMB/MiniCPM-V/tree/main/finetune)
