### ISSUE TITLE
请问OmniLMM-12B能8bit量化吗？

### ISSUE THREAD

**Issue by jiayev** [OpenBMB/MiniCPM-V#86]
个人研究使用24GB的4090，在实际环境中非常容易爆显存。

**Comment by iceflame89** [comment]
你好，OmniLMM-12B暂没有做int8量化，我们新发布了更强大的[MiniCPM-Llama3-V 2.5](https://github.com/OpenBMB/MiniCPM-V?tab=readme-ov-file#minicpm-llama3-v-25) ，总参数量8.5B，性能比肩GPT-4V，且有[int4量化](https://github.com/OpenBMB/MiniCPM-V?tab=readme-ov-file#%E6%A8%A1%E5%9E%8B%E5%BA%93)版本，欢迎试用～
