### ISSUE TITLE
mlc-MiniCPM: quantized to 4-bit

### ISSUE THREAD

**Issue by Fanthers** [OpenBMB/MiniCPM-V#87]
Note that the models run on android are quantized to 4-bit and may lose some performance. The non-quantized models can be found [here](https://github.com/OpenBMB/miniCPM).

我想问下4-bit量化的模型在哪里可以找到呢？想知道是多大参数的模型，以及如何进行量化，我看目前只有微调功能

**Comment by iceflame89** [comment]
MiniCPM-V 1.0 模型见[huggingface](https://huggingface.co/openbmb/MiniCPM-V) 2.8B参数.
量化方法见mlc-MiniCPM [readme](https://github.com/OpenBMB/mlc-MiniCPM?tab=readme-ov-file#compile-model).

**Comment by Fanthers** [comment]
> MiniCPM-V 1.0 模型见[huggingface](https://huggingface.co/openbmb/MiniCPM-V) 2.8B参数. 量化方法见mlc-MiniCPM [readme](https://github.com/OpenBMB/mlc-MiniCPM?tab=readme-ov-file#compile-model).

4bit模型可以拿到嘛？

**Comment by RLHF-V** [comment]
You can access the 4bit version of MiniCPM-Llama3-V 2.5 at [here](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5-int4/).

**Comment by Fanthers** [comment]
> You can access the 4bit version of MiniCPM-Llama3-V 2.5 at [here](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5-int4/).

thanks
