### ISSUE TITLE
用swift微调MiniCPM-V 2.0，loss一直为0

### ISSUE THREAD

**Issue by darklianyu** [OpenBMB/MiniCPM-V#89]
swift是直接从github拉的，好像是2.1版，使用默认参数,能跑起来，但是loss一直是0

**Comment by darklianyu** [comment]
![image](https://github.com/OpenBMB/MiniCPM-V/assets/50630477/a616b141-68ed-45cb-9530-a8668c2b964f)
我是按照swift的文档准备的数据

**Comment by YuzaChongyi** [comment]
你好，可以试一下我们提供的更简易的 [finetune](https://github.com/OpenBMB/MiniCPM-V/tree/main/finetune) 代码
