### ISSUE TITLE
Finetuned MiniCPM-V2.5 erro

### ISSUE THREAD

**Issue by zfy1041264242** [OpenBMB/MiniCPM-V#93]
I'm trying to fine-tune MiniCPM-V2.5, but I get the following error:
   
    f"{','.join(outputs.keys())}. For reference, the inputs it received are {
    ^
SyntaxError: unterminated string literal (detected at line 38)

**Comment by YuzaChongyi** [comment]
It's looks like something wrong with the input data, can you share your training example?

**Comment by Gary2018X** [comment]
一样的报错
示例数据集
```
[
  {
    "id": "1",
    "image": "./images/image.jpg",
    "conversations": [
      {
        "role": "user",
        "content": "<image>\n这张图片有什么？"
      },
      {
        "role": "assistant",
        "content": "有A B C D 。"
      }
    ]
  }
】
```

**Comment by YuzaChongyi** [comment]
Sorry for the extra line break in the code format, we have fixed the code, you can try it again.

**Comment by yipoh** [comment]
Hello author! We fine-tuned as required and encountered an error, which seemed to be caused by inconsistent dimensions. How can I fix this? Thank you

![e5286715c1d4734463d8435fa57eaa2](https://github.com/OpenBMB/MiniCPM-V/assets/124764227/ae81b5d1-eb5e-4334-8888-6da7bc9bf98c)
