### ISSUE TITLE
VisionEncoder里面的vit，用的是idefics2还是 hf4m那个啊？

### ISSUE THREAD

**Issue by MonolithFoundation** [OpenBMB/MiniCPM-V#94]
VisionEncoder里面的vit，与训练 权重 用的是idefics2还是 hf4m那个啊？

**Comment by iceflame89** [comment]
idefics2

**Comment by MonolithFoundation** [comment]
直接从idefics2加载的ve权重？



---- 回复的原邮件 ----
| 发件人 | Hongji ***@***.***> |
| 日期 | 2024年05月20日 19:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [OpenBMB/MiniCPM-V] VisionEncoder里面的vit，用的是idefics2还是 hf4m那个啊？ (Issue #94) |

idefics2

**Comment by YuzaChongyi** [comment]
> 直接从idefics2加载的ve权重？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Hongji ***@***.***> | | 日期 | 2024年05月20日 19:27 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [OpenBMB/MiniCPM-V] VisionEncoder里面的vit，用的是idefics2还是 hf4m那个啊？ (Issue #94) | idefics2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你好，我们的初始化权重是siglip-so400m 的预训练权重，参考[siglip-so400m-14-980-flash-attn2-navit](https://huggingface.co/HuggingFaceM4/siglip-so400m-14-980-flash-attn2-navit/tree/main)，推理代码改成 idefics2 是因为idefics2 已经合入 transfomers 官方仓库中，集成更方便一些 (两者实现是一致的)

**Comment by MonolithFoundation** [comment]
你确定？？？

**Comment by YuzaChongyi** [comment]
> Same as https://huggingface.co/HuggingFaceM4/siglip-so400m-14-384-flash-attn2 with two changes:
> 
> increase max resolution to 980 x 980 (instead of 384 x 384) by interpolating the position embeddings
> implement the strategy in [NaViT](https://arxiv.org/abs/2307.06304) to allow a/ variable resoltion images, b/ aspect ratio preserved images

[siglip-so400m-14-980-flash-attn2-navit](https://huggingface.co/HuggingFaceM4/siglip-so400m-14-980-flash-attn2-navit/tree/main) 只修改了 position embeddings 部分
