### ISSUE TITLE
Mac推理报错

### ISSUE THREAD

**Issue by bookandlover** [OpenBMB/MiniCPM-V#96]
PYTORCH_ENABLE_MPS_FALLBACK=1 python macinfer.py
/Users/peng/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/Users/peng/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████| 7/7 [00:06<00:00,  1.04it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/Users/peng/miniconda3/envs/MiniCPMV/lib/python3.10/site-packages/transformers/generation/stopping_criteria.py:149: UserWarning: The operator 'aten::isin.Tensor_Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
  is_done = torch.isin(input_ids[:, -1], self.eos_token_id.to(input_ids.device))
Answer: t
Context: r

**Comment by bookandlover** [comment]
Yes, no other error message. Codes can be executed successfully. Changed some pics and with same printed contents.

M2 Ultra 192G

Thanks.

2024年5月20日 20:18，Hongji Zhu ***@***.***> 写道：



No any other error message? Just stuck there or exited?

**Comment by Cuiunbo** [comment]
In order to solve the problem reproducible code needs to be provided~
 @bookandlover
