### ISSUE TITLE
Can u opensoure the Chinese ocr part data?

### ISSUE THREAD

**Issue by lucasjinreal** [OpenBMB/MiniCPM-V#98]
Can u opensoure the Chinese ocr part data?

**Comment by Cuiunbo** [comment]
Our Chinese OCR data is mainly collected from open-source data, later this week, the technical report will be released～

**Comment by Cuiunbo** [comment]
The details can be found in the technical report, which will be released this week～
If you still have any questions at that point, just let us know.

**Comment by xxlxms** [comment]
where the report
