### ISSUE TITLE
Offical Demo web site error.

### ISSUE THREAD

**Issue by wikeeyang** [OpenBMB/MiniCPM-V#99]
![120 92 209 146-8899-01](https://github.com/OpenBMB/MiniCPM-V/assets/131220899/fe9ed8a3-4f3c-445e-9674-3cd5ea130a00)
![120 92 209 146-8899-02](https://github.com/OpenBMB/MiniCPM-V/assets/131220899/c782d8fe-78f7-435a-b66f-f7d5b2e944ad)

can't accept any prompt, no any response.

**Comment by iceflame89** [comment]
Input question and press “Enter” other than click “Regenerate”

**Comment by wikeeyang** [comment]
Sorry for the misunderstanding...
